// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/Roisfaozi/queue-base/internal/modules/organization/entity"
	mock "github.com/stretchr/testify/mock"
)

// MockBranchRepository is an autogenerated mock type for the BranchRepository type
type MockBranchRepository struct {
	mock.Mock
}

type MockBranchRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBranchRepository) EXPECT() *MockBranchRepository_Expecter {
	return &MockBranchRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, branch
func (_m *MockBranchRepository) Create(ctx context.Context, branch *entity.Branch) error {
	ret := _m.Called(ctx, branch)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Branch) error); ok {
		r0 = rf(ctx, branch)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBranchRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockBranchRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - branch *entity.Branch
func (_e *MockBranchRepository_Expecter) Create(ctx interface{}, branch interface{}) *MockBranchRepository_Create_Call {
	return &MockBranchRepository_Create_Call{Call: _e.mock.On("Create", ctx, branch)}
}

func (_c *MockBranchRepository_Create_Call) Run(run func(ctx context.Context, branch *entity.Branch)) *MockBranchRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Branch))
	})
	return _c
}

func (_c *MockBranchRepository_Create_Call) Return(_a0 error) *MockBranchRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBranchRepository_Create_Call) RunAndReturn(run func(context.Context, *entity.Branch) error) *MockBranchRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, tenantID, branchID
func (_m *MockBranchRepository) Delete(ctx context.Context, tenantID string, branchID string) error {
	ret := _m.Called(ctx, tenantID, branchID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, tenantID, branchID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBranchRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockBranchRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID string
//   - branchID string
func (_e *MockBranchRepository_Expecter) Delete(ctx interface{}, tenantID interface{}, branchID interface{}) *MockBranchRepository_Delete_Call {
	return &MockBranchRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, tenantID, branchID)}
}

func (_c *MockBranchRepository_Delete_Call) Run(run func(ctx context.Context, tenantID string, branchID string)) *MockBranchRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockBranchRepository_Delete_Call) Return(_a0 error) *MockBranchRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBranchRepository_Delete_Call) RunAndReturn(run func(context.Context, string, string) error) *MockBranchRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function with given fields: ctx, tenantID
func (_m *MockBranchRepository) FindAll(ctx context.Context, tenantID string) ([]*entity.Branch, error) {
	ret := _m.Called(ctx, tenantID)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []*entity.Branch
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*entity.Branch, error)); ok {
		return rf(ctx, tenantID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*entity.Branch); ok {
		r0 = rf(ctx, tenantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Branch)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tenantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBranchRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockBranchRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID string
func (_e *MockBranchRepository_Expecter) FindAll(ctx interface{}, tenantID interface{}) *MockBranchRepository_FindAll_Call {
	return &MockBranchRepository_FindAll_Call{Call: _e.mock.On("FindAll", ctx, tenantID)}
}

func (_c *MockBranchRepository_FindAll_Call) Run(run func(ctx context.Context, tenantID string)) *MockBranchRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockBranchRepository_FindAll_Call) Return(_a0 []*entity.Branch, _a1 error) *MockBranchRepository_FindAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBranchRepository_FindAll_Call) RunAndReturn(run func(context.Context, string) ([]*entity.Branch, error)) *MockBranchRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, tenantID, branchID
func (_m *MockBranchRepository) FindByID(ctx context.Context, tenantID string, branchID string) (*entity.Branch, error) {
	ret := _m.Called(ctx, tenantID, branchID)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entity.Branch
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*entity.Branch, error)); ok {
		return rf(ctx, tenantID, branchID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *entity.Branch); ok {
		r0 = rf(ctx, tenantID, branchID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Branch)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, tenantID, branchID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBranchRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockBranchRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID string
//   - branchID string
func (_e *MockBranchRepository_Expecter) FindByID(ctx interface{}, tenantID interface{}, branchID interface{}) *MockBranchRepository_FindByID_Call {
	return &MockBranchRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, tenantID, branchID)}
}

func (_c *MockBranchRepository_FindByID_Call) Run(run func(ctx context.Context, tenantID string, branchID string)) *MockBranchRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockBranchRepository_FindByID_Call) Return(_a0 *entity.Branch, _a1 error) *MockBranchRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBranchRepository_FindByID_Call) RunAndReturn(run func(context.Context, string, string) (*entity.Branch, error)) *MockBranchRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, branch
func (_m *MockBranchRepository) Update(ctx context.Context, branch *entity.Branch) error {
	ret := _m.Called(ctx, branch)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Branch) error); ok {
		r0 = rf(ctx, branch)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBranchRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockBranchRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - branch *entity.Branch
func (_e *MockBranchRepository_Expecter) Update(ctx interface{}, branch interface{}) *MockBranchRepository_Update_Call {
	return &MockBranchRepository_Update_Call{Call: _e.mock.On("Update", ctx, branch)}
}

func (_c *MockBranchRepository_Update_Call) Run(run func(ctx context.Context, branch *entity.Branch)) *MockBranchRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Branch))
	})
	return _c
}

func (_c *MockBranchRepository_Update_Call) Return(_a0 error) *MockBranchRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBranchRepository_Update_Call) RunAndReturn(run func(context.Context, *entity.Branch) error) *MockBranchRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBranchRepository creates a new instance of MockBranchRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBranchRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBranchRepository {
	mock := &MockBranchRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
