// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Roisfaozi/queue-base/internal/modules/organization/model"
	"github.com/Roisfaozi/queue-base/pkg/ws"
	mock "github.com/stretchr/testify/mock"
)

// NewMockOrganizationUseCase creates a new instance of MockOrganizationUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrganizationUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrganizationUseCase {
	m := &MockOrganizationUseCase{}
	m.Mock.Test(t)

	t.Cleanup(func() { m.AssertExpectations(t) })

	return m
}

// MockOrganizationUseCase is an autogenerated mock type for the OrganizationUseCase type
type MockOrganizationUseCase struct {
	mock.Mock
}

type MockOrganizationUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrganizationUseCase) EXPECT() *MockOrganizationUseCase_Expecter {
	return &MockOrganizationUseCase_Expecter{mock: &_m.Mock}
}

// CreateOrganization provides a mock function for the type MockOrganizationUseCase
func (_mock *MockOrganizationUseCase) CreateOrganization(ctx context.Context, userID string, request *model.CreateOrganizationRequest) (*model.OrganizationResponse, error) {
	ret := _mock.Called(ctx, userID, request)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrganization")
	}

	var r0 *model.OrganizationResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *model.CreateOrganizationRequest) (*model.OrganizationResponse, error)); ok {
		return returnFunc(ctx, userID, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *model.CreateOrganizationRequest) *model.OrganizationResponse); ok {
		r0 = returnFunc(ctx, userID, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.OrganizationResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *model.CreateOrganizationRequest) error); ok {
		r1 = returnFunc(ctx, userID, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrganizationUseCase_CreateOrganization_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrganization'
type MockOrganizationUseCase_CreateOrganization_Call struct {
	*mock.Call
}

// CreateOrganization is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - request *model.CreateOrganizationRequest
func (_e *MockOrganizationUseCase_Expecter) CreateOrganization(ctx interface{}, userID interface{}, request interface{}) *MockOrganizationUseCase_CreateOrganization_Call {
	return &MockOrganizationUseCase_CreateOrganization_Call{Call: _e.mock.On("CreateOrganization", ctx, userID, request)}
}

func (_c *MockOrganizationUseCase_CreateOrganization_Call) Run(run func(ctx context.Context, userID string, request *model.CreateOrganizationRequest)) *MockOrganizationUseCase_CreateOrganization_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *model.CreateOrganizationRequest
		if args[2] != nil {
			arg2 = args[2].(*model.CreateOrganizationRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockOrganizationUseCase_CreateOrganization_Call) Return(organizationResponse *model.OrganizationResponse, err error) *MockOrganizationUseCase_CreateOrganization_Call {
	_c.Call.Return(organizationResponse, err)
	return _c
}

func (_c *MockOrganizationUseCase_CreateOrganization_Call) RunAndReturn(run func(ctx context.Context, userID string, request *model.CreateOrganizationRequest) (*model.OrganizationResponse, error)) *MockOrganizationUseCase_CreateOrganization_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteOrganization provides a mock function for the type MockOrganizationUseCase
func (_mock *MockOrganizationUseCase) DeleteOrganization(ctx context.Context, id string, userID string) error {
	ret := _mock.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOrganization")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, id, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrganizationUseCase_DeleteOrganization_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteOrganization'
type MockOrganizationUseCase_DeleteOrganization_Call struct {
	*mock.Call
}

// DeleteOrganization is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - userID string
func (_e *MockOrganizationUseCase_Expecter) DeleteOrganization(ctx interface{}, id interface{}, userID interface{}) *MockOrganizationUseCase_DeleteOrganization_Call {
	return &MockOrganizationUseCase_DeleteOrganization_Call{Call: _e.mock.On("DeleteOrganization", ctx, id, userID)}
}

func (_c *MockOrganizationUseCase_DeleteOrganization_Call) Run(run func(ctx context.Context, id string, userID string)) *MockOrganizationUseCase_DeleteOrganization_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockOrganizationUseCase_DeleteOrganization_Call) Return(err error) *MockOrganizationUseCase_DeleteOrganization_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrganizationUseCase_DeleteOrganization_Call) RunAndReturn(run func(ctx context.Context, id string, userID string) error) *MockOrganizationUseCase_DeleteOrganization_Call {
	_c.Call.Return(run)
	return _c
}

// RestoreOrganization provides a mock function for the type MockOrganizationUseCase
func (_mock *MockOrganizationUseCase) RestoreOrganization(ctx context.Context, id string) (*model.OrganizationResponse, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for RestoreOrganization")
	}

	var r0 *model.OrganizationResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.OrganizationResponse, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.OrganizationResponse); ok {
		r0 = returnFunc(ctx, id)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).(*model.OrganizationResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

type MockOrganizationUseCase_RestoreOrganization_Call struct {
	*mock.Call
}

func (_e *MockOrganizationUseCase_Expecter) RestoreOrganization(ctx interface{}, id interface{}) *MockOrganizationUseCase_RestoreOrganization_Call {
	return &MockOrganizationUseCase_RestoreOrganization_Call{Call: _e.mock.On("RestoreOrganization", ctx, id)}
}

func (_c *MockOrganizationUseCase_RestoreOrganization_Call) Run(run func(ctx context.Context, id string)) *MockOrganizationUseCase_RestoreOrganization_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(arg0, arg1)
	})
	return _c
}

func (_c *MockOrganizationUseCase_RestoreOrganization_Call) Return(organizationResponse *model.OrganizationResponse, err error) *MockOrganizationUseCase_RestoreOrganization_Call {
	_c.Call.Return(organizationResponse, err)
	return _c
}

func (_c *MockOrganizationUseCase_RestoreOrganization_Call) RunAndReturn(run func(ctx context.Context, id string) (*model.OrganizationResponse, error)) *MockOrganizationUseCase_RestoreOrganization_Call {
	_c.Call.Return(run)
	return _c
}

// HardDeleteOrganization provides a mock function for the type MockOrganizationUseCase
func (_mock *MockOrganizationUseCase) HardDeleteOrganization(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for HardDeleteOrganization")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

type MockOrganizationUseCase_HardDeleteOrganization_Call struct {
	*mock.Call
}

func (_e *MockOrganizationUseCase_Expecter) HardDeleteOrganization(ctx interface{}, id interface{}) *MockOrganizationUseCase_HardDeleteOrganization_Call {
	return &MockOrganizationUseCase_HardDeleteOrganization_Call{Call: _e.mock.On("HardDeleteOrganization", ctx, id)}
}

func (_c *MockOrganizationUseCase_HardDeleteOrganization_Call) Run(run func(ctx context.Context, id string)) *MockOrganizationUseCase_HardDeleteOrganization_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(arg0, arg1)
	})
	return _c
}

func (_c *MockOrganizationUseCase_HardDeleteOrganization_Call) Return(err error) *MockOrganizationUseCase_HardDeleteOrganization_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrganizationUseCase_HardDeleteOrganization_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockOrganizationUseCase_HardDeleteOrganization_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrganization provides a mock function for the type MockOrganizationUseCase
func (_mock *MockOrganizationUseCase) GetOrganization(ctx context.Context, id string) (*model.OrganizationResponse, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetOrganization")
	}

	var r0 *model.OrganizationResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.OrganizationResponse, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.OrganizationResponse); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.OrganizationResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrganizationUseCase_GetOrganization_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrganization'
type MockOrganizationUseCase_GetOrganization_Call struct {
	*mock.Call
}

// GetOrganization is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockOrganizationUseCase_Expecter) GetOrganization(ctx interface{}, id interface{}) *MockOrganizationUseCase_GetOrganization_Call {
	return &MockOrganizationUseCase_GetOrganization_Call{Call: _e.mock.On("GetOrganization", ctx, id)}
}

func (_c *MockOrganizationUseCase_GetOrganization_Call) Run(run func(ctx context.Context, id string)) *MockOrganizationUseCase_GetOrganization_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrganizationUseCase_GetOrganization_Call) Return(organizationResponse *model.OrganizationResponse, err error) *MockOrganizationUseCase_GetOrganization_Call {
	_c.Call.Return(organizationResponse, err)
	return _c
}

func (_c *MockOrganizationUseCase_GetOrganization_Call) RunAndReturn(run func(ctx context.Context, id string) (*model.OrganizationResponse, error)) *MockOrganizationUseCase_GetOrganization_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrganizationBySlug provides a mock function for the type MockOrganizationUseCase
func (_mock *MockOrganizationUseCase) GetOrganizationBySlug(ctx context.Context, slug string) (*model.OrganizationResponse, error) {
	ret := _mock.Called(ctx, slug)

	if len(ret) == 0 {
		panic("no return value specified for GetOrganizationBySlug")
	}

	var r0 *model.OrganizationResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.OrganizationResponse, error)); ok {
		return returnFunc(ctx, slug)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.OrganizationResponse); ok {
		r0 = returnFunc(ctx, slug)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.OrganizationResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, slug)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrganizationUseCase_GetOrganizationBySlug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrganizationBySlug'
type MockOrganizationUseCase_GetOrganizationBySlug_Call struct {
	*mock.Call
}

// GetOrganizationBySlug is a helper method to define mock.On call
//   - ctx context.Context
//   - slug string
func (_e *MockOrganizationUseCase_Expecter) GetOrganizationBySlug(ctx interface{}, slug interface{}) *MockOrganizationUseCase_GetOrganizationBySlug_Call {
	return &MockOrganizationUseCase_GetOrganizationBySlug_Call{Call: _e.mock.On("GetOrganizationBySlug", ctx, slug)}
}

func (_c *MockOrganizationUseCase_GetOrganizationBySlug_Call) Run(run func(ctx context.Context, slug string)) *MockOrganizationUseCase_GetOrganizationBySlug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrganizationUseCase_GetOrganizationBySlug_Call) Return(organizationResponse *model.OrganizationResponse, err error) *MockOrganizationUseCase_GetOrganizationBySlug_Call {
	_c.Call.Return(organizationResponse, err)
	return _c
}

func (_c *MockOrganizationUseCase_GetOrganizationBySlug_Call) RunAndReturn(run func(ctx context.Context, slug string) (*model.OrganizationResponse, error)) *MockOrganizationUseCase_GetOrganizationBySlug_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserOrganizations provides a mock function for the type MockOrganizationUseCase
func (_mock *MockOrganizationUseCase) GetUserOrganizations(ctx context.Context, userID string) (*model.UserOrganizationsResponse, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserOrganizations")
	}

	var r0 *model.UserOrganizationsResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.UserOrganizationsResponse, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.UserOrganizationsResponse); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserOrganizationsResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrganizationUseCase_GetUserOrganizations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserOrganizations'
type MockOrganizationUseCase_GetUserOrganizations_Call struct {
	*mock.Call
}

// GetUserOrganizations is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockOrganizationUseCase_Expecter) GetUserOrganizations(ctx interface{}, userID interface{}) *MockOrganizationUseCase_GetUserOrganizations_Call {
	return &MockOrganizationUseCase_GetUserOrganizations_Call{Call: _e.mock.On("GetUserOrganizations", ctx, userID)}
}

func (_c *MockOrganizationUseCase_GetUserOrganizations_Call) Run(run func(ctx context.Context, userID string)) *MockOrganizationUseCase_GetUserOrganizations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrganizationUseCase_GetUserOrganizations_Call) Return(userOrganizationsResponse *model.UserOrganizationsResponse, err error) *MockOrganizationUseCase_GetUserOrganizations_Call {
	_c.Call.Return(userOrganizationsResponse, err)
	return _c
}

func (_c *MockOrganizationUseCase_GetUserOrganizations_Call) RunAndReturn(run func(ctx context.Context, userID string) (*model.UserOrganizationsResponse, error)) *MockOrganizationUseCase_GetUserOrganizations_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOrganization provides a mock function for the type MockOrganizationUseCase
func (_mock *MockOrganizationUseCase) UpdateOrganization(ctx context.Context, id string, request *model.UpdateOrganizationRequest) (*model.OrganizationResponse, error) {
	ret := _mock.Called(ctx, id, request)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrganization")
	}

	var r0 *model.OrganizationResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *model.UpdateOrganizationRequest) (*model.OrganizationResponse, error)); ok {
		return returnFunc(ctx, id, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *model.UpdateOrganizationRequest) *model.OrganizationResponse); ok {
		r0 = returnFunc(ctx, id, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.OrganizationResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *model.UpdateOrganizationRequest) error); ok {
		r1 = returnFunc(ctx, id, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrganizationUseCase_UpdateOrganization_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOrganization'
type MockOrganizationUseCase_UpdateOrganization_Call struct {
	*mock.Call
}

// UpdateOrganization is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - request *model.UpdateOrganizationRequest
func (_e *MockOrganizationUseCase_Expecter) UpdateOrganization(ctx interface{}, id interface{}, request interface{}) *MockOrganizationUseCase_UpdateOrganization_Call {
	return &MockOrganizationUseCase_UpdateOrganization_Call{Call: _e.mock.On("UpdateOrganization", ctx, id, request)}
}

func (_c *MockOrganizationUseCase_UpdateOrganization_Call) Run(run func(ctx context.Context, id string, request *model.UpdateOrganizationRequest)) *MockOrganizationUseCase_UpdateOrganization_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *model.UpdateOrganizationRequest
		if args[2] != nil {
			arg2 = args[2].(*model.UpdateOrganizationRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockOrganizationUseCase_UpdateOrganization_Call) Return(organizationResponse *model.OrganizationResponse, err error) *MockOrganizationUseCase_UpdateOrganization_Call {
	_c.Call.Return(organizationResponse, err)
	return _c
}

func (_c *MockOrganizationUseCase_UpdateOrganization_Call) RunAndReturn(run func(ctx context.Context, id string, request *model.UpdateOrganizationRequest) (*model.OrganizationResponse, error)) *MockOrganizationUseCase_UpdateOrganization_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOrganizationMemberUseCase creates a new instance of MockOrganizationMemberUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrganizationMemberUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrganizationMemberUseCase {
	m := &MockOrganizationMemberUseCase{}
	m.Mock.Test(t)

	t.Cleanup(func() { m.AssertExpectations(t) })

	return m
}

// MockOrganizationMemberUseCase is an autogenerated mock type for the OrganizationMemberUseCase type
type MockOrganizationMemberUseCase struct {
	mock.Mock
}

type MockOrganizationMemberUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrganizationMemberUseCase) EXPECT() *MockOrganizationMemberUseCase_Expecter {
	return &MockOrganizationMemberUseCase_Expecter{mock: &_m.Mock}
}

// AcceptInvitation provides a mock function for the type MockOrganizationMemberUseCase
func (_mock *MockOrganizationMemberUseCase) AcceptInvitation(ctx context.Context, request *model.AcceptInvitationRequest) error {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for AcceptInvitation")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.AcceptInvitationRequest) error); ok {
		r0 = returnFunc(ctx, request)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrganizationMemberUseCase_AcceptInvitation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AcceptInvitation'
type MockOrganizationMemberUseCase_AcceptInvitation_Call struct {
	*mock.Call
}

// AcceptInvitation is a helper method to define mock.On call
//   - ctx context.Context
//   - request *model.AcceptInvitationRequest
func (_e *MockOrganizationMemberUseCase_Expecter) AcceptInvitation(ctx interface{}, request interface{}) *MockOrganizationMemberUseCase_AcceptInvitation_Call {
	return &MockOrganizationMemberUseCase_AcceptInvitation_Call{Call: _e.mock.On("AcceptInvitation", ctx, request)}
}

func (_c *MockOrganizationMemberUseCase_AcceptInvitation_Call) Run(run func(ctx context.Context, request *model.AcceptInvitationRequest)) *MockOrganizationMemberUseCase_AcceptInvitation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.AcceptInvitationRequest
		if args[1] != nil {
			arg1 = args[1].(*model.AcceptInvitationRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrganizationMemberUseCase_AcceptInvitation_Call) Return(err error) *MockOrganizationMemberUseCase_AcceptInvitation_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrganizationMemberUseCase_AcceptInvitation_Call) RunAndReturn(run func(ctx context.Context, request *model.AcceptInvitationRequest) error) *MockOrganizationMemberUseCase_AcceptInvitation_Call {
	_c.Call.Return(run)
	return _c
}

// GetMembers provides a mock function for the type MockOrganizationMemberUseCase
func (_mock *MockOrganizationMemberUseCase) GetMembers(ctx context.Context, orgID string) ([]model.MemberResponse, error) {
	ret := _mock.Called(ctx, orgID)

	if len(ret) == 0 {
		panic("no return value specified for GetMembers")
	}

	var r0 []model.MemberResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]model.MemberResponse, error)); ok {
		return returnFunc(ctx, orgID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []model.MemberResponse); ok {
		r0 = returnFunc(ctx, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.MemberResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, orgID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrganizationMemberUseCase_GetMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMembers'
type MockOrganizationMemberUseCase_GetMembers_Call struct {
	*mock.Call
}

// GetMembers is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID string
func (_e *MockOrganizationMemberUseCase_Expecter) GetMembers(ctx interface{}, orgID interface{}) *MockOrganizationMemberUseCase_GetMembers_Call {
	return &MockOrganizationMemberUseCase_GetMembers_Call{Call: _e.mock.On("GetMembers", ctx, orgID)}
}

func (_c *MockOrganizationMemberUseCase_GetMembers_Call) Run(run func(ctx context.Context, orgID string)) *MockOrganizationMemberUseCase_GetMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrganizationMemberUseCase_GetMembers_Call) Return(memberResponses []model.MemberResponse, err error) *MockOrganizationMemberUseCase_GetMembers_Call {
	_c.Call.Return(memberResponses, err)
	return _c
}

func (_c *MockOrganizationMemberUseCase_GetMembers_Call) RunAndReturn(run func(ctx context.Context, orgID string) ([]model.MemberResponse, error)) *MockOrganizationMemberUseCase_GetMembers_Call {
	_c.Call.Return(run)
	return _c
}

// GetPresence provides a mock function for the type MockOrganizationMemberUseCase
func (_mock *MockOrganizationMemberUseCase) GetPresence(ctx context.Context, orgID string) ([]interface{}, error) {
	ret := _mock.Called(ctx, orgID)

	if len(ret) == 0 {
		panic("no return value specified for GetPresence")
	}

	var r0 []interface{}
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]interface{}, error)); ok {
		return returnFunc(ctx, orgID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []interface{}); ok {
		r0 = returnFunc(ctx, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]interface{})
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, orgID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrganizationMemberUseCase_GetPresence_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPresence'
type MockOrganizationMemberUseCase_GetPresence_Call struct {
	*mock.Call
}

// GetPresence is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID string
func (_e *MockOrganizationMemberUseCase_Expecter) GetPresence(ctx interface{}, orgID interface{}) *MockOrganizationMemberUseCase_GetPresence_Call {
	return &MockOrganizationMemberUseCase_GetPresence_Call{Call: _e.mock.On("GetPresence", ctx, orgID)}
}

func (_c *MockOrganizationMemberUseCase_GetPresence_Call) Run(run func(ctx context.Context, orgID string)) *MockOrganizationMemberUseCase_GetPresence_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrganizationMemberUseCase_GetPresence_Call) Return(ifaceVals []interface{}, err error) *MockOrganizationMemberUseCase_GetPresence_Call {
	_c.Call.Return(ifaceVals, err)
	return _c
}

func (_c *MockOrganizationMemberUseCase_GetPresence_Call) RunAndReturn(run func(ctx context.Context, orgID string) ([]interface{}, error)) *MockOrganizationMemberUseCase_GetPresence_Call {
	_c.Call.Return(run)
	return _c
}

// InviteMember provides a mock function for the type MockOrganizationMemberUseCase
func (_mock *MockOrganizationMemberUseCase) InviteMember(ctx context.Context, orgID string, request *model.InviteMemberRequest) (*model.MemberResponse, error) {
	ret := _mock.Called(ctx, orgID, request)

	if len(ret) == 0 {
		panic("no return value specified for InviteMember")
	}

	var r0 *model.MemberResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *model.InviteMemberRequest) (*model.MemberResponse, error)); ok {
		return returnFunc(ctx, orgID, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *model.InviteMemberRequest) *model.MemberResponse); ok {
		r0 = returnFunc(ctx, orgID, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.MemberResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *model.InviteMemberRequest) error); ok {
		r1 = returnFunc(ctx, orgID, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrganizationMemberUseCase_InviteMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InviteMember'
type MockOrganizationMemberUseCase_InviteMember_Call struct {
	*mock.Call
}

// InviteMember is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID string
//   - request *model.InviteMemberRequest
func (_e *MockOrganizationMemberUseCase_Expecter) InviteMember(ctx interface{}, orgID interface{}, request interface{}) *MockOrganizationMemberUseCase_InviteMember_Call {
	return &MockOrganizationMemberUseCase_InviteMember_Call{Call: _e.mock.On("InviteMember", ctx, orgID, request)}
}

func (_c *MockOrganizationMemberUseCase_InviteMember_Call) Run(run func(ctx context.Context, orgID string, request *model.InviteMemberRequest)) *MockOrganizationMemberUseCase_InviteMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *model.InviteMemberRequest
		if args[2] != nil {
			arg2 = args[2].(*model.InviteMemberRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockOrganizationMemberUseCase_InviteMember_Call) Return(memberResponse *model.MemberResponse, err error) *MockOrganizationMemberUseCase_InviteMember_Call {
	_c.Call.Return(memberResponse, err)
	return _c
}

func (_c *MockOrganizationMemberUseCase_InviteMember_Call) RunAndReturn(run func(ctx context.Context, orgID string, request *model.InviteMemberRequest) (*model.MemberResponse, error)) *MockOrganizationMemberUseCase_InviteMember_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveMember provides a mock function for the type MockOrganizationMemberUseCase
func (_mock *MockOrganizationMemberUseCase) RemoveMember(ctx context.Context, orgID string, userID string) error {
	ret := _mock.Called(ctx, orgID, userID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveMember")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, orgID, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrganizationMemberUseCase_RemoveMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveMember'
type MockOrganizationMemberUseCase_RemoveMember_Call struct {
	*mock.Call
}

// RemoveMember is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID string
//   - userID string
func (_e *MockOrganizationMemberUseCase_Expecter) RemoveMember(ctx interface{}, orgID interface{}, userID interface{}) *MockOrganizationMemberUseCase_RemoveMember_Call {
	return &MockOrganizationMemberUseCase_RemoveMember_Call{Call: _e.mock.On("RemoveMember", ctx, orgID, userID)}
}

func (_c *MockOrganizationMemberUseCase_RemoveMember_Call) Run(run func(ctx context.Context, orgID string, userID string)) *MockOrganizationMemberUseCase_RemoveMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockOrganizationMemberUseCase_RemoveMember_Call) Return(err error) *MockOrganizationMemberUseCase_RemoveMember_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrganizationMemberUseCase_RemoveMember_Call) RunAndReturn(run func(ctx context.Context, orgID string, userID string) error) *MockOrganizationMemberUseCase_RemoveMember_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateMember provides a mock function for the type MockOrganizationMemberUseCase
func (_mock *MockOrganizationMemberUseCase) UpdateMember(ctx context.Context, orgID string, userID string, request *model.UpdateMemberRequest) (*model.MemberResponse, error) {
	ret := _mock.Called(ctx, orgID, userID, request)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMember")
	}

	var r0 *model.MemberResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *model.UpdateMemberRequest) (*model.MemberResponse, error)); ok {
		return returnFunc(ctx, orgID, userID, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *model.UpdateMemberRequest) *model.MemberResponse); ok {
		r0 = returnFunc(ctx, orgID, userID, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.MemberResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, *model.UpdateMemberRequest) error); ok {
		r1 = returnFunc(ctx, orgID, userID, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrganizationMemberUseCase_UpdateMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateMember'
type MockOrganizationMemberUseCase_UpdateMember_Call struct {
	*mock.Call
}

// UpdateMember is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID string
//   - userID string
//   - request *model.UpdateMemberRequest
func (_e *MockOrganizationMemberUseCase_Expecter) UpdateMember(ctx interface{}, orgID interface{}, userID interface{}, request interface{}) *MockOrganizationMemberUseCase_UpdateMember_Call {
	return &MockOrganizationMemberUseCase_UpdateMember_Call{Call: _e.mock.On("UpdateMember", ctx, orgID, userID, request)}
}

func (_c *MockOrganizationMemberUseCase_UpdateMember_Call) Run(run func(ctx context.Context, orgID string, userID string, request *model.UpdateMemberRequest)) *MockOrganizationMemberUseCase_UpdateMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *model.UpdateMemberRequest
		if args[3] != nil {
			arg3 = args[3].(*model.UpdateMemberRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockOrganizationMemberUseCase_UpdateMember_Call) Return(memberResponse *model.MemberResponse, err error) *MockOrganizationMemberUseCase_UpdateMember_Call {
	_c.Call.Return(memberResponse, err)
	return _c
}

func (_c *MockOrganizationMemberUseCase_UpdateMember_Call) RunAndReturn(run func(ctx context.Context, orgID string, userID string, request *model.UpdateMemberRequest) (*model.MemberResponse, error)) *MockOrganizationMemberUseCase_UpdateMember_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIOrganizationReader creates a new instance of MockIOrganizationReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIOrganizationReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIOrganizationReader {
	m := &MockIOrganizationReader{}
	m.Mock.Test(t)

	t.Cleanup(func() { m.AssertExpectations(t) })

	return m
}

// MockIOrganizationReader is an autogenerated mock type for the IOrganizationReader type
type MockIOrganizationReader struct {
	mock.Mock
}

type MockIOrganizationReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIOrganizationReader) EXPECT() *MockIOrganizationReader_Expecter {
	return &MockIOrganizationReader_Expecter{mock: &_m.Mock}
}

// GetMemberRole provides a mock function for the type MockIOrganizationReader
func (_mock *MockIOrganizationReader) GetMemberRole(ctx context.Context, orgID string, userID string) (string, error) {
	ret := _mock.Called(ctx, orgID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetMemberRole")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return returnFunc(ctx, orgID, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = returnFunc(ctx, orgID, userID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, orgID, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIOrganizationReader_GetMemberRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMemberRole'
type MockIOrganizationReader_GetMemberRole_Call struct {
	*mock.Call
}

// GetMemberRole is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID string
//   - userID string
func (_e *MockIOrganizationReader_Expecter) GetMemberRole(ctx interface{}, orgID interface{}, userID interface{}) *MockIOrganizationReader_GetMemberRole_Call {
	return &MockIOrganizationReader_GetMemberRole_Call{Call: _e.mock.On("GetMemberRole", ctx, orgID, userID)}
}

func (_c *MockIOrganizationReader_GetMemberRole_Call) Run(run func(ctx context.Context, orgID string, userID string)) *MockIOrganizationReader_GetMemberRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIOrganizationReader_GetMemberRole_Call) Return(s string, err error) *MockIOrganizationReader_GetMemberRole_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockIOrganizationReader_GetMemberRole_Call) RunAndReturn(run func(ctx context.Context, orgID string, userID string) (string, error)) *MockIOrganizationReader_GetMemberRole_Call {
	_c.Call.Return(run)
	return _c
}

// InvalidateMembershipCache provides a mock function for the type MockIOrganizationReader
func (_mock *MockIOrganizationReader) InvalidateMembershipCache(ctx context.Context, orgID string, userID string) error {
	ret := _mock.Called(ctx, orgID, userID)

	if len(ret) == 0 {
		panic("no return value specified for InvalidateMembershipCache")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, orgID, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIOrganizationReader_InvalidateMembershipCache_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InvalidateMembershipCache'
type MockIOrganizationReader_InvalidateMembershipCache_Call struct {
	*mock.Call
}

// InvalidateMembershipCache is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID string
//   - userID string
func (_e *MockIOrganizationReader_Expecter) InvalidateMembershipCache(ctx interface{}, orgID interface{}, userID interface{}) *MockIOrganizationReader_InvalidateMembershipCache_Call {
	return &MockIOrganizationReader_InvalidateMembershipCache_Call{Call: _e.mock.On("InvalidateMembershipCache", ctx, orgID, userID)}
}

func (_c *MockIOrganizationReader_InvalidateMembershipCache_Call) Run(run func(ctx context.Context, orgID string, userID string)) *MockIOrganizationReader_InvalidateMembershipCache_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIOrganizationReader_InvalidateMembershipCache_Call) Return(err error) *MockIOrganizationReader_InvalidateMembershipCache_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIOrganizationReader_InvalidateMembershipCache_Call) RunAndReturn(run func(ctx context.Context, orgID string, userID string) error) *MockIOrganizationReader_InvalidateMembershipCache_Call {
	_c.Call.Return(run)
	return _c
}

// InvalidateOrganizationCache provides a mock function for the type MockIOrganizationReader
func (_mock *MockIOrganizationReader) InvalidateOrganizationCache(ctx context.Context, orgID string) error {
	ret := _mock.Called(ctx, orgID)

	if len(ret) == 0 {
		panic("no return value specified for InvalidateOrganizationCache")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, orgID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIOrganizationReader_InvalidateOrganizationCache_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InvalidateOrganizationCache'
type MockIOrganizationReader_InvalidateOrganizationCache_Call struct {
	*mock.Call
}

// InvalidateOrganizationCache is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID string
func (_e *MockIOrganizationReader_Expecter) InvalidateOrganizationCache(ctx interface{}, orgID interface{}) *MockIOrganizationReader_InvalidateOrganizationCache_Call {
	return &MockIOrganizationReader_InvalidateOrganizationCache_Call{Call: _e.mock.On("InvalidateOrganizationCache", ctx, orgID)}
}

func (_c *MockIOrganizationReader_InvalidateOrganizationCache_Call) Run(run func(ctx context.Context, orgID string)) *MockIOrganizationReader_InvalidateOrganizationCache_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIOrganizationReader_InvalidateOrganizationCache_Call) Return(err error) *MockIOrganizationReader_InvalidateOrganizationCache_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIOrganizationReader_InvalidateOrganizationCache_Call) RunAndReturn(run func(ctx context.Context, orgID string) error) *MockIOrganizationReader_InvalidateOrganizationCache_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateMembership provides a mock function for the type MockIOrganizationReader
func (_mock *MockIOrganizationReader) ValidateMembership(ctx context.Context, orgID string, userID string) (bool, error) {
	ret := _mock.Called(ctx, orgID, userID)

	if len(ret) == 0 {
		panic("no return value specified for ValidateMembership")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return returnFunc(ctx, orgID, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = returnFunc(ctx, orgID, userID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, orgID, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIOrganizationReader_ValidateMembership_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateMembership'
type MockIOrganizationReader_ValidateMembership_Call struct {
	*mock.Call
}

// ValidateMembership is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID string
//   - userID string
func (_e *MockIOrganizationReader_Expecter) ValidateMembership(ctx interface{}, orgID interface{}, userID interface{}) *MockIOrganizationReader_ValidateMembership_Call {
	return &MockIOrganizationReader_ValidateMembership_Call{Call: _e.mock.On("ValidateMembership", ctx, orgID, userID)}
}

func (_c *MockIOrganizationReader_ValidateMembership_Call) Run(run func(ctx context.Context, orgID string, userID string)) *MockIOrganizationReader_ValidateMembership_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIOrganizationReader_ValidateMembership_Call) Return(b bool, err error) *MockIOrganizationReader_ValidateMembership_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockIOrganizationReader_ValidateMembership_Call) RunAndReturn(run func(ctx context.Context, orgID string, userID string) (bool, error)) *MockIOrganizationReader_ValidateMembership_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPresenceReader creates a new instance of MockPresenceReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPresenceReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPresenceReader {
	m := &MockPresenceReader{}
	m.Mock.Test(t)

	t.Cleanup(func() { m.AssertExpectations(t) })

	return m
}

// MockPresenceReader is an autogenerated mock type for the PresenceReader type
type MockPresenceReader struct {
	mock.Mock
}

type MockPresenceReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPresenceReader) EXPECT() *MockPresenceReader_Expecter {
	return &MockPresenceReader_Expecter{mock: &_m.Mock}
}

// GetOnlineUsers provides a mock function for the type MockPresenceReader
func (_mock *MockPresenceReader) GetOnlineUsers(ctx context.Context, orgID string) ([]ws.PresenceUser, error) {
	ret := _mock.Called(ctx, orgID)

	if len(ret) == 0 {
		panic("no return value specified for GetOnlineUsers")
	}

	var r0 []ws.PresenceUser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]ws.PresenceUser, error)); ok {
		return returnFunc(ctx, orgID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []ws.PresenceUser); ok {
		r0 = returnFunc(ctx, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ws.PresenceUser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, orgID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPresenceReader_GetOnlineUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOnlineUsers'
type MockPresenceReader_GetOnlineUsers_Call struct {
	*mock.Call
}

// GetOnlineUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID string
func (_e *MockPresenceReader_Expecter) GetOnlineUsers(ctx interface{}, orgID interface{}) *MockPresenceReader_GetOnlineUsers_Call {
	return &MockPresenceReader_GetOnlineUsers_Call{Call: _e.mock.On("GetOnlineUsers", ctx, orgID)}
}

func (_c *MockPresenceReader_GetOnlineUsers_Call) Run(run func(ctx context.Context, orgID string)) *MockPresenceReader_GetOnlineUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPresenceReader_GetOnlineUsers_Call) Return(presenceUsers []ws.PresenceUser, err error) *MockPresenceReader_GetOnlineUsers_Call {
	_c.Call.Return(presenceUsers, err)
	return _c
}

func (_c *MockPresenceReader_GetOnlineUsers_Call) RunAndReturn(run func(ctx context.Context, orgID string) ([]ws.PresenceUser, error)) *MockPresenceReader_GetOnlineUsers_Call {
	_c.Call.Return(run)
	return _c
}
