// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/Roisfaozi/queue-base/internal/modules/audit/model"
	mock "github.com/stretchr/testify/mock"
)

// MockAuditLogger is an autogenerated mock type for the AuditLogger type
type MockAuditLogger struct {
	mock.Mock
}

type MockAuditLogger_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuditLogger) EXPECT() *MockAuditLogger_Expecter {
	return &MockAuditLogger_Expecter{mock: &_m.Mock}
}

// LogActivity provides a mock function with given fields: ctx, req
func (_m *MockAuditLogger) LogActivity(ctx context.Context, req model.CreateAuditLogRequest) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for LogActivity")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.CreateAuditLogRequest) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuditLogger_LogActivity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LogActivity'
type MockAuditLogger_LogActivity_Call struct {
	*mock.Call
}

// LogActivity is a helper method to define mock.On call
//   - ctx context.Context
//   - req model.CreateAuditLogRequest
func (_e *MockAuditLogger_Expecter) LogActivity(ctx interface{}, req interface{}) *MockAuditLogger_LogActivity_Call {
	return &MockAuditLogger_LogActivity_Call{Call: _e.mock.On("LogActivity", ctx, req)}
}

func (_c *MockAuditLogger_LogActivity_Call) Run(run func(ctx context.Context, req model.CreateAuditLogRequest)) *MockAuditLogger_LogActivity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.CreateAuditLogRequest))
	})
	return _c
}

func (_c *MockAuditLogger_LogActivity_Call) Return(_a0 error) *MockAuditLogger_LogActivity_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuditLogger_LogActivity_Call) RunAndReturn(run func(context.Context, model.CreateAuditLogRequest) error) *MockAuditLogger_LogActivity_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuditLogger creates a new instance of MockAuditLogger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuditLogger(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuditLogger {
	mock := &MockAuditLogger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
