// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Roisfaozi/go-clean-boilerplate/internal/modules/organization/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockOrganizationRepository creates a new instance of MockOrganizationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrganizationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrganizationRepository {
	m := &MockOrganizationRepository{}
	m.Mock.Test(t)

	t.Cleanup(func() { m.AssertExpectations(t) })

	return m
}

// MockOrganizationRepository is an autogenerated mock type for the OrganizationRepository type
type MockOrganizationRepository struct {
	mock.Mock
}

type MockOrganizationRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrganizationRepository) EXPECT() *MockOrganizationRepository_Expecter {
	return &MockOrganizationRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockOrganizationRepository
func (_mock *MockOrganizationRepository) Create(ctx context.Context, org *entity.Organization, ownerRoleID string) error {
	ret := _mock.Called(ctx, org, ownerRoleID)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Organization, string) error); ok {
		r0 = returnFunc(ctx, org, ownerRoleID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrganizationRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockOrganizationRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - org *entity.Organization
//   - ownerRoleID string
func (_e *MockOrganizationRepository_Expecter) Create(ctx interface{}, org interface{}, ownerRoleID interface{}) *MockOrganizationRepository_Create_Call {
	return &MockOrganizationRepository_Create_Call{Call: _e.mock.On("Create", ctx, org, ownerRoleID)}
}

func (_c *MockOrganizationRepository_Create_Call) Run(run func(ctx context.Context, org *entity.Organization, ownerRoleID string)) *MockOrganizationRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Organization
		if args[1] != nil {
			arg1 = args[1].(*entity.Organization)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockOrganizationRepository_Create_Call) Return(err error) *MockOrganizationRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrganizationRepository_Create_Call) RunAndReturn(run func(ctx context.Context, org *entity.Organization, ownerRoleID string) error) *MockOrganizationRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockOrganizationRepository
func (_mock *MockOrganizationRepository) Delete(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrganizationRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockOrganizationRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockOrganizationRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockOrganizationRepository_Delete_Call {
	return &MockOrganizationRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockOrganizationRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *MockOrganizationRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrganizationRepository_Delete_Call) Return(err error) *MockOrganizationRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrganizationRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockOrganizationRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Restore provides a mock function for the type MockOrganizationRepository
func (_mock *MockOrganizationRepository) Restore(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Restore")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrganizationRepository_Restore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Restore'
type MockOrganizationRepository_Restore_Call struct {
	*mock.Call
}

// Restore is a helper method to define mock.On call
func (_e *MockOrganizationRepository_Expecter) Restore(ctx interface{}, id interface{}) *MockOrganizationRepository_Restore_Call {
	return &MockOrganizationRepository_Restore_Call{Call: _e.mock.On("Restore", ctx, id)}
}

func (_c *MockOrganizationRepository_Restore_Call) Run(run func(ctx context.Context, id string)) *MockOrganizationRepository_Restore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(arg0, arg1)
	})
	return _c
}

func (_c *MockOrganizationRepository_Restore_Call) Return(err error) *MockOrganizationRepository_Restore_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrganizationRepository_Restore_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockOrganizationRepository_Restore_Call {
	_c.Call.Return(run)
	return _c
}

// HardDelete provides a mock function for the type MockOrganizationRepository
func (_mock *MockOrganizationRepository) HardDelete(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for HardDelete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

type MockOrganizationRepository_HardDelete_Call struct {
	*mock.Call
}

func (_e *MockOrganizationRepository_Expecter) HardDelete(ctx interface{}, id interface{}) *MockOrganizationRepository_HardDelete_Call {
	return &MockOrganizationRepository_HardDelete_Call{Call: _e.mock.On("HardDelete", ctx, id)}
}

func (_c *MockOrganizationRepository_HardDelete_Call) Run(run func(ctx context.Context, id string)) *MockOrganizationRepository_HardDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(arg0, arg1)
	})
	return _c
}

func (_c *MockOrganizationRepository_HardDelete_Call) Return(err error) *MockOrganizationRepository_HardDelete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrganizationRepository_HardDelete_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockOrganizationRepository_HardDelete_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockOrganizationRepository
func (_mock *MockOrganizationRepository) FindByID(ctx context.Context, id string) (*entity.Organization, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entity.Organization
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.Organization, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.Organization); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Organization)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrganizationRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockOrganizationRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockOrganizationRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockOrganizationRepository_FindByID_Call {
	return &MockOrganizationRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockOrganizationRepository_FindByID_Call) Run(run func(ctx context.Context, id string)) *MockOrganizationRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrganizationRepository_FindByID_Call) Return(organization *entity.Organization, err error) *MockOrganizationRepository_FindByID_Call {
	_c.Call.Return(organization, err)
	return _c
}

func (_c *MockOrganizationRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*entity.Organization, error)) *MockOrganizationRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindBySlug provides a mock function for the type MockOrganizationRepository
func (_mock *MockOrganizationRepository) FindBySlug(ctx context.Context, slug string) (*entity.Organization, error) {
	ret := _mock.Called(ctx, slug)

	if len(ret) == 0 {
		panic("no return value specified for FindBySlug")
	}

	var r0 *entity.Organization
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.Organization, error)); ok {
		return returnFunc(ctx, slug)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.Organization); ok {
		r0 = returnFunc(ctx, slug)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Organization)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, slug)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrganizationRepository_FindBySlug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindBySlug'
type MockOrganizationRepository_FindBySlug_Call struct {
	*mock.Call
}

// FindBySlug is a helper method to define mock.On call
//   - ctx context.Context
//   - slug string
func (_e *MockOrganizationRepository_Expecter) FindBySlug(ctx interface{}, slug interface{}) *MockOrganizationRepository_FindBySlug_Call {
	return &MockOrganizationRepository_FindBySlug_Call{Call: _e.mock.On("FindBySlug", ctx, slug)}
}

func (_c *MockOrganizationRepository_FindBySlug_Call) Run(run func(ctx context.Context, slug string)) *MockOrganizationRepository_FindBySlug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrganizationRepository_FindBySlug_Call) Return(organization *entity.Organization, err error) *MockOrganizationRepository_FindBySlug_Call {
	_c.Call.Return(organization, err)
	return _c
}

func (_c *MockOrganizationRepository_FindBySlug_Call) RunAndReturn(run func(ctx context.Context, slug string) (*entity.Organization, error)) *MockOrganizationRepository_FindBySlug_Call {
	_c.Call.Return(run)
	return _c
}

// FindUserOrganizations provides a mock function for the type MockOrganizationRepository
func (_mock *MockOrganizationRepository) FindUserOrganizations(ctx context.Context, userID string) ([]*entity.Organization, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindUserOrganizations")
	}

	var r0 []*entity.Organization
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*entity.Organization, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*entity.Organization); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Organization)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrganizationRepository_FindUserOrganizations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindUserOrganizations'
type MockOrganizationRepository_FindUserOrganizations_Call struct {
	*mock.Call
}

// FindUserOrganizations is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockOrganizationRepository_Expecter) FindUserOrganizations(ctx interface{}, userID interface{}) *MockOrganizationRepository_FindUserOrganizations_Call {
	return &MockOrganizationRepository_FindUserOrganizations_Call{Call: _e.mock.On("FindUserOrganizations", ctx, userID)}
}

func (_c *MockOrganizationRepository_FindUserOrganizations_Call) Run(run func(ctx context.Context, userID string)) *MockOrganizationRepository_FindUserOrganizations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrganizationRepository_FindUserOrganizations_Call) Return(organizations []*entity.Organization, err error) *MockOrganizationRepository_FindUserOrganizations_Call {
	_c.Call.Return(organizations, err)
	return _c
}

func (_c *MockOrganizationRepository_FindUserOrganizations_Call) RunAndReturn(run func(ctx context.Context, userID string) ([]*entity.Organization, error)) *MockOrganizationRepository_FindUserOrganizations_Call {
	_c.Call.Return(run)
	return _c
}

// SlugExists provides a mock function for the type MockOrganizationRepository
func (_mock *MockOrganizationRepository) SlugExists(ctx context.Context, slug string) (bool, error) {
	ret := _mock.Called(ctx, slug)

	if len(ret) == 0 {
		panic("no return value specified for SlugExists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, slug)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, slug)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, slug)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrganizationRepository_SlugExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SlugExists'
type MockOrganizationRepository_SlugExists_Call struct {
	*mock.Call
}

// SlugExists is a helper method to define mock.On call
//   - ctx context.Context
//   - slug string
func (_e *MockOrganizationRepository_Expecter) SlugExists(ctx interface{}, slug interface{}) *MockOrganizationRepository_SlugExists_Call {
	return &MockOrganizationRepository_SlugExists_Call{Call: _e.mock.On("SlugExists", ctx, slug)}
}

func (_c *MockOrganizationRepository_SlugExists_Call) Run(run func(ctx context.Context, slug string)) *MockOrganizationRepository_SlugExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrganizationRepository_SlugExists_Call) Return(b bool, err error) *MockOrganizationRepository_SlugExists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockOrganizationRepository_SlugExists_Call) RunAndReturn(run func(ctx context.Context, slug string) (bool, error)) *MockOrganizationRepository_SlugExists_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockOrganizationRepository
func (_mock *MockOrganizationRepository) Update(ctx context.Context, org *entity.Organization) error {
	ret := _mock.Called(ctx, org)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Organization) error); ok {
		r0 = returnFunc(ctx, org)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrganizationRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockOrganizationRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - org *entity.Organization
func (_e *MockOrganizationRepository_Expecter) Update(ctx interface{}, org interface{}) *MockOrganizationRepository_Update_Call {
	return &MockOrganizationRepository_Update_Call{Call: _e.mock.On("Update", ctx, org)}
}

func (_c *MockOrganizationRepository_Update_Call) Run(run func(ctx context.Context, org *entity.Organization)) *MockOrganizationRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Organization
		if args[1] != nil {
			arg1 = args[1].(*entity.Organization)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrganizationRepository_Update_Call) Return(err error) *MockOrganizationRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrganizationRepository_Update_Call) RunAndReturn(run func(ctx context.Context, org *entity.Organization) error) *MockOrganizationRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOrganizationMemberRepository creates a new instance of MockOrganizationMemberRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrganizationMemberRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrganizationMemberRepository {
	m := &MockOrganizationMemberRepository{}
	m.Mock.Test(t)

	t.Cleanup(func() { m.AssertExpectations(t) })

	return m
}

// MockOrganizationMemberRepository is an autogenerated mock type for the OrganizationMemberRepository type
type MockOrganizationMemberRepository struct {
	mock.Mock
}

type MockOrganizationMemberRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrganizationMemberRepository) EXPECT() *MockOrganizationMemberRepository_Expecter {
	return &MockOrganizationMemberRepository_Expecter{mock: &_m.Mock}
}

// AddMember provides a mock function for the type MockOrganizationMemberRepository
func (_mock *MockOrganizationMemberRepository) AddMember(ctx context.Context, member *entity.OrganizationMember) error {
	ret := _mock.Called(ctx, member)

	if len(ret) == 0 {
		panic("no return value specified for AddMember")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.OrganizationMember) error); ok {
		r0 = returnFunc(ctx, member)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrganizationMemberRepository_AddMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddMember'
type MockOrganizationMemberRepository_AddMember_Call struct {
	*mock.Call
}

// AddMember is a helper method to define mock.On call
//   - ctx context.Context
//   - member *entity.OrganizationMember
func (_e *MockOrganizationMemberRepository_Expecter) AddMember(ctx interface{}, member interface{}) *MockOrganizationMemberRepository_AddMember_Call {
	return &MockOrganizationMemberRepository_AddMember_Call{Call: _e.mock.On("AddMember", ctx, member)}
}

func (_c *MockOrganizationMemberRepository_AddMember_Call) Run(run func(ctx context.Context, member *entity.OrganizationMember)) *MockOrganizationMemberRepository_AddMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.OrganizationMember
		if args[1] != nil {
			arg1 = args[1].(*entity.OrganizationMember)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrganizationMemberRepository_AddMember_Call) Return(err error) *MockOrganizationMemberRepository_AddMember_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrganizationMemberRepository_AddMember_Call) RunAndReturn(run func(ctx context.Context, member *entity.OrganizationMember) error) *MockOrganizationMemberRepository_AddMember_Call {
	_c.Call.Return(run)
	return _c
}

// CheckMembership provides a mock function for the type MockOrganizationMemberRepository
func (_mock *MockOrganizationMemberRepository) CheckMembership(ctx context.Context, orgID string, userID string) (bool, error) {
	ret := _mock.Called(ctx, orgID, userID)

	if len(ret) == 0 {
		panic("no return value specified for CheckMembership")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return returnFunc(ctx, orgID, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = returnFunc(ctx, orgID, userID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, orgID, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrganizationMemberRepository_CheckMembership_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckMembership'
type MockOrganizationMemberRepository_CheckMembership_Call struct {
	*mock.Call
}

// CheckMembership is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID string
//   - userID string
func (_e *MockOrganizationMemberRepository_Expecter) CheckMembership(ctx interface{}, orgID interface{}, userID interface{}) *MockOrganizationMemberRepository_CheckMembership_Call {
	return &MockOrganizationMemberRepository_CheckMembership_Call{Call: _e.mock.On("CheckMembership", ctx, orgID, userID)}
}

func (_c *MockOrganizationMemberRepository_CheckMembership_Call) Run(run func(ctx context.Context, orgID string, userID string)) *MockOrganizationMemberRepository_CheckMembership_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockOrganizationMemberRepository_CheckMembership_Call) Return(b bool, err error) *MockOrganizationMemberRepository_CheckMembership_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockOrganizationMemberRepository_CheckMembership_Call) RunAndReturn(run func(ctx context.Context, orgID string, userID string) (bool, error)) *MockOrganizationMemberRepository_CheckMembership_Call {
	_c.Call.Return(run)
	return _c
}

// FindMembers provides a mock function for the type MockOrganizationMemberRepository
func (_mock *MockOrganizationMemberRepository) FindMembers(ctx context.Context, orgID string) ([]*entity.OrganizationMember, error) {
	ret := _mock.Called(ctx, orgID)

	if len(ret) == 0 {
		panic("no return value specified for FindMembers")
	}

	var r0 []*entity.OrganizationMember
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*entity.OrganizationMember, error)); ok {
		return returnFunc(ctx, orgID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*entity.OrganizationMember); ok {
		r0 = returnFunc(ctx, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.OrganizationMember)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, orgID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrganizationMemberRepository_FindMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindMembers'
type MockOrganizationMemberRepository_FindMembers_Call struct {
	*mock.Call
}

// FindMembers is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID string
func (_e *MockOrganizationMemberRepository_Expecter) FindMembers(ctx interface{}, orgID interface{}) *MockOrganizationMemberRepository_FindMembers_Call {
	return &MockOrganizationMemberRepository_FindMembers_Call{Call: _e.mock.On("FindMembers", ctx, orgID)}
}

func (_c *MockOrganizationMemberRepository_FindMembers_Call) Run(run func(ctx context.Context, orgID string)) *MockOrganizationMemberRepository_FindMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrganizationMemberRepository_FindMembers_Call) Return(organizationMembers []*entity.OrganizationMember, err error) *MockOrganizationMemberRepository_FindMembers_Call {
	_c.Call.Return(organizationMembers, err)
	return _c
}

func (_c *MockOrganizationMemberRepository_FindMembers_Call) RunAndReturn(run func(ctx context.Context, orgID string) ([]*entity.OrganizationMember, error)) *MockOrganizationMemberRepository_FindMembers_Call {
	_c.Call.Return(run)
	return _c
}

// GetMemberRole provides a mock function for the type MockOrganizationMemberRepository
func (_mock *MockOrganizationMemberRepository) GetMemberRole(ctx context.Context, orgID string, userID string) (string, error) {
	ret := _mock.Called(ctx, orgID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetMemberRole")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return returnFunc(ctx, orgID, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = returnFunc(ctx, orgID, userID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, orgID, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrganizationMemberRepository_GetMemberRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMemberRole'
type MockOrganizationMemberRepository_GetMemberRole_Call struct {
	*mock.Call
}

// GetMemberRole is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID string
//   - userID string
func (_e *MockOrganizationMemberRepository_Expecter) GetMemberRole(ctx interface{}, orgID interface{}, userID interface{}) *MockOrganizationMemberRepository_GetMemberRole_Call {
	return &MockOrganizationMemberRepository_GetMemberRole_Call{Call: _e.mock.On("GetMemberRole", ctx, orgID, userID)}
}

func (_c *MockOrganizationMemberRepository_GetMemberRole_Call) Run(run func(ctx context.Context, orgID string, userID string)) *MockOrganizationMemberRepository_GetMemberRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockOrganizationMemberRepository_GetMemberRole_Call) Return(s string, err error) *MockOrganizationMemberRepository_GetMemberRole_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockOrganizationMemberRepository_GetMemberRole_Call) RunAndReturn(run func(ctx context.Context, orgID string, userID string) (string, error)) *MockOrganizationMemberRepository_GetMemberRole_Call {
	_c.Call.Return(run)
	return _c
}

// GetMemberStatus provides a mock function for the type MockOrganizationMemberRepository
func (_mock *MockOrganizationMemberRepository) GetMemberStatus(ctx context.Context, orgID string, userID string) (string, error) {
	ret := _mock.Called(ctx, orgID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetMemberStatus")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return returnFunc(ctx, orgID, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = returnFunc(ctx, orgID, userID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, orgID, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrganizationMemberRepository_GetMemberStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMemberStatus'
type MockOrganizationMemberRepository_GetMemberStatus_Call struct {
	*mock.Call
}

// GetMemberStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID string
//   - userID string
func (_e *MockOrganizationMemberRepository_Expecter) GetMemberStatus(ctx interface{}, orgID interface{}, userID interface{}) *MockOrganizationMemberRepository_GetMemberStatus_Call {
	return &MockOrganizationMemberRepository_GetMemberStatus_Call{Call: _e.mock.On("GetMemberStatus", ctx, orgID, userID)}
}

func (_c *MockOrganizationMemberRepository_GetMemberStatus_Call) Run(run func(ctx context.Context, orgID string, userID string)) *MockOrganizationMemberRepository_GetMemberStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockOrganizationMemberRepository_GetMemberStatus_Call) Return(s string, err error) *MockOrganizationMemberRepository_GetMemberStatus_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockOrganizationMemberRepository_GetMemberStatus_Call) RunAndReturn(run func(ctx context.Context, orgID string, userID string) (string, error)) *MockOrganizationMemberRepository_GetMemberStatus_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveMember provides a mock function for the type MockOrganizationMemberRepository
func (_mock *MockOrganizationMemberRepository) RemoveMember(ctx context.Context, orgID string, userID string) error {
	ret := _mock.Called(ctx, orgID, userID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveMember")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, orgID, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrganizationMemberRepository_RemoveMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveMember'
type MockOrganizationMemberRepository_RemoveMember_Call struct {
	*mock.Call
}

// RemoveMember is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID string
//   - userID string
func (_e *MockOrganizationMemberRepository_Expecter) RemoveMember(ctx interface{}, orgID interface{}, userID interface{}) *MockOrganizationMemberRepository_RemoveMember_Call {
	return &MockOrganizationMemberRepository_RemoveMember_Call{Call: _e.mock.On("RemoveMember", ctx, orgID, userID)}
}

func (_c *MockOrganizationMemberRepository_RemoveMember_Call) Run(run func(ctx context.Context, orgID string, userID string)) *MockOrganizationMemberRepository_RemoveMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockOrganizationMemberRepository_RemoveMember_Call) Return(err error) *MockOrganizationMemberRepository_RemoveMember_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrganizationMemberRepository_RemoveMember_Call) RunAndReturn(run func(ctx context.Context, orgID string, userID string) error) *MockOrganizationMemberRepository_RemoveMember_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateMemberRole provides a mock function for the type MockOrganizationMemberRepository
func (_mock *MockOrganizationMemberRepository) UpdateMemberRole(ctx context.Context, orgID string, userID string, roleID string) error {
	ret := _mock.Called(ctx, orgID, userID, roleID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMemberRole")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, orgID, userID, roleID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrganizationMemberRepository_UpdateMemberRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateMemberRole'
type MockOrganizationMemberRepository_UpdateMemberRole_Call struct {
	*mock.Call
}

// UpdateMemberRole is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID string
//   - userID string
//   - roleID string
func (_e *MockOrganizationMemberRepository_Expecter) UpdateMemberRole(ctx interface{}, orgID interface{}, userID interface{}, roleID interface{}) *MockOrganizationMemberRepository_UpdateMemberRole_Call {
	return &MockOrganizationMemberRepository_UpdateMemberRole_Call{Call: _e.mock.On("UpdateMemberRole", ctx, orgID, userID, roleID)}
}

func (_c *MockOrganizationMemberRepository_UpdateMemberRole_Call) Run(run func(ctx context.Context, orgID string, userID string, roleID string)) *MockOrganizationMemberRepository_UpdateMemberRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockOrganizationMemberRepository_UpdateMemberRole_Call) Return(err error) *MockOrganizationMemberRepository_UpdateMemberRole_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrganizationMemberRepository_UpdateMemberRole_Call) RunAndReturn(run func(ctx context.Context, orgID string, userID string, roleID string) error) *MockOrganizationMemberRepository_UpdateMemberRole_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateMemberStatus provides a mock function for the type MockOrganizationMemberRepository
func (_mock *MockOrganizationMemberRepository) UpdateMemberStatus(ctx context.Context, orgID string, userID string, status string) error {
	ret := _mock.Called(ctx, orgID, userID, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMemberStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, orgID, userID, status)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrganizationMemberRepository_UpdateMemberStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateMemberStatus'
type MockOrganizationMemberRepository_UpdateMemberStatus_Call struct {
	*mock.Call
}

// UpdateMemberStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID string
//   - userID string
//   - status string
func (_e *MockOrganizationMemberRepository_Expecter) UpdateMemberStatus(ctx interface{}, orgID interface{}, userID interface{}, status interface{}) *MockOrganizationMemberRepository_UpdateMemberStatus_Call {
	return &MockOrganizationMemberRepository_UpdateMemberStatus_Call{Call: _e.mock.On("UpdateMemberStatus", ctx, orgID, userID, status)}
}

func (_c *MockOrganizationMemberRepository_UpdateMemberStatus_Call) Run(run func(ctx context.Context, orgID string, userID string, status string)) *MockOrganizationMemberRepository_UpdateMemberStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockOrganizationMemberRepository_UpdateMemberStatus_Call) Return(err error) *MockOrganizationMemberRepository_UpdateMemberStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrganizationMemberRepository_UpdateMemberStatus_Call) RunAndReturn(run func(ctx context.Context, orgID string, userID string, status string) error) *MockOrganizationMemberRepository_UpdateMemberStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockInvitationRepository creates a new instance of MockInvitationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInvitationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInvitationRepository {
	m := &MockInvitationRepository{}
	m.Mock.Test(t)

	t.Cleanup(func() { m.AssertExpectations(t) })

	return m
}

// MockInvitationRepository is an autogenerated mock type for the InvitationRepository type
type MockInvitationRepository struct {
	mock.Mock
}

type MockInvitationRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInvitationRepository) EXPECT() *MockInvitationRepository_Expecter {
	return &MockInvitationRepository_Expecter{mock: &_m.Mock}
}

// CleanupExpired provides a mock function for the type MockInvitationRepository
func (_mock *MockInvitationRepository) CleanupExpired(ctx context.Context, now int64) error {
	ret := _mock.Called(ctx, now)

	if len(ret) == 0 {
		panic("no return value specified for CleanupExpired")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, now)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInvitationRepository_CleanupExpired_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CleanupExpired'
type MockInvitationRepository_CleanupExpired_Call struct {
	*mock.Call
}

// CleanupExpired is a helper method to define mock.On call
//   - ctx context.Context
//   - now int64
func (_e *MockInvitationRepository_Expecter) CleanupExpired(ctx interface{}, now interface{}) *MockInvitationRepository_CleanupExpired_Call {
	return &MockInvitationRepository_CleanupExpired_Call{Call: _e.mock.On("CleanupExpired", ctx, now)}
}

func (_c *MockInvitationRepository_CleanupExpired_Call) Run(run func(ctx context.Context, now int64)) *MockInvitationRepository_CleanupExpired_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockInvitationRepository_CleanupExpired_Call) Return(err error) *MockInvitationRepository_CleanupExpired_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInvitationRepository_CleanupExpired_Call) RunAndReturn(run func(ctx context.Context, now int64) error) *MockInvitationRepository_CleanupExpired_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockInvitationRepository
func (_mock *MockInvitationRepository) Create(ctx context.Context, invitation *entity.InvitationToken) error {
	ret := _mock.Called(ctx, invitation)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.InvitationToken) error); ok {
		r0 = returnFunc(ctx, invitation)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInvitationRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockInvitationRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - invitation *entity.InvitationToken
func (_e *MockInvitationRepository_Expecter) Create(ctx interface{}, invitation interface{}) *MockInvitationRepository_Create_Call {
	return &MockInvitationRepository_Create_Call{Call: _e.mock.On("Create", ctx, invitation)}
}

func (_c *MockInvitationRepository_Create_Call) Run(run func(ctx context.Context, invitation *entity.InvitationToken)) *MockInvitationRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.InvitationToken
		if args[1] != nil {
			arg1 = args[1].(*entity.InvitationToken)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockInvitationRepository_Create_Call) Return(err error) *MockInvitationRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInvitationRepository_Create_Call) RunAndReturn(run func(ctx context.Context, invitation *entity.InvitationToken) error) *MockInvitationRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockInvitationRepository
func (_mock *MockInvitationRepository) Delete(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInvitationRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockInvitationRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockInvitationRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockInvitationRepository_Delete_Call {
	return &MockInvitationRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockInvitationRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *MockInvitationRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockInvitationRepository_Delete_Call) Return(err error) *MockInvitationRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInvitationRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockInvitationRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByEmailAndOrg provides a mock function for the type MockInvitationRepository
func (_mock *MockInvitationRepository) DeleteByEmailAndOrg(ctx context.Context, email string, orgID string) error {
	ret := _mock.Called(ctx, email, orgID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByEmailAndOrg")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, email, orgID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInvitationRepository_DeleteByEmailAndOrg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByEmailAndOrg'
type MockInvitationRepository_DeleteByEmailAndOrg_Call struct {
	*mock.Call
}

// DeleteByEmailAndOrg is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - orgID string
func (_e *MockInvitationRepository_Expecter) DeleteByEmailAndOrg(ctx interface{}, email interface{}, orgID interface{}) *MockInvitationRepository_DeleteByEmailAndOrg_Call {
	return &MockInvitationRepository_DeleteByEmailAndOrg_Call{Call: _e.mock.On("DeleteByEmailAndOrg", ctx, email, orgID)}
}

func (_c *MockInvitationRepository_DeleteByEmailAndOrg_Call) Run(run func(ctx context.Context, email string, orgID string)) *MockInvitationRepository_DeleteByEmailAndOrg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockInvitationRepository_DeleteByEmailAndOrg_Call) Return(err error) *MockInvitationRepository_DeleteByEmailAndOrg_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInvitationRepository_DeleteByEmailAndOrg_Call) RunAndReturn(run func(ctx context.Context, email string, orgID string) error) *MockInvitationRepository_DeleteByEmailAndOrg_Call {
	_c.Call.Return(run)
	return _c
}

// FindByToken provides a mock function for the type MockInvitationRepository
func (_mock *MockInvitationRepository) FindByToken(ctx context.Context, token string) (*entity.InvitationToken, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for FindByToken")
	}

	var r0 *entity.InvitationToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.InvitationToken, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.InvitationToken); ok {
		r0 = returnFunc(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.InvitationToken)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInvitationRepository_FindByToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByToken'
type MockInvitationRepository_FindByToken_Call struct {
	*mock.Call
}

// FindByToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockInvitationRepository_Expecter) FindByToken(ctx interface{}, token interface{}) *MockInvitationRepository_FindByToken_Call {
	return &MockInvitationRepository_FindByToken_Call{Call: _e.mock.On("FindByToken", ctx, token)}
}

func (_c *MockInvitationRepository_FindByToken_Call) Run(run func(ctx context.Context, token string)) *MockInvitationRepository_FindByToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockInvitationRepository_FindByToken_Call) Return(invitationToken *entity.InvitationToken, err error) *MockInvitationRepository_FindByToken_Call {
	_c.Call.Return(invitationToken, err)
	return _c
}

func (_c *MockInvitationRepository_FindByToken_Call) RunAndReturn(run func(ctx context.Context, token string) (*entity.InvitationToken, error)) *MockInvitationRepository_FindByToken_Call {
	_c.Call.Return(run)
	return _c
}
