// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"io"

	mock "github.com/stretchr/testify/mock"
)

// NewMockProvider creates a new instance of MockProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProvider {
	m := &MockProvider{}
	m.Mock.Test(t)

	t.Cleanup(func() { m.AssertExpectations(t) })

	return m
}

// MockProvider is an autogenerated mock type for the Provider type
type MockProvider struct {
	mock.Mock
}

type MockProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProvider) EXPECT() *MockProvider_Expecter {
	return &MockProvider_Expecter{mock: &_m.Mock}
}

// DeleteFile provides a mock function for the type MockProvider
func (_mock *MockProvider) DeleteFile(ctx context.Context, filename string) error {
	ret := _mock.Called(ctx, filename)

	if len(ret) == 0 {
		panic("no return value specified for DeleteFile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, filename)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProvider_DeleteFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteFile'
type MockProvider_DeleteFile_Call struct {
	*mock.Call
}

// DeleteFile is a helper method to define mock.On call
//   - ctx context.Context
//   - filename string
func (_e *MockProvider_Expecter) DeleteFile(ctx interface{}, filename interface{}) *MockProvider_DeleteFile_Call {
	return &MockProvider_DeleteFile_Call{Call: _e.mock.On("DeleteFile", ctx, filename)}
}

func (_c *MockProvider_DeleteFile_Call) Run(run func(ctx context.Context, filename string)) *MockProvider_DeleteFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProvider_DeleteFile_Call) Return(err error) *MockProvider_DeleteFile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProvider_DeleteFile_Call) RunAndReturn(run func(ctx context.Context, filename string) error) *MockProvider_DeleteFile_Call {
	_c.Call.Return(run)
	return _c
}

// GetFileUrl provides a mock function for the type MockProvider
func (_mock *MockProvider) GetFileUrl(ctx context.Context, filename string) (string, error) {
	ret := _mock.Called(ctx, filename)

	if len(ret) == 0 {
		panic("no return value specified for GetFileUrl")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, filename)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, filename)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, filename)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProvider_GetFileUrl_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFileUrl'
type MockProvider_GetFileUrl_Call struct {
	*mock.Call
}

// GetFileUrl is a helper method to define mock.On call
//   - ctx context.Context
//   - filename string
func (_e *MockProvider_Expecter) GetFileUrl(ctx interface{}, filename interface{}) *MockProvider_GetFileUrl_Call {
	return &MockProvider_GetFileUrl_Call{Call: _e.mock.On("GetFileUrl", ctx, filename)}
}

func (_c *MockProvider_GetFileUrl_Call) Run(run func(ctx context.Context, filename string)) *MockProvider_GetFileUrl_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProvider_GetFileUrl_Call) Return(s string, err error) *MockProvider_GetFileUrl_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockProvider_GetFileUrl_Call) RunAndReturn(run func(ctx context.Context, filename string) (string, error)) *MockProvider_GetFileUrl_Call {
	_c.Call.Return(run)
	return _c
}

// UploadFile provides a mock function for the type MockProvider
func (_mock *MockProvider) UploadFile(ctx context.Context, file io.Reader, filename string, contentType string) (string, error) {
	ret := _mock.Called(ctx, file, filename, contentType)

	if len(ret) == 0 {
		panic("no return value specified for UploadFile")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, io.Reader, string, string) (string, error)); ok {
		return returnFunc(ctx, file, filename, contentType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, io.Reader, string, string) string); ok {
		r0 = returnFunc(ctx, file, filename, contentType)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, io.Reader, string, string) error); ok {
		r1 = returnFunc(ctx, file, filename, contentType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProvider_UploadFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadFile'
type MockProvider_UploadFile_Call struct {
	*mock.Call
}

// UploadFile is a helper method to define mock.On call
//   - ctx context.Context
//   - file io.Reader
//   - filename string
//   - contentType string
func (_e *MockProvider_Expecter) UploadFile(ctx interface{}, file interface{}, filename interface{}, contentType interface{}) *MockProvider_UploadFile_Call {
	return &MockProvider_UploadFile_Call{Call: _e.mock.On("UploadFile", ctx, file, filename, contentType)}
}

func (_c *MockProvider_UploadFile_Call) Run(run func(ctx context.Context, file io.Reader, filename string, contentType string)) *MockProvider_UploadFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 io.Reader
		if args[1] != nil {
			arg1 = args[1].(io.Reader)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockProvider_UploadFile_Call) Return(s string, err error) *MockProvider_UploadFile_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockProvider_UploadFile_Call) RunAndReturn(run func(ctx context.Context, file io.Reader, filename string, contentType string) (string, error)) *MockProvider_UploadFile_Call {
	_c.Call.Return(run)
	return _c
}
