// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Roisfaozi/go-clean-boilerplate/internal/modules/permission/model"
	"github.com/Roisfaozi/go-clean-boilerplate/internal/modules/permission/usecase"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIEnforcer creates a new instance of MockIEnforcer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIEnforcer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIEnforcer {
	m := &MockIEnforcer{}
	m.Mock.Test(t)

	t.Cleanup(func() { m.AssertExpectations(t) })

	return m
}

// MockIEnforcer is an autogenerated mock type for the IEnforcer type
type MockIEnforcer struct {
	mock.Mock
}

type MockIEnforcer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIEnforcer) EXPECT() *MockIEnforcer_Expecter {
	return &MockIEnforcer_Expecter{mock: &_m.Mock}
}

// AddGroupingPolicy provides a mock function for the type MockIEnforcer
func (_mock *MockIEnforcer) AddGroupingPolicy(params ...interface{}) (bool, error) {
	var tmpRet mock.Arguments
	if len(params) > 0 {
		tmpRet = _mock.Called(params)
	} else {
		tmpRet = _mock.Called()
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for AddGroupingPolicy")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(...interface{}) (bool, error)); ok {
		return returnFunc(params...)
	}
	if returnFunc, ok := ret.Get(0).(func(...interface{}) bool); ok {
		r0 = returnFunc(params...)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(...interface{}) error); ok {
		r1 = returnFunc(params...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIEnforcer_AddGroupingPolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddGroupingPolicy'
type MockIEnforcer_AddGroupingPolicy_Call struct {
	*mock.Call
}

// AddGroupingPolicy is a helper method to define mock.On call
//   - params ...interface{}
func (_e *MockIEnforcer_Expecter) AddGroupingPolicy(params ...interface{}) *MockIEnforcer_AddGroupingPolicy_Call {
	return &MockIEnforcer_AddGroupingPolicy_Call{Call: _e.mock.On("AddGroupingPolicy",
		append([]interface{}{}, params...)...)}
}

func (_c *MockIEnforcer_AddGroupingPolicy_Call) Run(run func(params ...interface{})) *MockIEnforcer_AddGroupingPolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []interface{}
		var variadicArgs []interface{}
		if len(args) > 0 {
			variadicArgs = args[0].([]interface{})
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *MockIEnforcer_AddGroupingPolicy_Call) Return(b bool, err error) *MockIEnforcer_AddGroupingPolicy_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockIEnforcer_AddGroupingPolicy_Call) RunAndReturn(run func(params ...interface{}) (bool, error)) *MockIEnforcer_AddGroupingPolicy_Call {
	_c.Call.Return(run)
	return _c
}

// AddPolicy provides a mock function for the type MockIEnforcer
func (_mock *MockIEnforcer) AddPolicy(params ...interface{}) (bool, error) {
	var tmpRet mock.Arguments
	if len(params) > 0 {
		tmpRet = _mock.Called(params)
	} else {
		tmpRet = _mock.Called()
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for AddPolicy")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(...interface{}) (bool, error)); ok {
		return returnFunc(params...)
	}
	if returnFunc, ok := ret.Get(0).(func(...interface{}) bool); ok {
		r0 = returnFunc(params...)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(...interface{}) error); ok {
		r1 = returnFunc(params...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIEnforcer_AddPolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddPolicy'
type MockIEnforcer_AddPolicy_Call struct {
	*mock.Call
}

// AddPolicy is a helper method to define mock.On call
//   - params ...interface{}
func (_e *MockIEnforcer_Expecter) AddPolicy(params ...interface{}) *MockIEnforcer_AddPolicy_Call {
	return &MockIEnforcer_AddPolicy_Call{Call: _e.mock.On("AddPolicy",
		append([]interface{}{}, params...)...)}
}

func (_c *MockIEnforcer_AddPolicy_Call) Run(run func(params ...interface{})) *MockIEnforcer_AddPolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []interface{}
		var variadicArgs []interface{}
		if len(args) > 0 {
			variadicArgs = args[0].([]interface{})
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *MockIEnforcer_AddPolicy_Call) Return(b bool, err error) *MockIEnforcer_AddPolicy_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockIEnforcer_AddPolicy_Call) RunAndReturn(run func(params ...interface{}) (bool, error)) *MockIEnforcer_AddPolicy_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRole provides a mock function for the type MockIEnforcer
func (_mock *MockIEnforcer) DeleteRole(role string) (bool, error) {
	ret := _mock.Called(role)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRole")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return returnFunc(role)
	}
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(role)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(role)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIEnforcer_DeleteRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRole'
type MockIEnforcer_DeleteRole_Call struct {
	*mock.Call
}

// DeleteRole is a helper method to define mock.On call
//   - role string
func (_e *MockIEnforcer_Expecter) DeleteRole(role interface{}) *MockIEnforcer_DeleteRole_Call {
	return &MockIEnforcer_DeleteRole_Call{Call: _e.mock.On("DeleteRole", role)}
}

func (_c *MockIEnforcer_DeleteRole_Call) Run(run func(role string)) *MockIEnforcer_DeleteRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIEnforcer_DeleteRole_Call) Return(b bool, err error) *MockIEnforcer_DeleteRole_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockIEnforcer_DeleteRole_Call) RunAndReturn(run func(role string) (bool, error)) *MockIEnforcer_DeleteRole_Call {
	_c.Call.Return(run)
	return _c
}

// Enforce provides a mock function for the type MockIEnforcer
func (_mock *MockIEnforcer) Enforce(params ...interface{}) (bool, error) {
	var tmpRet mock.Arguments
	if len(params) > 0 {
		tmpRet = _mock.Called(params)
	} else {
		tmpRet = _mock.Called()
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Enforce")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(...interface{}) (bool, error)); ok {
		return returnFunc(params...)
	}
	if returnFunc, ok := ret.Get(0).(func(...interface{}) bool); ok {
		r0 = returnFunc(params...)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(...interface{}) error); ok {
		r1 = returnFunc(params...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIEnforcer_Enforce_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Enforce'
type MockIEnforcer_Enforce_Call struct {
	*mock.Call
}

// Enforce is a helper method to define mock.On call
//   - params ...interface{}
func (_e *MockIEnforcer_Expecter) Enforce(params ...interface{}) *MockIEnforcer_Enforce_Call {
	return &MockIEnforcer_Enforce_Call{Call: _e.mock.On("Enforce",
		append([]interface{}{}, params...)...)}
}

func (_c *MockIEnforcer_Enforce_Call) Run(run func(params ...interface{})) *MockIEnforcer_Enforce_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []interface{}
		var variadicArgs []interface{}
		if len(args) > 0 {
			variadicArgs = args[0].([]interface{})
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *MockIEnforcer_Enforce_Call) Return(b bool, err error) *MockIEnforcer_Enforce_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockIEnforcer_Enforce_Call) RunAndReturn(run func(params ...interface{}) (bool, error)) *MockIEnforcer_Enforce_Call {
	_c.Call.Return(run)
	return _c
}

// GetFilteredPolicy provides a mock function for the type MockIEnforcer
func (_mock *MockIEnforcer) GetFilteredPolicy(fieldIndex int, fieldValues ...string) ([][]string, error) {
	var tmpRet mock.Arguments
	if len(fieldValues) > 0 {
		tmpRet = _mock.Called(fieldIndex, fieldValues)
	} else {
		tmpRet = _mock.Called(fieldIndex)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetFilteredPolicy")
	}

	var r0 [][]string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int, ...string) ([][]string, error)); ok {
		return returnFunc(fieldIndex, fieldValues...)
	}
	if returnFunc, ok := ret.Get(0).(func(int, ...string) [][]string); ok {
		r0 = returnFunc(fieldIndex, fieldValues...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([][]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int, ...string) error); ok {
		r1 = returnFunc(fieldIndex, fieldValues...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIEnforcer_GetFilteredPolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFilteredPolicy'
type MockIEnforcer_GetFilteredPolicy_Call struct {
	*mock.Call
}

// GetFilteredPolicy is a helper method to define mock.On call
//   - fieldIndex int
//   - fieldValues ...string
func (_e *MockIEnforcer_Expecter) GetFilteredPolicy(fieldIndex interface{}, fieldValues ...interface{}) *MockIEnforcer_GetFilteredPolicy_Call {
	return &MockIEnforcer_GetFilteredPolicy_Call{Call: _e.mock.On("GetFilteredPolicy",
		append([]interface{}{fieldIndex}, fieldValues...)...)}
}

func (_c *MockIEnforcer_GetFilteredPolicy_Call) Run(run func(fieldIndex int, fieldValues ...string)) *MockIEnforcer_GetFilteredPolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 []string
		var variadicArgs []string
		if len(args) > 1 {
			variadicArgs = args[1].([]string)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockIEnforcer_GetFilteredPolicy_Call) Return(stringss [][]string, err error) *MockIEnforcer_GetFilteredPolicy_Call {
	_c.Call.Return(stringss, err)
	return _c
}

func (_c *MockIEnforcer_GetFilteredPolicy_Call) RunAndReturn(run func(fieldIndex int, fieldValues ...string) ([][]string, error)) *MockIEnforcer_GetFilteredPolicy_Call {
	_c.Call.Return(run)
	return _c
}

// GetPolicy provides a mock function for the type MockIEnforcer
func (_mock *MockIEnforcer) GetPolicy() ([][]string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPolicy")
	}

	var r0 [][]string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([][]string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() [][]string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([][]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIEnforcer_GetPolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPolicy'
type MockIEnforcer_GetPolicy_Call struct {
	*mock.Call
}

// GetPolicy is a helper method to define mock.On call
func (_e *MockIEnforcer_Expecter) GetPolicy() *MockIEnforcer_GetPolicy_Call {
	return &MockIEnforcer_GetPolicy_Call{Call: _e.mock.On("GetPolicy")}
}

func (_c *MockIEnforcer_GetPolicy_Call) Run(run func()) *MockIEnforcer_GetPolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIEnforcer_GetPolicy_Call) Return(stringss [][]string, err error) *MockIEnforcer_GetPolicy_Call {
	_c.Call.Return(stringss, err)
	return _c
}

func (_c *MockIEnforcer_GetPolicy_Call) RunAndReturn(run func() ([][]string, error)) *MockIEnforcer_GetPolicy_Call {
	_c.Call.Return(run)
	return _c
}

// GetRolesForUser provides a mock function for the type MockIEnforcer
func (_mock *MockIEnforcer) GetRolesForUser(name string, domain ...string) ([]string, error) {
	var tmpRet mock.Arguments
	if len(domain) > 0 {
		tmpRet = _mock.Called(name, domain)
	} else {
		tmpRet = _mock.Called(name)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetRolesForUser")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, ...string) ([]string, error)); ok {
		return returnFunc(name, domain...)
	}
	if returnFunc, ok := ret.Get(0).(func(string, ...string) []string); ok {
		r0 = returnFunc(name, domain...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, ...string) error); ok {
		r1 = returnFunc(name, domain...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIEnforcer_GetRolesForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRolesForUser'
type MockIEnforcer_GetRolesForUser_Call struct {
	*mock.Call
}

// GetRolesForUser is a helper method to define mock.On call
//   - name string
//   - domain ...string
func (_e *MockIEnforcer_Expecter) GetRolesForUser(name interface{}, domain ...interface{}) *MockIEnforcer_GetRolesForUser_Call {
	return &MockIEnforcer_GetRolesForUser_Call{Call: _e.mock.On("GetRolesForUser",
		append([]interface{}{name}, domain...)...)}
}

func (_c *MockIEnforcer_GetRolesForUser_Call) Run(run func(name string, domain ...string)) *MockIEnforcer_GetRolesForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []string
		var variadicArgs []string
		if len(args) > 1 {
			variadicArgs = args[1].([]string)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockIEnforcer_GetRolesForUser_Call) Return(strings []string, err error) *MockIEnforcer_GetRolesForUser_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockIEnforcer_GetRolesForUser_Call) RunAndReturn(run func(name string, domain ...string) ([]string, error)) *MockIEnforcer_GetRolesForUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUsersForRole provides a mock function for the type MockIEnforcer
func (_mock *MockIEnforcer) GetUsersForRole(name string, domain ...string) ([]string, error) {
	var tmpRet mock.Arguments
	if len(domain) > 0 {
		tmpRet = _mock.Called(name, domain)
	} else {
		tmpRet = _mock.Called(name)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetUsersForRole")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, ...string) ([]string, error)); ok {
		return returnFunc(name, domain...)
	}
	if returnFunc, ok := ret.Get(0).(func(string, ...string) []string); ok {
		r0 = returnFunc(name, domain...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, ...string) error); ok {
		r1 = returnFunc(name, domain...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIEnforcer_GetUsersForRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUsersForRole'
type MockIEnforcer_GetUsersForRole_Call struct {
	*mock.Call
}

// GetUsersForRole is a helper method to define mock.On call
//   - name string
//   - domain ...string
func (_e *MockIEnforcer_Expecter) GetUsersForRole(name interface{}, domain ...interface{}) *MockIEnforcer_GetUsersForRole_Call {
	return &MockIEnforcer_GetUsersForRole_Call{Call: _e.mock.On("GetUsersForRole",
		append([]interface{}{name}, domain...)...)}
}

func (_c *MockIEnforcer_GetUsersForRole_Call) Run(run func(name string, domain ...string)) *MockIEnforcer_GetUsersForRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []string
		var variadicArgs []string
		if len(args) > 1 {
			variadicArgs = args[1].([]string)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockIEnforcer_GetUsersForRole_Call) Return(strings []string, err error) *MockIEnforcer_GetUsersForRole_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockIEnforcer_GetUsersForRole_Call) RunAndReturn(run func(name string, domain ...string) ([]string, error)) *MockIEnforcer_GetUsersForRole_Call {
	_c.Call.Return(run)
	return _c
}

// HasGroupingPolicy provides a mock function for the type MockIEnforcer
func (_mock *MockIEnforcer) HasGroupingPolicy(params ...interface{}) (bool, error) {
	var tmpRet mock.Arguments
	if len(params) > 0 {
		tmpRet = _mock.Called(params)
	} else {
		tmpRet = _mock.Called()
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for HasGroupingPolicy")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(...interface{}) (bool, error)); ok {
		return returnFunc(params...)
	}
	if returnFunc, ok := ret.Get(0).(func(...interface{}) bool); ok {
		r0 = returnFunc(params...)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(...interface{}) error); ok {
		r1 = returnFunc(params...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIEnforcer_HasGroupingPolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasGroupingPolicy'
type MockIEnforcer_HasGroupingPolicy_Call struct {
	*mock.Call
}

// HasGroupingPolicy is a helper method to define mock.On call
//   - params ...interface{}
func (_e *MockIEnforcer_Expecter) HasGroupingPolicy(params ...interface{}) *MockIEnforcer_HasGroupingPolicy_Call {
	return &MockIEnforcer_HasGroupingPolicy_Call{Call: _e.mock.On("HasGroupingPolicy",
		append([]interface{}{}, params...)...)}
}

func (_c *MockIEnforcer_HasGroupingPolicy_Call) Run(run func(params ...interface{})) *MockIEnforcer_HasGroupingPolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []interface{}
		var variadicArgs []interface{}
		if len(args) > 0 {
			variadicArgs = args[0].([]interface{})
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *MockIEnforcer_HasGroupingPolicy_Call) Return(b bool, err error) *MockIEnforcer_HasGroupingPolicy_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockIEnforcer_HasGroupingPolicy_Call) RunAndReturn(run func(params ...interface{}) (bool, error)) *MockIEnforcer_HasGroupingPolicy_Call {
	_c.Call.Return(run)
	return _c
}

// HasPolicy provides a mock function for the type MockIEnforcer
func (_mock *MockIEnforcer) HasPolicy(params ...interface{}) (bool, error) {
	var tmpRet mock.Arguments
	if len(params) > 0 {
		tmpRet = _mock.Called(params)
	} else {
		tmpRet = _mock.Called()
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for HasPolicy")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(...interface{}) (bool, error)); ok {
		return returnFunc(params...)
	}
	if returnFunc, ok := ret.Get(0).(func(...interface{}) bool); ok {
		r0 = returnFunc(params...)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(...interface{}) error); ok {
		r1 = returnFunc(params...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIEnforcer_HasPolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasPolicy'
type MockIEnforcer_HasPolicy_Call struct {
	*mock.Call
}

// HasPolicy is a helper method to define mock.On call
//   - params ...interface{}
func (_e *MockIEnforcer_Expecter) HasPolicy(params ...interface{}) *MockIEnforcer_HasPolicy_Call {
	return &MockIEnforcer_HasPolicy_Call{Call: _e.mock.On("HasPolicy",
		append([]interface{}{}, params...)...)}
}

func (_c *MockIEnforcer_HasPolicy_Call) Run(run func(params ...interface{})) *MockIEnforcer_HasPolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []interface{}
		var variadicArgs []interface{}
		if len(args) > 0 {
			variadicArgs = args[0].([]interface{})
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *MockIEnforcer_HasPolicy_Call) Return(b bool, err error) *MockIEnforcer_HasPolicy_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockIEnforcer_HasPolicy_Call) RunAndReturn(run func(params ...interface{}) (bool, error)) *MockIEnforcer_HasPolicy_Call {
	_c.Call.Return(run)
	return _c
}

// LoadPolicy provides a mock function for the type MockIEnforcer
func (_mock *MockIEnforcer) LoadPolicy() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for LoadPolicy")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIEnforcer_LoadPolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadPolicy'
type MockIEnforcer_LoadPolicy_Call struct {
	*mock.Call
}

// LoadPolicy is a helper method to define mock.On call
func (_e *MockIEnforcer_Expecter) LoadPolicy() *MockIEnforcer_LoadPolicy_Call {
	return &MockIEnforcer_LoadPolicy_Call{Call: _e.mock.On("LoadPolicy")}
}

func (_c *MockIEnforcer_LoadPolicy_Call) Run(run func()) *MockIEnforcer_LoadPolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIEnforcer_LoadPolicy_Call) Return(err error) *MockIEnforcer_LoadPolicy_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIEnforcer_LoadPolicy_Call) RunAndReturn(run func() error) *MockIEnforcer_LoadPolicy_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveFilteredGroupingPolicy provides a mock function for the type MockIEnforcer
func (_mock *MockIEnforcer) RemoveFilteredGroupingPolicy(fieldIndex int, fieldValues ...string) (bool, error) {
	var tmpRet mock.Arguments
	if len(fieldValues) > 0 {
		tmpRet = _mock.Called(fieldIndex, fieldValues)
	} else {
		tmpRet = _mock.Called(fieldIndex)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for RemoveFilteredGroupingPolicy")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int, ...string) (bool, error)); ok {
		return returnFunc(fieldIndex, fieldValues...)
	}
	if returnFunc, ok := ret.Get(0).(func(int, ...string) bool); ok {
		r0 = returnFunc(fieldIndex, fieldValues...)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(int, ...string) error); ok {
		r1 = returnFunc(fieldIndex, fieldValues...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIEnforcer_RemoveFilteredGroupingPolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveFilteredGroupingPolicy'
type MockIEnforcer_RemoveFilteredGroupingPolicy_Call struct {
	*mock.Call
}

// RemoveFilteredGroupingPolicy is a helper method to define mock.On call
//   - fieldIndex int
//   - fieldValues ...string
func (_e *MockIEnforcer_Expecter) RemoveFilteredGroupingPolicy(fieldIndex interface{}, fieldValues ...interface{}) *MockIEnforcer_RemoveFilteredGroupingPolicy_Call {
	return &MockIEnforcer_RemoveFilteredGroupingPolicy_Call{Call: _e.mock.On("RemoveFilteredGroupingPolicy",
		append([]interface{}{fieldIndex}, fieldValues...)...)}
}

func (_c *MockIEnforcer_RemoveFilteredGroupingPolicy_Call) Run(run func(fieldIndex int, fieldValues ...string)) *MockIEnforcer_RemoveFilteredGroupingPolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 []string
		var variadicArgs []string
		if len(args) > 1 {
			variadicArgs = args[1].([]string)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockIEnforcer_RemoveFilteredGroupingPolicy_Call) Return(b bool, err error) *MockIEnforcer_RemoveFilteredGroupingPolicy_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockIEnforcer_RemoveFilteredGroupingPolicy_Call) RunAndReturn(run func(fieldIndex int, fieldValues ...string) (bool, error)) *MockIEnforcer_RemoveFilteredGroupingPolicy_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveFilteredPolicy provides a mock function for the type MockIEnforcer
func (_mock *MockIEnforcer) RemoveFilteredPolicy(fieldIndex int, fieldValues ...string) (bool, error) {
	var tmpRet mock.Arguments
	if len(fieldValues) > 0 {
		tmpRet = _mock.Called(fieldIndex, fieldValues)
	} else {
		tmpRet = _mock.Called(fieldIndex)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for RemoveFilteredPolicy")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int, ...string) (bool, error)); ok {
		return returnFunc(fieldIndex, fieldValues...)
	}
	if returnFunc, ok := ret.Get(0).(func(int, ...string) bool); ok {
		r0 = returnFunc(fieldIndex, fieldValues...)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(int, ...string) error); ok {
		r1 = returnFunc(fieldIndex, fieldValues...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIEnforcer_RemoveFilteredPolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveFilteredPolicy'
type MockIEnforcer_RemoveFilteredPolicy_Call struct {
	*mock.Call
}

// RemoveFilteredPolicy is a helper method to define mock.On call
//   - fieldIndex int
//   - fieldValues ...string
func (_e *MockIEnforcer_Expecter) RemoveFilteredPolicy(fieldIndex interface{}, fieldValues ...interface{}) *MockIEnforcer_RemoveFilteredPolicy_Call {
	return &MockIEnforcer_RemoveFilteredPolicy_Call{Call: _e.mock.On("RemoveFilteredPolicy",
		append([]interface{}{fieldIndex}, fieldValues...)...)}
}

func (_c *MockIEnforcer_RemoveFilteredPolicy_Call) Run(run func(fieldIndex int, fieldValues ...string)) *MockIEnforcer_RemoveFilteredPolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 []string
		var variadicArgs []string
		if len(args) > 1 {
			variadicArgs = args[1].([]string)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockIEnforcer_RemoveFilteredPolicy_Call) Return(b bool, err error) *MockIEnforcer_RemoveFilteredPolicy_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockIEnforcer_RemoveFilteredPolicy_Call) RunAndReturn(run func(fieldIndex int, fieldValues ...string) (bool, error)) *MockIEnforcer_RemoveFilteredPolicy_Call {
	_c.Call.Return(run)
	return _c
}

// RemovePolicy provides a mock function for the type MockIEnforcer
func (_mock *MockIEnforcer) RemovePolicy(params ...interface{}) (bool, error) {
	var tmpRet mock.Arguments
	if len(params) > 0 {
		tmpRet = _mock.Called(params)
	} else {
		tmpRet = _mock.Called()
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for RemovePolicy")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(...interface{}) (bool, error)); ok {
		return returnFunc(params...)
	}
	if returnFunc, ok := ret.Get(0).(func(...interface{}) bool); ok {
		r0 = returnFunc(params...)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(...interface{}) error); ok {
		r1 = returnFunc(params...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIEnforcer_RemovePolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemovePolicy'
type MockIEnforcer_RemovePolicy_Call struct {
	*mock.Call
}

// RemovePolicy is a helper method to define mock.On call
//   - params ...interface{}
func (_e *MockIEnforcer_Expecter) RemovePolicy(params ...interface{}) *MockIEnforcer_RemovePolicy_Call {
	return &MockIEnforcer_RemovePolicy_Call{Call: _e.mock.On("RemovePolicy",
		append([]interface{}{}, params...)...)}
}

func (_c *MockIEnforcer_RemovePolicy_Call) Run(run func(params ...interface{})) *MockIEnforcer_RemovePolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []interface{}
		var variadicArgs []interface{}
		if len(args) > 0 {
			variadicArgs = args[0].([]interface{})
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *MockIEnforcer_RemovePolicy_Call) Return(b bool, err error) *MockIEnforcer_RemovePolicy_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockIEnforcer_RemovePolicy_Call) RunAndReturn(run func(params ...interface{}) (bool, error)) *MockIEnforcer_RemovePolicy_Call {
	_c.Call.Return(run)
	return _c
}

// SavePolicy provides a mock function for the type MockIEnforcer
func (_mock *MockIEnforcer) SavePolicy() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for SavePolicy")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIEnforcer_SavePolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SavePolicy'
type MockIEnforcer_SavePolicy_Call struct {
	*mock.Call
}

// SavePolicy is a helper method to define mock.On call
func (_e *MockIEnforcer_Expecter) SavePolicy() *MockIEnforcer_SavePolicy_Call {
	return &MockIEnforcer_SavePolicy_Call{Call: _e.mock.On("SavePolicy")}
}

func (_c *MockIEnforcer_SavePolicy_Call) Run(run func()) *MockIEnforcer_SavePolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIEnforcer_SavePolicy_Call) Return(err error) *MockIEnforcer_SavePolicy_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIEnforcer_SavePolicy_Call) RunAndReturn(run func() error) *MockIEnforcer_SavePolicy_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePolicy provides a mock function for the type MockIEnforcer
func (_mock *MockIEnforcer) UpdatePolicy(oldRule []string, newRule []string) (bool, error) {
	ret := _mock.Called(oldRule, newRule)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePolicy")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]string, []string) (bool, error)); ok {
		return returnFunc(oldRule, newRule)
	}
	if returnFunc, ok := ret.Get(0).(func([]string, []string) bool); ok {
		r0 = returnFunc(oldRule, newRule)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func([]string, []string) error); ok {
		r1 = returnFunc(oldRule, newRule)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIEnforcer_UpdatePolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePolicy'
type MockIEnforcer_UpdatePolicy_Call struct {
	*mock.Call
}

// UpdatePolicy is a helper method to define mock.On call
//   - oldRule []string
//   - newRule []string
func (_e *MockIEnforcer_Expecter) UpdatePolicy(oldRule interface{}, newRule interface{}) *MockIEnforcer_UpdatePolicy_Call {
	return &MockIEnforcer_UpdatePolicy_Call{Call: _e.mock.On("UpdatePolicy", oldRule, newRule)}
}

func (_c *MockIEnforcer_UpdatePolicy_Call) Run(run func(oldRule []string, newRule []string)) *MockIEnforcer_UpdatePolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []string
		if args[0] != nil {
			arg0 = args[0].([]string)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIEnforcer_UpdatePolicy_Call) Return(b bool, err error) *MockIEnforcer_UpdatePolicy_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockIEnforcer_UpdatePolicy_Call) RunAndReturn(run func(oldRule []string, newRule []string) (bool, error)) *MockIEnforcer_UpdatePolicy_Call {
	_c.Call.Return(run)
	return _c
}

// WithContext provides a mock function for the type MockIEnforcer
func (_mock *MockIEnforcer) WithContext(ctx context.Context) usecase.IEnforcer {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for WithContext")
	}

	var r0 usecase.IEnforcer
	if returnFunc, ok := ret.Get(0).(func(context.Context) usecase.IEnforcer); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(usecase.IEnforcer)
		}
	}
	return r0
}

// MockIEnforcer_WithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithContext'
type MockIEnforcer_WithContext_Call struct {
	*mock.Call
}

// WithContext is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIEnforcer_Expecter) WithContext(ctx interface{}) *MockIEnforcer_WithContext_Call {
	return &MockIEnforcer_WithContext_Call{Call: _e.mock.On("WithContext", ctx)}
}

func (_c *MockIEnforcer_WithContext_Call) Run(run func(ctx context.Context)) *MockIEnforcer_WithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIEnforcer_WithContext_Call) Return(iEnforcer usecase.IEnforcer) *MockIEnforcer_WithContext_Call {
	_c.Call.Return(iEnforcer)
	return _c
}

func (_c *MockIEnforcer_WithContext_Call) RunAndReturn(run func(ctx context.Context) usecase.IEnforcer) *MockIEnforcer_WithContext_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIPermissionUseCase creates a new instance of MockIPermissionUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIPermissionUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIPermissionUseCase {
	m := &MockIPermissionUseCase{}
	m.Mock.Test(t)

	t.Cleanup(func() { m.AssertExpectations(t) })

	return m
}

// MockIPermissionUseCase is an autogenerated mock type for the IPermissionUseCase type
type MockIPermissionUseCase struct {
	mock.Mock
}

type MockIPermissionUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIPermissionUseCase) EXPECT() *MockIPermissionUseCase_Expecter {
	return &MockIPermissionUseCase_Expecter{mock: &_m.Mock}
}

// AddParentRole provides a mock function for the type MockIPermissionUseCase
func (_mock *MockIPermissionUseCase) AddParentRole(ctx context.Context, childRole string, parentRole string, domain string) error {
	ret := _mock.Called(ctx, childRole, parentRole, domain)

	if len(ret) == 0 {
		panic("no return value specified for AddParentRole")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, childRole, parentRole, domain)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIPermissionUseCase_AddParentRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddParentRole'
type MockIPermissionUseCase_AddParentRole_Call struct {
	*mock.Call
}

// AddParentRole is a helper method to define mock.On call
//   - ctx context.Context
//   - childRole string
//   - parentRole string
//   - domain string
func (_e *MockIPermissionUseCase_Expecter) AddParentRole(ctx interface{}, childRole interface{}, parentRole interface{}, domain interface{}) *MockIPermissionUseCase_AddParentRole_Call {
	return &MockIPermissionUseCase_AddParentRole_Call{Call: _e.mock.On("AddParentRole", ctx, childRole, parentRole, domain)}
}

func (_c *MockIPermissionUseCase_AddParentRole_Call) Run(run func(ctx context.Context, childRole string, parentRole string, domain string)) *MockIPermissionUseCase_AddParentRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockIPermissionUseCase_AddParentRole_Call) Return(err error) *MockIPermissionUseCase_AddParentRole_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIPermissionUseCase_AddParentRole_Call) RunAndReturn(run func(ctx context.Context, childRole string, parentRole string, domain string) error) *MockIPermissionUseCase_AddParentRole_Call {
	_c.Call.Return(run)
	return _c
}

// AssignAccessRight provides a mock function for the type MockIPermissionUseCase
func (_mock *MockIPermissionUseCase) AssignAccessRight(ctx context.Context, req model.AssignAccessRightRequest) error {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for AssignAccessRight")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.AssignAccessRightRequest) error); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIPermissionUseCase_AssignAccessRight_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssignAccessRight'
type MockIPermissionUseCase_AssignAccessRight_Call struct {
	*mock.Call
}

// AssignAccessRight is a helper method to define mock.On call
//   - ctx context.Context
//   - req model.AssignAccessRightRequest
func (_e *MockIPermissionUseCase_Expecter) AssignAccessRight(ctx interface{}, req interface{}) *MockIPermissionUseCase_AssignAccessRight_Call {
	return &MockIPermissionUseCase_AssignAccessRight_Call{Call: _e.mock.On("AssignAccessRight", ctx, req)}
}

func (_c *MockIPermissionUseCase_AssignAccessRight_Call) Run(run func(ctx context.Context, req model.AssignAccessRightRequest)) *MockIPermissionUseCase_AssignAccessRight_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.AssignAccessRightRequest
		if args[1] != nil {
			arg1 = args[1].(model.AssignAccessRightRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIPermissionUseCase_AssignAccessRight_Call) Return(err error) *MockIPermissionUseCase_AssignAccessRight_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIPermissionUseCase_AssignAccessRight_Call) RunAndReturn(run func(ctx context.Context, req model.AssignAccessRightRequest) error) *MockIPermissionUseCase_AssignAccessRight_Call {
	_c.Call.Return(run)
	return _c
}

// AssignRoleToUser provides a mock function for the type MockIPermissionUseCase
func (_mock *MockIPermissionUseCase) AssignRoleToUser(ctx context.Context, userID string, role string, domain string) error {
	ret := _mock.Called(ctx, userID, role, domain)

	if len(ret) == 0 {
		panic("no return value specified for AssignRoleToUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, userID, role, domain)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIPermissionUseCase_AssignRoleToUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssignRoleToUser'
type MockIPermissionUseCase_AssignRoleToUser_Call struct {
	*mock.Call
}

// AssignRoleToUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - role string
//   - domain string
func (_e *MockIPermissionUseCase_Expecter) AssignRoleToUser(ctx interface{}, userID interface{}, role interface{}, domain interface{}) *MockIPermissionUseCase_AssignRoleToUser_Call {
	return &MockIPermissionUseCase_AssignRoleToUser_Call{Call: _e.mock.On("AssignRoleToUser", ctx, userID, role, domain)}
}

func (_c *MockIPermissionUseCase_AssignRoleToUser_Call) Run(run func(ctx context.Context, userID string, role string, domain string)) *MockIPermissionUseCase_AssignRoleToUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockIPermissionUseCase_AssignRoleToUser_Call) Return(err error) *MockIPermissionUseCase_AssignRoleToUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIPermissionUseCase_AssignRoleToUser_Call) RunAndReturn(run func(ctx context.Context, userID string, role string, domain string) error) *MockIPermissionUseCase_AssignRoleToUser_Call {
	_c.Call.Return(run)
	return _c
}

// BatchCheckPermission provides a mock function for the type MockIPermissionUseCase
func (_mock *MockIPermissionUseCase) BatchCheckPermission(ctx context.Context, userID string, items []model.PermissionCheckItem) (map[string]bool, error) {
	ret := _mock.Called(ctx, userID, items)

	if len(ret) == 0 {
		panic("no return value specified for BatchCheckPermission")
	}

	var r0 map[string]bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []model.PermissionCheckItem) (map[string]bool, error)); ok {
		return returnFunc(ctx, userID, items)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []model.PermissionCheckItem) map[string]bool); ok {
		r0 = returnFunc(ctx, userID, items)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]bool)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []model.PermissionCheckItem) error); ok {
		r1 = returnFunc(ctx, userID, items)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIPermissionUseCase_BatchCheckPermission_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BatchCheckPermission'
type MockIPermissionUseCase_BatchCheckPermission_Call struct {
	*mock.Call
}

// BatchCheckPermission is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - items []model.PermissionCheckItem
func (_e *MockIPermissionUseCase_Expecter) BatchCheckPermission(ctx interface{}, userID interface{}, items interface{}) *MockIPermissionUseCase_BatchCheckPermission_Call {
	return &MockIPermissionUseCase_BatchCheckPermission_Call{Call: _e.mock.On("BatchCheckPermission", ctx, userID, items)}
}

func (_c *MockIPermissionUseCase_BatchCheckPermission_Call) Run(run func(ctx context.Context, userID string, items []model.PermissionCheckItem)) *MockIPermissionUseCase_BatchCheckPermission_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []model.PermissionCheckItem
		if args[2] != nil {
			arg2 = args[2].([]model.PermissionCheckItem)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIPermissionUseCase_BatchCheckPermission_Call) Return(stringToBool map[string]bool, err error) *MockIPermissionUseCase_BatchCheckPermission_Call {
	_c.Call.Return(stringToBool, err)
	return _c
}

func (_c *MockIPermissionUseCase_BatchCheckPermission_Call) RunAndReturn(run func(ctx context.Context, userID string, items []model.PermissionCheckItem) (map[string]bool, error)) *MockIPermissionUseCase_BatchCheckPermission_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRole provides a mock function for the type MockIPermissionUseCase
func (_mock *MockIPermissionUseCase) DeleteRole(ctx context.Context, roleName string) error {
	ret := _mock.Called(ctx, roleName)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRole")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, roleName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIPermissionUseCase_DeleteRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRole'
type MockIPermissionUseCase_DeleteRole_Call struct {
	*mock.Call
}

// DeleteRole is a helper method to define mock.On call
//   - ctx context.Context
//   - roleName string
func (_e *MockIPermissionUseCase_Expecter) DeleteRole(ctx interface{}, roleName interface{}) *MockIPermissionUseCase_DeleteRole_Call {
	return &MockIPermissionUseCase_DeleteRole_Call{Call: _e.mock.On("DeleteRole", ctx, roleName)}
}

func (_c *MockIPermissionUseCase_DeleteRole_Call) Run(run func(ctx context.Context, roleName string)) *MockIPermissionUseCase_DeleteRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIPermissionUseCase_DeleteRole_Call) Return(err error) *MockIPermissionUseCase_DeleteRole_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIPermissionUseCase_DeleteRole_Call) RunAndReturn(run func(ctx context.Context, roleName string) error) *MockIPermissionUseCase_DeleteRole_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllPermissions provides a mock function for the type MockIPermissionUseCase
func (_mock *MockIPermissionUseCase) GetAllPermissions(ctx context.Context) ([][]string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllPermissions")
	}

	var r0 [][]string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([][]string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) [][]string); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([][]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIPermissionUseCase_GetAllPermissions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllPermissions'
type MockIPermissionUseCase_GetAllPermissions_Call struct {
	*mock.Call
}

// GetAllPermissions is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIPermissionUseCase_Expecter) GetAllPermissions(ctx interface{}) *MockIPermissionUseCase_GetAllPermissions_Call {
	return &MockIPermissionUseCase_GetAllPermissions_Call{Call: _e.mock.On("GetAllPermissions", ctx)}
}

func (_c *MockIPermissionUseCase_GetAllPermissions_Call) Run(run func(ctx context.Context)) *MockIPermissionUseCase_GetAllPermissions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIPermissionUseCase_GetAllPermissions_Call) Return(stringss [][]string, err error) *MockIPermissionUseCase_GetAllPermissions_Call {
	_c.Call.Return(stringss, err)
	return _c
}

func (_c *MockIPermissionUseCase_GetAllPermissions_Call) RunAndReturn(run func(ctx context.Context) ([][]string, error)) *MockIPermissionUseCase_GetAllPermissions_Call {
	_c.Call.Return(run)
	return _c
}

// GetInheritanceTree provides a mock function for the type MockIPermissionUseCase
func (_mock *MockIPermissionUseCase) GetInheritanceTree(ctx context.Context) (*model.InheritanceTreeResponse, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetInheritanceTree")
	}

	var r0 *model.InheritanceTreeResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*model.InheritanceTreeResponse, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *model.InheritanceTreeResponse); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.InheritanceTreeResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIPermissionUseCase_GetInheritanceTree_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInheritanceTree'
type MockIPermissionUseCase_GetInheritanceTree_Call struct {
	*mock.Call
}

// GetInheritanceTree is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIPermissionUseCase_Expecter) GetInheritanceTree(ctx interface{}) *MockIPermissionUseCase_GetInheritanceTree_Call {
	return &MockIPermissionUseCase_GetInheritanceTree_Call{Call: _e.mock.On("GetInheritanceTree", ctx)}
}

func (_c *MockIPermissionUseCase_GetInheritanceTree_Call) Run(run func(ctx context.Context)) *MockIPermissionUseCase_GetInheritanceTree_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIPermissionUseCase_GetInheritanceTree_Call) Return(inheritanceTreeResponse *model.InheritanceTreeResponse, err error) *MockIPermissionUseCase_GetInheritanceTree_Call {
	_c.Call.Return(inheritanceTreeResponse, err)
	return _c
}

func (_c *MockIPermissionUseCase_GetInheritanceTree_Call) RunAndReturn(run func(ctx context.Context) (*model.InheritanceTreeResponse, error)) *MockIPermissionUseCase_GetInheritanceTree_Call {
	_c.Call.Return(run)
	return _c
}

// GetParentRoles provides a mock function for the type MockIPermissionUseCase
func (_mock *MockIPermissionUseCase) GetParentRoles(ctx context.Context, role string, domain string) ([]string, error) {
	ret := _mock.Called(ctx, role, domain)

	if len(ret) == 0 {
		panic("no return value specified for GetParentRoles")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]string, error)); ok {
		return returnFunc(ctx, role, domain)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []string); ok {
		r0 = returnFunc(ctx, role, domain)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, role, domain)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIPermissionUseCase_GetParentRoles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetParentRoles'
type MockIPermissionUseCase_GetParentRoles_Call struct {
	*mock.Call
}

// GetParentRoles is a helper method to define mock.On call
//   - ctx context.Context
//   - role string
//   - domain string
func (_e *MockIPermissionUseCase_Expecter) GetParentRoles(ctx interface{}, role interface{}, domain interface{}) *MockIPermissionUseCase_GetParentRoles_Call {
	return &MockIPermissionUseCase_GetParentRoles_Call{Call: _e.mock.On("GetParentRoles", ctx, role, domain)}
}

func (_c *MockIPermissionUseCase_GetParentRoles_Call) Run(run func(ctx context.Context, role string, domain string)) *MockIPermissionUseCase_GetParentRoles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIPermissionUseCase_GetParentRoles_Call) Return(strings []string, err error) *MockIPermissionUseCase_GetParentRoles_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockIPermissionUseCase_GetParentRoles_Call) RunAndReturn(run func(ctx context.Context, role string, domain string) ([]string, error)) *MockIPermissionUseCase_GetParentRoles_Call {
	_c.Call.Return(run)
	return _c
}

// GetPermissionsForRole provides a mock function for the type MockIPermissionUseCase
func (_mock *MockIPermissionUseCase) GetPermissionsForRole(ctx context.Context, role string) ([][]string, error) {
	ret := _mock.Called(ctx, role)

	if len(ret) == 0 {
		panic("no return value specified for GetPermissionsForRole")
	}

	var r0 [][]string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([][]string, error)); ok {
		return returnFunc(ctx, role)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) [][]string); ok {
		r0 = returnFunc(ctx, role)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([][]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, role)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIPermissionUseCase_GetPermissionsForRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPermissionsForRole'
type MockIPermissionUseCase_GetPermissionsForRole_Call struct {
	*mock.Call
}

// GetPermissionsForRole is a helper method to define mock.On call
//   - ctx context.Context
//   - role string
func (_e *MockIPermissionUseCase_Expecter) GetPermissionsForRole(ctx interface{}, role interface{}) *MockIPermissionUseCase_GetPermissionsForRole_Call {
	return &MockIPermissionUseCase_GetPermissionsForRole_Call{Call: _e.mock.On("GetPermissionsForRole", ctx, role)}
}

func (_c *MockIPermissionUseCase_GetPermissionsForRole_Call) Run(run func(ctx context.Context, role string)) *MockIPermissionUseCase_GetPermissionsForRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIPermissionUseCase_GetPermissionsForRole_Call) Return(stringss [][]string, err error) *MockIPermissionUseCase_GetPermissionsForRole_Call {
	_c.Call.Return(stringss, err)
	return _c
}

func (_c *MockIPermissionUseCase_GetPermissionsForRole_Call) RunAndReturn(run func(ctx context.Context, role string) ([][]string, error)) *MockIPermissionUseCase_GetPermissionsForRole_Call {
	_c.Call.Return(run)
	return _c
}

// GetResourceAggregation provides a mock function for the type MockIPermissionUseCase
func (_mock *MockIPermissionUseCase) GetResourceAggregation(ctx context.Context) (*model.ResourceAggregationResponse, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetResourceAggregation")
	}

	var r0 *model.ResourceAggregationResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*model.ResourceAggregationResponse, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *model.ResourceAggregationResponse); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ResourceAggregationResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIPermissionUseCase_GetResourceAggregation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetResourceAggregation'
type MockIPermissionUseCase_GetResourceAggregation_Call struct {
	*mock.Call
}

// GetResourceAggregation is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIPermissionUseCase_Expecter) GetResourceAggregation(ctx interface{}) *MockIPermissionUseCase_GetResourceAggregation_Call {
	return &MockIPermissionUseCase_GetResourceAggregation_Call{Call: _e.mock.On("GetResourceAggregation", ctx)}
}

func (_c *MockIPermissionUseCase_GetResourceAggregation_Call) Run(run func(ctx context.Context)) *MockIPermissionUseCase_GetResourceAggregation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIPermissionUseCase_GetResourceAggregation_Call) Return(resourceAggregationResponse *model.ResourceAggregationResponse, err error) *MockIPermissionUseCase_GetResourceAggregation_Call {
	_c.Call.Return(resourceAggregationResponse, err)
	return _c
}

func (_c *MockIPermissionUseCase_GetResourceAggregation_Call) RunAndReturn(run func(ctx context.Context) (*model.ResourceAggregationResponse, error)) *MockIPermissionUseCase_GetResourceAggregation_Call {
	_c.Call.Return(run)
	return _c
}

// GetRoleAccessRights provides a mock function for the type MockIPermissionUseCase
func (_mock *MockIPermissionUseCase) GetRoleAccessRights(ctx context.Context, role string, domain string) ([]model.RoleAccessRightStatus, error) {
	ret := _mock.Called(ctx, role, domain)

	if len(ret) == 0 {
		panic("no return value specified for GetRoleAccessRights")
	}

	var r0 []model.RoleAccessRightStatus
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]model.RoleAccessRightStatus, error)); ok {
		return returnFunc(ctx, role, domain)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []model.RoleAccessRightStatus); ok {
		r0 = returnFunc(ctx, role, domain)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.RoleAccessRightStatus)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, role, domain)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIPermissionUseCase_GetRoleAccessRights_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRoleAccessRights'
type MockIPermissionUseCase_GetRoleAccessRights_Call struct {
	*mock.Call
}

// GetRoleAccessRights is a helper method to define mock.On call
//   - ctx context.Context
//   - role string
//   - domain string
func (_e *MockIPermissionUseCase_Expecter) GetRoleAccessRights(ctx interface{}, role interface{}, domain interface{}) *MockIPermissionUseCase_GetRoleAccessRights_Call {
	return &MockIPermissionUseCase_GetRoleAccessRights_Call{Call: _e.mock.On("GetRoleAccessRights", ctx, role, domain)}
}

func (_c *MockIPermissionUseCase_GetRoleAccessRights_Call) Run(run func(ctx context.Context, role string, domain string)) *MockIPermissionUseCase_GetRoleAccessRights_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIPermissionUseCase_GetRoleAccessRights_Call) Return(roleAccessRightStatuss []model.RoleAccessRightStatus, err error) *MockIPermissionUseCase_GetRoleAccessRights_Call {
	_c.Call.Return(roleAccessRightStatuss, err)
	return _c
}

func (_c *MockIPermissionUseCase_GetRoleAccessRights_Call) RunAndReturn(run func(ctx context.Context, role string, domain string) ([]model.RoleAccessRightStatus, error)) *MockIPermissionUseCase_GetRoleAccessRights_Call {
	_c.Call.Return(run)
	return _c
}

// GetUsersForRole provides a mock function for the type MockIPermissionUseCase
func (_mock *MockIPermissionUseCase) GetUsersForRole(ctx context.Context, role string, domain string) ([]string, error) {
	ret := _mock.Called(ctx, role, domain)

	if len(ret) == 0 {
		panic("no return value specified for GetUsersForRole")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]string, error)); ok {
		return returnFunc(ctx, role, domain)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []string); ok {
		r0 = returnFunc(ctx, role, domain)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, role, domain)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIPermissionUseCase_GetUsersForRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUsersForRole'
type MockIPermissionUseCase_GetUsersForRole_Call struct {
	*mock.Call
}

// GetUsersForRole is a helper method to define mock.On call
//   - ctx context.Context
//   - role string
//   - domain string
func (_e *MockIPermissionUseCase_Expecter) GetUsersForRole(ctx interface{}, role interface{}, domain interface{}) *MockIPermissionUseCase_GetUsersForRole_Call {
	return &MockIPermissionUseCase_GetUsersForRole_Call{Call: _e.mock.On("GetUsersForRole", ctx, role, domain)}
}

func (_c *MockIPermissionUseCase_GetUsersForRole_Call) Run(run func(ctx context.Context, role string, domain string)) *MockIPermissionUseCase_GetUsersForRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIPermissionUseCase_GetUsersForRole_Call) Return(strings []string, err error) *MockIPermissionUseCase_GetUsersForRole_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockIPermissionUseCase_GetUsersForRole_Call) RunAndReturn(run func(ctx context.Context, role string, domain string) ([]string, error)) *MockIPermissionUseCase_GetUsersForRole_Call {
	_c.Call.Return(run)
	return _c
}

// GrantPermissionToRole provides a mock function for the type MockIPermissionUseCase
func (_mock *MockIPermissionUseCase) GrantPermissionToRole(ctx context.Context, role string, path string, method string, domain string) error {
	ret := _mock.Called(ctx, role, path, method, domain)

	if len(ret) == 0 {
		panic("no return value specified for GrantPermissionToRole")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) error); ok {
		r0 = returnFunc(ctx, role, path, method, domain)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIPermissionUseCase_GrantPermissionToRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GrantPermissionToRole'
type MockIPermissionUseCase_GrantPermissionToRole_Call struct {
	*mock.Call
}

// GrantPermissionToRole is a helper method to define mock.On call
//   - ctx context.Context
//   - role string
//   - path string
//   - method string
//   - domain string
func (_e *MockIPermissionUseCase_Expecter) GrantPermissionToRole(ctx interface{}, role interface{}, path interface{}, method interface{}, domain interface{}) *MockIPermissionUseCase_GrantPermissionToRole_Call {
	return &MockIPermissionUseCase_GrantPermissionToRole_Call{Call: _e.mock.On("GrantPermissionToRole", ctx, role, path, method, domain)}
}

func (_c *MockIPermissionUseCase_GrantPermissionToRole_Call) Run(run func(ctx context.Context, role string, path string, method string, domain string)) *MockIPermissionUseCase_GrantPermissionToRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockIPermissionUseCase_GrantPermissionToRole_Call) Return(err error) *MockIPermissionUseCase_GrantPermissionToRole_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIPermissionUseCase_GrantPermissionToRole_Call) RunAndReturn(run func(ctx context.Context, role string, path string, method string, domain string) error) *MockIPermissionUseCase_GrantPermissionToRole_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveParentRole provides a mock function for the type MockIPermissionUseCase
func (_mock *MockIPermissionUseCase) RemoveParentRole(ctx context.Context, childRole string, parentRole string, domain string) error {
	ret := _mock.Called(ctx, childRole, parentRole, domain)

	if len(ret) == 0 {
		panic("no return value specified for RemoveParentRole")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, childRole, parentRole, domain)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIPermissionUseCase_RemoveParentRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveParentRole'
type MockIPermissionUseCase_RemoveParentRole_Call struct {
	*mock.Call
}

// RemoveParentRole is a helper method to define mock.On call
//   - ctx context.Context
//   - childRole string
//   - parentRole string
//   - domain string
func (_e *MockIPermissionUseCase_Expecter) RemoveParentRole(ctx interface{}, childRole interface{}, parentRole interface{}, domain interface{}) *MockIPermissionUseCase_RemoveParentRole_Call {
	return &MockIPermissionUseCase_RemoveParentRole_Call{Call: _e.mock.On("RemoveParentRole", ctx, childRole, parentRole, domain)}
}

func (_c *MockIPermissionUseCase_RemoveParentRole_Call) Run(run func(ctx context.Context, childRole string, parentRole string, domain string)) *MockIPermissionUseCase_RemoveParentRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockIPermissionUseCase_RemoveParentRole_Call) Return(err error) *MockIPermissionUseCase_RemoveParentRole_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIPermissionUseCase_RemoveParentRole_Call) RunAndReturn(run func(ctx context.Context, childRole string, parentRole string, domain string) error) *MockIPermissionUseCase_RemoveParentRole_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeAccessRight provides a mock function for the type MockIPermissionUseCase
func (_mock *MockIPermissionUseCase) RevokeAccessRight(ctx context.Context, req model.AssignAccessRightRequest) error {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for RevokeAccessRight")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.AssignAccessRightRequest) error); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIPermissionUseCase_RevokeAccessRight_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeAccessRight'
type MockIPermissionUseCase_RevokeAccessRight_Call struct {
	*mock.Call
}

// RevokeAccessRight is a helper method to define mock.On call
//   - ctx context.Context
//   - req model.AssignAccessRightRequest
func (_e *MockIPermissionUseCase_Expecter) RevokeAccessRight(ctx interface{}, req interface{}) *MockIPermissionUseCase_RevokeAccessRight_Call {
	return &MockIPermissionUseCase_RevokeAccessRight_Call{Call: _e.mock.On("RevokeAccessRight", ctx, req)}
}

func (_c *MockIPermissionUseCase_RevokeAccessRight_Call) Run(run func(ctx context.Context, req model.AssignAccessRightRequest)) *MockIPermissionUseCase_RevokeAccessRight_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.AssignAccessRightRequest
		if args[1] != nil {
			arg1 = args[1].(model.AssignAccessRightRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIPermissionUseCase_RevokeAccessRight_Call) Return(err error) *MockIPermissionUseCase_RevokeAccessRight_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIPermissionUseCase_RevokeAccessRight_Call) RunAndReturn(run func(ctx context.Context, req model.AssignAccessRightRequest) error) *MockIPermissionUseCase_RevokeAccessRight_Call {
	_c.Call.Return(run)
	return _c
}

// RevokePermissionFromRole provides a mock function for the type MockIPermissionUseCase
func (_mock *MockIPermissionUseCase) RevokePermissionFromRole(ctx context.Context, role string, path string, method string, domain string) error {
	ret := _mock.Called(ctx, role, path, method, domain)

	if len(ret) == 0 {
		panic("no return value specified for RevokePermissionFromRole")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) error); ok {
		r0 = returnFunc(ctx, role, path, method, domain)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIPermissionUseCase_RevokePermissionFromRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokePermissionFromRole'
type MockIPermissionUseCase_RevokePermissionFromRole_Call struct {
	*mock.Call
}

// RevokePermissionFromRole is a helper method to define mock.On call
//   - ctx context.Context
//   - role string
//   - path string
//   - method string
//   - domain string
func (_e *MockIPermissionUseCase_Expecter) RevokePermissionFromRole(ctx interface{}, role interface{}, path interface{}, method interface{}, domain interface{}) *MockIPermissionUseCase_RevokePermissionFromRole_Call {
	return &MockIPermissionUseCase_RevokePermissionFromRole_Call{Call: _e.mock.On("RevokePermissionFromRole", ctx, role, path, method, domain)}
}

func (_c *MockIPermissionUseCase_RevokePermissionFromRole_Call) Run(run func(ctx context.Context, role string, path string, method string, domain string)) *MockIPermissionUseCase_RevokePermissionFromRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockIPermissionUseCase_RevokePermissionFromRole_Call) Return(err error) *MockIPermissionUseCase_RevokePermissionFromRole_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIPermissionUseCase_RevokePermissionFromRole_Call) RunAndReturn(run func(ctx context.Context, role string, path string, method string, domain string) error) *MockIPermissionUseCase_RevokePermissionFromRole_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeRoleFromUser provides a mock function for the type MockIPermissionUseCase
func (_mock *MockIPermissionUseCase) RevokeRoleFromUser(ctx context.Context, userID string, role string, domain string) error {
	ret := _mock.Called(ctx, userID, role, domain)

	if len(ret) == 0 {
		panic("no return value specified for RevokeRoleFromUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, userID, role, domain)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIPermissionUseCase_RevokeRoleFromUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeRoleFromUser'
type MockIPermissionUseCase_RevokeRoleFromUser_Call struct {
	*mock.Call
}

// RevokeRoleFromUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - role string
//   - domain string
func (_e *MockIPermissionUseCase_Expecter) RevokeRoleFromUser(ctx interface{}, userID interface{}, role interface{}, domain interface{}) *MockIPermissionUseCase_RevokeRoleFromUser_Call {
	return &MockIPermissionUseCase_RevokeRoleFromUser_Call{Call: _e.mock.On("RevokeRoleFromUser", ctx, userID, role, domain)}
}

func (_c *MockIPermissionUseCase_RevokeRoleFromUser_Call) Run(run func(ctx context.Context, userID string, role string, domain string)) *MockIPermissionUseCase_RevokeRoleFromUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockIPermissionUseCase_RevokeRoleFromUser_Call) Return(err error) *MockIPermissionUseCase_RevokeRoleFromUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIPermissionUseCase_RevokeRoleFromUser_Call) RunAndReturn(run func(ctx context.Context, userID string, role string, domain string) error) *MockIPermissionUseCase_RevokeRoleFromUser_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePermission provides a mock function for the type MockIPermissionUseCase
func (_mock *MockIPermissionUseCase) UpdatePermission(ctx context.Context, oldPermission []string, newPermission []string) (bool, error) {
	ret := _mock.Called(ctx, oldPermission, newPermission)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePermission")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, []string) (bool, error)); ok {
		return returnFunc(ctx, oldPermission, newPermission)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, []string) bool); ok {
		r0 = returnFunc(ctx, oldPermission, newPermission)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string, []string) error); ok {
		r1 = returnFunc(ctx, oldPermission, newPermission)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIPermissionUseCase_UpdatePermission_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePermission'
type MockIPermissionUseCase_UpdatePermission_Call struct {
	*mock.Call
}

// UpdatePermission is a helper method to define mock.On call
//   - ctx context.Context
//   - oldPermission []string
//   - newPermission []string
func (_e *MockIPermissionUseCase_Expecter) UpdatePermission(ctx interface{}, oldPermission interface{}, newPermission interface{}) *MockIPermissionUseCase_UpdatePermission_Call {
	return &MockIPermissionUseCase_UpdatePermission_Call{Call: _e.mock.On("UpdatePermission", ctx, oldPermission, newPermission)}
}

func (_c *MockIPermissionUseCase_UpdatePermission_Call) Run(run func(ctx context.Context, oldPermission []string, newPermission []string)) *MockIPermissionUseCase_UpdatePermission_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIPermissionUseCase_UpdatePermission_Call) Return(b bool, err error) *MockIPermissionUseCase_UpdatePermission_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockIPermissionUseCase_UpdatePermission_Call) RunAndReturn(run func(ctx context.Context, oldPermission []string, newPermission []string) (bool, error)) *MockIPermissionUseCase_UpdatePermission_Call {
	_c.Call.Return(run)
	return _c
}
