FROM golang:1.25-alpine

# Install git and air for live reloading
RUN apk add --no-cache git curl && \
    go install github.com/air-verse/air@latest

WORKDIR /app

# Copy dependency files first to utilize cache
COPY go.mod go.sum ./
RUN go mod download

# Copy the rest of the application
COPY . .

# Expose API port
EXPOSE 8080

# Run air
CMD ["air", "-c", ".air.toml"]
