import {
  type RouteConfig,
  index,
  route,
  layout,
  prefix,
} from "@react-router/dev/routes";

export default [
  index("pages/LandingPage.tsx"),
  route("api/v1/*", "routes/api-proxy.ts"),
  route("newsletter/confirm", "pages/NewsletterConfirmPage.tsx"),

  route("login", "pages/LoginPage.tsx"),
  route("register", "pages/RegisterPage.tsx"),
  route("forgot-password", "pages/ForgotPasswordPage.tsx"),
  route("reset-password", "pages/ResetPasswordPage.tsx"),

  ...prefix("auth", [
    route("login-v1", "pages/auth/LoginV1.tsx"),
    route("login-v2", "pages/auth/LoginV2.tsx"),
    route("login-v3", "pages/auth/LoginV3.tsx"),
    route("register-v1", "pages/auth/RegisterV1.tsx"),
    route("register-v2", "pages/auth/RegisterV2.tsx"),
    route("register-v3", "pages/auth/RegisterV3.tsx"),
    route("forgot-password-v1", "pages/auth/ForgotPasswordV1.tsx"),
    route("forgot-password-v2", "pages/auth/ForgotPasswordV2.tsx"),
    route("forgot-password-v3", "pages/auth/ForgotPasswordV3.tsx"),
    route("reset-password-v1", "pages/auth/ResetPasswordV1.tsx"),
    route("reset-password-v2", "pages/auth/ResetPasswordV2.tsx"),
    route("reset-password-v3", "pages/auth/ResetPasswordV3.tsx"),
  ]),

  ...prefix("errors", [
    route("401-v1", "pages/errors/Error401V1.tsx"),
    route("401-v2", "pages/errors/Error401V2.tsx"),
    route("401-v3", "pages/errors/Error401V3.tsx"),
    route("403-v1", "pages/errors/Error403V1.tsx"),
    route("403-v2", "pages/errors/Error403V2.tsx"),
    route("403-v3", "pages/errors/Error403V3.tsx"),
    route("404-v1", "pages/errors/Error404V1.tsx"),
    route("404-v2", "pages/errors/Error404V2.tsx"),
    route("404-v3", "pages/errors/Error404V3.tsx"),
    route("500-v1", "pages/errors/Error500V1.tsx"),
    route("500-v2", "pages/errors/Error500V2.tsx"),
    route("500-v3", "pages/errors/Error500V3.tsx"),
  ]),

  layout("routes/app-layout.tsx", [
    route("dashboard", "pages/DashboardPage.tsx"),
    route("users", "features/users/userPage.tsx"),
    route("roles", "features/roles/rolePage.tsx"),
    route("organizations", "features/organizations/organizationPage.tsx"),
    route("workspace", "pages/WorkspacePage.tsx"),
    route("projects", "features/projects/projectPage.tsx"),
    route("permissions", "features/permissions/permissionPage.tsx"),
    route("resources", "features/resources/resourcePage.tsx"),
    route("endpoints", "features/endpoints/endpointPage.tsx"),
    route("roles-permissions", "pages/RolesPermissionsPage.tsx"),
    route("audit-logs", "features/audit-logs/auditLogPage.tsx"),
    route("system-health", "pages/SystemHealthPage.tsx"),
    route("system-insights", "pages/SystemInsightsPage.tsx"),
    route("uploads", "pages/UploadsPage.tsx"),
    route("settings", "pages/SettingsPage.tsx"),
    route("design-system", "pages/DesignSystemPage.tsx"),
    route("components", "pages/ComponentShowcasePage.tsx"),

    ...prefix("components", [
      route("buttons", "pages/showcase/ShowcaseButtons.tsx"),
      route("badges", "pages/showcase/ShowcaseBadges.tsx"),
      route("forms", "pages/showcase/ShowcaseForms.tsx"),
      route("cards", "pages/showcase/ShowcaseCards.tsx"),
      route("feedback", "pages/showcase/ShowcaseFeedback.tsx"),
      route("data-display", "pages/showcase/ShowcaseDataDisplay.tsx"),
      route("overlays", "pages/showcase/ShowcaseOverlays.tsx"),
      route("navigation", "pages/showcase/ShowcaseNavigation.tsx"),
      route("charts", "pages/showcase/ShowcaseCharts.tsx"),
      route("realtime", "pages/showcase/ShowcaseRealtime.tsx"),
    ]),

    route("auth-showcase", "pages/auth/AuthShowcasePage.tsx"),
    route("error-showcase", "pages/errors/ErrorShowcasePage.tsx"),
  ]),

  route("*", "pages/NotFound.tsx"),
] satisfies RouteConfig;
