// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Roisfaozi/go-clean-boilerplate/internal/modules/role/model"
	"github.com/Roisfaozi/go-clean-boilerplate/pkg/querybuilder"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRoleUseCase creates a new instance of MockRoleUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRoleUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRoleUseCase {
	m := &MockRoleUseCase{}
	m.Mock.Test(t)

	t.Cleanup(func() { m.AssertExpectations(t) })

	return m
}

// MockRoleUseCase is an autogenerated mock type for the RoleUseCase type
type MockRoleUseCase struct {
	mock.Mock
}

type MockRoleUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRoleUseCase) EXPECT() *MockRoleUseCase_Expecter {
	return &MockRoleUseCase_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockRoleUseCase
func (_mock *MockRoleUseCase) Create(ctx context.Context, request *model.CreateRoleRequest) (*model.RoleResponse, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.RoleResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.CreateRoleRequest) (*model.RoleResponse, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.CreateRoleRequest) *model.RoleResponse); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.RoleResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.CreateRoleRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRoleUseCase_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRoleUseCase_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - request *model.CreateRoleRequest
func (_e *MockRoleUseCase_Expecter) Create(ctx interface{}, request interface{}) *MockRoleUseCase_Create_Call {
	return &MockRoleUseCase_Create_Call{Call: _e.mock.On("Create", ctx, request)}
}

func (_c *MockRoleUseCase_Create_Call) Run(run func(ctx context.Context, request *model.CreateRoleRequest)) *MockRoleUseCase_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.CreateRoleRequest
		if args[1] != nil {
			arg1 = args[1].(*model.CreateRoleRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRoleUseCase_Create_Call) Return(roleResponse *model.RoleResponse, err error) *MockRoleUseCase_Create_Call {
	_c.Call.Return(roleResponse, err)
	return _c
}

func (_c *MockRoleUseCase_Create_Call) RunAndReturn(run func(ctx context.Context, request *model.CreateRoleRequest) (*model.RoleResponse, error)) *MockRoleUseCase_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockRoleUseCase
func (_mock *MockRoleUseCase) Delete(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRoleUseCase_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockRoleUseCase_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockRoleUseCase_Expecter) Delete(ctx interface{}, id interface{}) *MockRoleUseCase_Delete_Call {
	return &MockRoleUseCase_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockRoleUseCase_Delete_Call) Run(run func(ctx context.Context, id string)) *MockRoleUseCase_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRoleUseCase_Delete_Call) Return(err error) *MockRoleUseCase_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRoleUseCase_Delete_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockRoleUseCase_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function for the type MockRoleUseCase
func (_mock *MockRoleUseCase) GetAll(ctx context.Context) ([]model.RoleResponse, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []model.RoleResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]model.RoleResponse, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []model.RoleResponse); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.RoleResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRoleUseCase_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockRoleUseCase_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRoleUseCase_Expecter) GetAll(ctx interface{}) *MockRoleUseCase_GetAll_Call {
	return &MockRoleUseCase_GetAll_Call{Call: _e.mock.On("GetAll", ctx)}
}

func (_c *MockRoleUseCase_GetAll_Call) Run(run func(ctx context.Context)) *MockRoleUseCase_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRoleUseCase_GetAll_Call) Return(roleResponses []model.RoleResponse, err error) *MockRoleUseCase_GetAll_Call {
	_c.Call.Return(roleResponses, err)
	return _c
}

func (_c *MockRoleUseCase_GetAll_Call) RunAndReturn(run func(ctx context.Context) ([]model.RoleResponse, error)) *MockRoleUseCase_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllRolesDynamic provides a mock function for the type MockRoleUseCase
func (_mock *MockRoleUseCase) GetAllRolesDynamic(ctx context.Context, filter *querybuilder.DynamicFilter) ([]model.RoleResponse, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetAllRolesDynamic")
	}

	var r0 []model.RoleResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *querybuilder.DynamicFilter) ([]model.RoleResponse, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *querybuilder.DynamicFilter) []model.RoleResponse); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.RoleResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *querybuilder.DynamicFilter) error); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRoleUseCase_GetAllRolesDynamic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllRolesDynamic'
type MockRoleUseCase_GetAllRolesDynamic_Call struct {
	*mock.Call
}

// GetAllRolesDynamic is a helper method to define mock.On call
//   - ctx context.Context
//   - filter *querybuilder.DynamicFilter
func (_e *MockRoleUseCase_Expecter) GetAllRolesDynamic(ctx interface{}, filter interface{}) *MockRoleUseCase_GetAllRolesDynamic_Call {
	return &MockRoleUseCase_GetAllRolesDynamic_Call{Call: _e.mock.On("GetAllRolesDynamic", ctx, filter)}
}

func (_c *MockRoleUseCase_GetAllRolesDynamic_Call) Run(run func(ctx context.Context, filter *querybuilder.DynamicFilter)) *MockRoleUseCase_GetAllRolesDynamic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *querybuilder.DynamicFilter
		if args[1] != nil {
			arg1 = args[1].(*querybuilder.DynamicFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRoleUseCase_GetAllRolesDynamic_Call) Return(roleResponses []model.RoleResponse, err error) *MockRoleUseCase_GetAllRolesDynamic_Call {
	_c.Call.Return(roleResponses, err)
	return _c
}

func (_c *MockRoleUseCase_GetAllRolesDynamic_Call) RunAndReturn(run func(ctx context.Context, filter *querybuilder.DynamicFilter) ([]model.RoleResponse, error)) *MockRoleUseCase_GetAllRolesDynamic_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockRoleUseCase
func (_mock *MockRoleUseCase) Update(ctx context.Context, id string, request *model.UpdateRoleRequest) (*model.RoleResponse, error) {
	ret := _mock.Called(ctx, id, request)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *model.RoleResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *model.UpdateRoleRequest) (*model.RoleResponse, error)); ok {
		return returnFunc(ctx, id, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *model.UpdateRoleRequest) *model.RoleResponse); ok {
		r0 = returnFunc(ctx, id, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.RoleResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *model.UpdateRoleRequest) error); ok {
		r1 = returnFunc(ctx, id, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRoleUseCase_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockRoleUseCase_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - request *model.UpdateRoleRequest
func (_e *MockRoleUseCase_Expecter) Update(ctx interface{}, id interface{}, request interface{}) *MockRoleUseCase_Update_Call {
	return &MockRoleUseCase_Update_Call{Call: _e.mock.On("Update", ctx, id, request)}
}

func (_c *MockRoleUseCase_Update_Call) Run(run func(ctx context.Context, id string, request *model.UpdateRoleRequest)) *MockRoleUseCase_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *model.UpdateRoleRequest
		if args[2] != nil {
			arg2 = args[2].(*model.UpdateRoleRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRoleUseCase_Update_Call) Return(roleResponse *model.RoleResponse, err error) *MockRoleUseCase_Update_Call {
	_c.Call.Return(roleResponse, err)
	return _c
}

func (_c *MockRoleUseCase_Update_Call) RunAndReturn(run func(ctx context.Context, id string, request *model.UpdateRoleRequest) (*model.RoleResponse, error)) *MockRoleUseCase_Update_Call {
	_c.Call.Return(run)
	return _c
}
