// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Roisfaozi/go-clean-boilerplate/internal/modules/role/entity"
	"github.com/Roisfaozi/go-clean-boilerplate/pkg/querybuilder"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRoleRepository creates a new instance of MockRoleRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRoleRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRoleRepository {
	m := &MockRoleRepository{}
	m.Mock.Test(t)

	t.Cleanup(func() { m.AssertExpectations(t) })

	return m
}

// MockRoleRepository is an autogenerated mock type for the RoleRepository type
type MockRoleRepository struct {
	mock.Mock
}

type MockRoleRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRoleRepository) EXPECT() *MockRoleRepository_Expecter {
	return &MockRoleRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockRoleRepository
func (_mock *MockRoleRepository) Create(ctx context.Context, role *entity.Role) error {
	ret := _mock.Called(ctx, role)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Role) error); ok {
		r0 = returnFunc(ctx, role)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRoleRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRoleRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - role *entity.Role
func (_e *MockRoleRepository_Expecter) Create(ctx interface{}, role interface{}) *MockRoleRepository_Create_Call {
	return &MockRoleRepository_Create_Call{Call: _e.mock.On("Create", ctx, role)}
}

func (_c *MockRoleRepository_Create_Call) Run(run func(ctx context.Context, role *entity.Role)) *MockRoleRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Role
		if args[1] != nil {
			arg1 = args[1].(*entity.Role)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRoleRepository_Create_Call) Return(err error) *MockRoleRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRoleRepository_Create_Call) RunAndReturn(run func(ctx context.Context, role *entity.Role) error) *MockRoleRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockRoleRepository
func (_mock *MockRoleRepository) Delete(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRoleRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockRoleRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockRoleRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockRoleRepository_Delete_Call {
	return &MockRoleRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockRoleRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *MockRoleRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRoleRepository_Delete_Call) Return(err error) *MockRoleRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRoleRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockRoleRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function for the type MockRoleRepository
func (_mock *MockRoleRepository) FindAll(ctx context.Context) ([]*entity.Role, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []*entity.Role
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*entity.Role, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*entity.Role); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Role)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRoleRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockRoleRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRoleRepository_Expecter) FindAll(ctx interface{}) *MockRoleRepository_FindAll_Call {
	return &MockRoleRepository_FindAll_Call{Call: _e.mock.On("FindAll", ctx)}
}

func (_c *MockRoleRepository_FindAll_Call) Run(run func(ctx context.Context)) *MockRoleRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRoleRepository_FindAll_Call) Return(roles []*entity.Role, err error) *MockRoleRepository_FindAll_Call {
	_c.Call.Return(roles, err)
	return _c
}

func (_c *MockRoleRepository_FindAll_Call) RunAndReturn(run func(ctx context.Context) ([]*entity.Role, error)) *MockRoleRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllDynamic provides a mock function for the type MockRoleRepository
func (_mock *MockRoleRepository) FindAllDynamic(ctx context.Context, filter *querybuilder.DynamicFilter) ([]*entity.Role, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for FindAllDynamic")
	}

	var r0 []*entity.Role
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *querybuilder.DynamicFilter) ([]*entity.Role, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *querybuilder.DynamicFilter) []*entity.Role); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Role)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *querybuilder.DynamicFilter) error); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRoleRepository_FindAllDynamic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllDynamic'
type MockRoleRepository_FindAllDynamic_Call struct {
	*mock.Call
}

// FindAllDynamic is a helper method to define mock.On call
//   - ctx context.Context
//   - filter *querybuilder.DynamicFilter
func (_e *MockRoleRepository_Expecter) FindAllDynamic(ctx interface{}, filter interface{}) *MockRoleRepository_FindAllDynamic_Call {
	return &MockRoleRepository_FindAllDynamic_Call{Call: _e.mock.On("FindAllDynamic", ctx, filter)}
}

func (_c *MockRoleRepository_FindAllDynamic_Call) Run(run func(ctx context.Context, filter *querybuilder.DynamicFilter)) *MockRoleRepository_FindAllDynamic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *querybuilder.DynamicFilter
		if args[1] != nil {
			arg1 = args[1].(*querybuilder.DynamicFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRoleRepository_FindAllDynamic_Call) Return(roles []*entity.Role, err error) *MockRoleRepository_FindAllDynamic_Call {
	_c.Call.Return(roles, err)
	return _c
}

func (_c *MockRoleRepository_FindAllDynamic_Call) RunAndReturn(run func(ctx context.Context, filter *querybuilder.DynamicFilter) ([]*entity.Role, error)) *MockRoleRepository_FindAllDynamic_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockRoleRepository
func (_mock *MockRoleRepository) FindByID(ctx context.Context, id string) (*entity.Role, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entity.Role
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.Role, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.Role); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Role)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRoleRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockRoleRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockRoleRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockRoleRepository_FindByID_Call {
	return &MockRoleRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockRoleRepository_FindByID_Call) Run(run func(ctx context.Context, id string)) *MockRoleRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRoleRepository_FindByID_Call) Return(role *entity.Role, err error) *MockRoleRepository_FindByID_Call {
	_c.Call.Return(role, err)
	return _c
}

func (_c *MockRoleRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*entity.Role, error)) *MockRoleRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByName provides a mock function for the type MockRoleRepository
func (_mock *MockRoleRepository) FindByName(ctx context.Context, name string) (*entity.Role, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for FindByName")
	}

	var r0 *entity.Role
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.Role, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.Role); ok {
		r0 = returnFunc(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Role)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRoleRepository_FindByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByName'
type MockRoleRepository_FindByName_Call struct {
	*mock.Call
}

// FindByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockRoleRepository_Expecter) FindByName(ctx interface{}, name interface{}) *MockRoleRepository_FindByName_Call {
	return &MockRoleRepository_FindByName_Call{Call: _e.mock.On("FindByName", ctx, name)}
}

func (_c *MockRoleRepository_FindByName_Call) Run(run func(ctx context.Context, name string)) *MockRoleRepository_FindByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRoleRepository_FindByName_Call) Return(role *entity.Role, err error) *MockRoleRepository_FindByName_Call {
	_c.Call.Return(role, err)
	return _c
}

func (_c *MockRoleRepository_FindByName_Call) RunAndReturn(run func(ctx context.Context, name string) (*entity.Role, error)) *MockRoleRepository_FindByName_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockRoleRepository
func (_mock *MockRoleRepository) Update(ctx context.Context, role *entity.Role) error {
	ret := _mock.Called(ctx, role)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Role) error); ok {
		r0 = returnFunc(ctx, role)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRoleRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockRoleRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - role *entity.Role
func (_e *MockRoleRepository_Expecter) Update(ctx interface{}, role interface{}) *MockRoleRepository_Update_Call {
	return &MockRoleRepository_Update_Call{Call: _e.mock.On("Update", ctx, role)}
}

func (_c *MockRoleRepository_Update_Call) Run(run func(ctx context.Context, role *entity.Role)) *MockRoleRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Role
		if args[1] != nil {
			arg1 = args[1].(*entity.Role)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRoleRepository_Update_Call) Return(err error) *MockRoleRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRoleRepository_Update_Call) RunAndReturn(run func(ctx context.Context, role *entity.Role) error) *MockRoleRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
