// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocking

import (
	"context"

	"github.com/Roisfaozi/go-clean-boilerplate/internal/modules/audit/model"
	"github.com/Roisfaozi/go-clean-boilerplate/internal/worker/tasks"
	"github.com/hibiken/asynq"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTaskDistributor creates a new instance of MockTaskDistributor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTaskDistributor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTaskDistributor {
	m := &MockTaskDistributor{}
	m.Mock.Test(t)

	t.Cleanup(func() { m.Mock.AssertExpectations(t) })

	return m
}

// MockTaskDistributor is an autogenerated mock type for the TaskDistributor type
type MockTaskDistributor struct {
	mock.Mock
}

type MockTaskDistributor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTaskDistributor) EXPECT() *MockTaskDistributor_Expecter {
	return &MockTaskDistributor_Expecter{mock: &_m.Mock}
}

// DistributeTaskAuditLog provides a mock function for the type MockTaskDistributor
func (_mock *MockTaskDistributor) DistributeTaskAuditLog(ctx context.Context, payload model.CreateAuditLogRequest, opts ...asynq.Option) error {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Mock.Called(ctx, payload, opts)
	} else {
		tmpRet = _mock.Mock.Called(ctx, payload)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for DistributeTaskAuditLog")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.CreateAuditLogRequest, ...asynq.Option) error); ok {
		r0 = returnFunc(ctx, payload, opts...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTaskDistributor_DistributeTaskAuditLog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DistributeTaskAuditLog'
type MockTaskDistributor_DistributeTaskAuditLog_Call struct {
	*mock.Call
}

// DistributeTaskAuditLog is a helper method to define mock.On call
//   - ctx context.Context
//   - payload model.CreateAuditLogRequest
//   - opts ...asynq.Option
func (_e *MockTaskDistributor_Expecter) DistributeTaskAuditLog(ctx interface{}, payload interface{}, opts ...interface{}) *MockTaskDistributor_DistributeTaskAuditLog_Call {
	return &MockTaskDistributor_DistributeTaskAuditLog_Call{Call: _e.mock.On("DistributeTaskAuditLog",
		append([]interface{}{ctx, payload}, opts...)...)}
}

func (_c *MockTaskDistributor_DistributeTaskAuditLog_Call) Run(run func(ctx context.Context, payload model.CreateAuditLogRequest, opts ...asynq.Option)) *MockTaskDistributor_DistributeTaskAuditLog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.CreateAuditLogRequest
		if args[1] != nil {
			arg1 = args[1].(model.CreateAuditLogRequest)
		}
		var arg2 []asynq.Option
		var variadicArgs []asynq.Option
		if len(args) > 2 {
			variadicArgs = args[2].([]asynq.Option)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockTaskDistributor_DistributeTaskAuditLog_Call) Return(err error) *MockTaskDistributor_DistributeTaskAuditLog_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTaskDistributor_DistributeTaskAuditLog_Call) RunAndReturn(run func(ctx context.Context, payload model.CreateAuditLogRequest, opts ...asynq.Option) error) *MockTaskDistributor_DistributeTaskAuditLog_Call {
	_c.Call.Return(run)
	return _c
}

// DistributeTaskAuditLogExport provides a mock function for the type MockTaskDistributor
func (_mock *MockTaskDistributor) DistributeTaskAuditLogExport(ctx context.Context, payload model.AuditLogExportPayload, opts ...asynq.Option) error {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, payload, opts)
	} else {
		tmpRet = _mock.Called(ctx, payload)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for DistributeTaskAuditLogExport")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.AuditLogExportPayload, ...asynq.Option) error); ok {
		r0 = returnFunc(ctx, payload, opts...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTaskDistributor_DistributeTaskAuditLogExport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DistributeTaskAuditLogExport'
type MockTaskDistributor_DistributeTaskAuditLogExport_Call struct {
	*mock.Call
}

// DistributeTaskAuditLogExport is a helper method to define mock.On call
//   - ctx context.Context
//   - payload model.AuditLogExportPayload
//   - opts ...asynq.Option
func (_e *MockTaskDistributor_Expecter) DistributeTaskAuditLogExport(ctx interface{}, payload interface{}, opts ...interface{}) *MockTaskDistributor_DistributeTaskAuditLogExport_Call {
	return &MockTaskDistributor_DistributeTaskAuditLogExport_Call{Call: _e.mock.On("DistributeTaskAuditLogExport",
		append([]interface{}{ctx, payload}, opts...)...)}
}

func (_c *MockTaskDistributor_DistributeTaskAuditLogExport_Call) Run(run func(ctx context.Context, payload model.AuditLogExportPayload, opts ...asynq.Option)) *MockTaskDistributor_DistributeTaskAuditLogExport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.AuditLogExportPayload
		if args[1] != nil {
			arg1 = args[1].(model.AuditLogExportPayload)
		}
		var arg2 []asynq.Option
		var variadicArgs []asynq.Option
		if len(args) > 2 {
			variadicArgs = args[2].([]asynq.Option)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockTaskDistributor_DistributeTaskAuditLogExport_Call) Return(err error) *MockTaskDistributor_DistributeTaskAuditLogExport_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTaskDistributor_DistributeTaskAuditLogExport_Call) RunAndReturn(run func(ctx context.Context, payload model.AuditLogExportPayload, opts ...asynq.Option) error) *MockTaskDistributor_DistributeTaskAuditLogExport_Call {
	_c.Call.Return(run)
	return _c
}

// DistributeTaskAuditOutboxSync provides a mock function for the type MockTaskDistributor
func (_mock *MockTaskDistributor) DistributeTaskAuditOutboxSync(ctx context.Context, opts ...asynq.Option) error {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, opts)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for DistributeTaskAuditOutboxSync")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...asynq.Option) error); ok {
		r0 = returnFunc(ctx, opts...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTaskDistributor_DistributeTaskAuditOutboxSync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DistributeTaskAuditOutboxSync'
type MockTaskDistributor_DistributeTaskAuditOutboxSync_Call struct {
	*mock.Call
}

// DistributeTaskAuditOutboxSync is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...asynq.Option
func (_e *MockTaskDistributor_Expecter) DistributeTaskAuditOutboxSync(ctx interface{}, opts ...interface{}) *MockTaskDistributor_DistributeTaskAuditOutboxSync_Call {
	return &MockTaskDistributor_DistributeTaskAuditOutboxSync_Call{Call: _e.mock.On("DistributeTaskAuditOutboxSync",
		append([]interface{}{ctx}, opts...)...)}
}

func (_c *MockTaskDistributor_DistributeTaskAuditOutboxSync_Call) Run(run func(ctx context.Context, opts ...asynq.Option)) *MockTaskDistributor_DistributeTaskAuditOutboxSync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []asynq.Option
		var variadicArgs []asynq.Option
		if len(args) > 1 {
			variadicArgs = args[1].([]asynq.Option)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockTaskDistributor_DistributeTaskAuditOutboxSync_Call) Return(err error) *MockTaskDistributor_DistributeTaskAuditOutboxSync_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTaskDistributor_DistributeTaskAuditOutboxSync_Call) RunAndReturn(run func(ctx context.Context, opts ...asynq.Option) error) *MockTaskDistributor_DistributeTaskAuditOutboxSync_Call {
	_c.Call.Return(run)
	return _c
}

// DistributeTaskSendEmail provides a mock function for the type MockTaskDistributor
func (_mock *MockTaskDistributor) DistributeTaskSendEmail(ctx context.Context, payload *tasks.SendEmailPayload, opts ...asynq.Option) error {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, payload, opts)
	} else {
		tmpRet = _mock.Called(ctx, payload)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for DistributeTaskSendEmail")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *tasks.SendEmailPayload, ...asynq.Option) error); ok {
		r0 = returnFunc(ctx, payload, opts...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTaskDistributor_DistributeTaskSendEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DistributeTaskSendEmail'
type MockTaskDistributor_DistributeTaskSendEmail_Call struct {
	*mock.Call
}

// DistributeTaskSendEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - payload *tasks.SendEmailPayload
//   - opts ...asynq.Option
func (_e *MockTaskDistributor_Expecter) DistributeTaskSendEmail(ctx interface{}, payload interface{}, opts ...interface{}) *MockTaskDistributor_DistributeTaskSendEmail_Call {
	return &MockTaskDistributor_DistributeTaskSendEmail_Call{Call: _e.mock.On("DistributeTaskSendEmail",
		append([]interface{}{ctx, payload}, opts...)...)}
}

func (_c *MockTaskDistributor_DistributeTaskSendEmail_Call) Run(run func(ctx context.Context, payload *tasks.SendEmailPayload, opts ...asynq.Option)) *MockTaskDistributor_DistributeTaskSendEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *tasks.SendEmailPayload
		if args[1] != nil {
			arg1 = args[1].(*tasks.SendEmailPayload)
		}
		var arg2 []asynq.Option
		var variadicArgs []asynq.Option
		if len(args) > 2 {
			variadicArgs = args[2].([]asynq.Option)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockTaskDistributor_DistributeTaskSendEmail_Call) Return(err error) *MockTaskDistributor_DistributeTaskSendEmail_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTaskDistributor_DistributeTaskSendEmail_Call) RunAndReturn(run func(context.Context, *tasks.SendEmailPayload, ...asynq.Option) error) *MockTaskDistributor_DistributeTaskSendEmail_Call {
	_c.Call.Return(run)
	return _c
}

// DistributeTaskWebhookTrigger provides a mock function for the type MockTaskDistributor
func (_mock *MockTaskDistributor) DistributeTaskWebhookTrigger(ctx context.Context, payload tasks.WebhookTriggerPayload, opts ...asynq.Option) error {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, payload, opts)
	} else {
		tmpRet = _mock.Called(ctx, payload)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for DistributeTaskWebhookTrigger")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, tasks.WebhookTriggerPayload, ...asynq.Option) error); ok {
		r0 = returnFunc(ctx, payload, opts...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTaskDistributor_DistributeTaskWebhookTrigger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DistributeTaskWebhookTrigger'
type MockTaskDistributor_DistributeTaskWebhookTrigger_Call struct {
	*mock.Call
}

// DistributeTaskWebhookTrigger is a helper method to define mock.On call
//   - ctx context.Context
//   - payload tasks.WebhookTriggerPayload
//   - opts ...asynq.Option
func (_e *MockTaskDistributor_Expecter) DistributeTaskWebhookTrigger(ctx interface{}, payload interface{}, opts ...interface{}) *MockTaskDistributor_DistributeTaskWebhookTrigger_Call {
	return &MockTaskDistributor_DistributeTaskWebhookTrigger_Call{Call: _e.mock.On("DistributeTaskWebhookTrigger",
		append([]interface{}{ctx, payload}, opts...)...)}
}

func (_c *MockTaskDistributor_DistributeTaskWebhookTrigger_Call) Run(run func(ctx context.Context, payload tasks.WebhookTriggerPayload, opts ...asynq.Option)) *MockTaskDistributor_DistributeTaskWebhookTrigger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 tasks.WebhookTriggerPayload
		if args[1] != nil {
			arg1 = args[1].(tasks.WebhookTriggerPayload)
		}
		var arg2 []asynq.Option
		var variadicArgs []asynq.Option
		if len(args) > 2 {
			variadicArgs = args[2].([]asynq.Option)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockTaskDistributor_DistributeTaskWebhookTrigger_Call) Return(err error) *MockTaskDistributor_DistributeTaskWebhookTrigger_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTaskDistributor_DistributeTaskWebhookTrigger_Call) RunAndReturn(run func(ctx context.Context, payload tasks.WebhookTriggerPayload, opts ...asynq.Option) error) *MockTaskDistributor_DistributeTaskWebhookTrigger_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTaskProcessor creates a new instance of MockTaskProcessor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.

// The first argument is typically a *testing.T value.
func NewMockTaskProcessor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTaskProcessor {
	m := &MockTaskProcessor{}
	m.Mock.Test(t)

	t.Cleanup(func() { m.AssertExpectations(t) })

	return m
}

// MockTaskProcessor is an autogenerated mock type for the TaskProcessor type
type MockTaskProcessor struct {
	mock.Mock
}

type MockTaskProcessor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTaskProcessor) EXPECT() *MockTaskProcessor_Expecter {
	return &MockTaskProcessor_Expecter{mock: &_m.Mock}
}

// Shutdown provides a mock function for the type MockTaskProcessor
func (_mock *MockTaskProcessor) Shutdown() {
	_mock.Called()
	return
}

// MockTaskProcessor_Shutdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shutdown'
type MockTaskProcessor_Shutdown_Call struct {
	*mock.Call
}

// Shutdown is a helper method to define mock.On call
func (_e *MockTaskProcessor_Expecter) Shutdown() *MockTaskProcessor_Shutdown_Call {
	return &MockTaskProcessor_Shutdown_Call{Call: _e.mock.On("Shutdown")}
}

func (_c *MockTaskProcessor_Shutdown_Call) Run(run func()) *MockTaskProcessor_Shutdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTaskProcessor_Shutdown_Call) Return() *MockTaskProcessor_Shutdown_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockTaskProcessor_Shutdown_Call) RunAndReturn(run func()) *MockTaskProcessor_Shutdown_Call {
	_c.Run(run)
	return _c
}

// Start provides a mock function for the type MockTaskProcessor
func (_mock *MockTaskProcessor) Start() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTaskProcessor_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockTaskProcessor_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
func (_e *MockTaskProcessor_Expecter) Start() *MockTaskProcessor_Start_Call {
	return &MockTaskProcessor_Start_Call{Call: _e.mock.On("Start")}
}

func (_c *MockTaskProcessor_Start_Call) Run(run func()) *MockTaskProcessor_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTaskProcessor_Start_Call) Return(err error) *MockTaskProcessor_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTaskProcessor_Start_Call) RunAndReturn(run func() error) *MockTaskProcessor_Start_Call {
	_c.Call.Return(run)
	return _c
}
