// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocking

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockWithTransactionManager creates a new instance of MockWithTransactionManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWithTransactionManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWithTransactionManager {
	m := &MockWithTransactionManager{}
	m.Mock.Test(t)

	t.Cleanup(func() { m.AssertExpectations(t) })

	return m
}

// MockWithTransactionManager is an autogenerated mock type for the WithTransactionManager type
type MockWithTransactionManager struct {
	mock.Mock
}

type MockWithTransactionManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWithTransactionManager) EXPECT() *MockWithTransactionManager_Expecter {
	return &MockWithTransactionManager_Expecter{mock: &_m.Mock}
}

// WithinTransaction provides a mock function for the type MockWithTransactionManager
func (_mock *MockWithTransactionManager) WithinTransaction(ctx context.Context, fn func(ctx context.Context) error) error {
	ret := _mock.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for WithinTransaction")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, func(ctx context.Context) error) error); ok {
		r0 = returnFunc(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWithTransactionManager_WithinTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithinTransaction'
type MockWithTransactionManager_WithinTransaction_Call struct {
	*mock.Call
}

// WithinTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(ctx context.Context) error
func (_e *MockWithTransactionManager_Expecter) WithinTransaction(ctx interface{}, fn interface{}) *MockWithTransactionManager_WithinTransaction_Call {
	return &MockWithTransactionManager_WithinTransaction_Call{Call: _e.mock.On("WithinTransaction", ctx, fn)}
}

func (_c *MockWithTransactionManager_WithinTransaction_Call) Run(run func(ctx context.Context, fn func(ctx context.Context) error)) *MockWithTransactionManager_WithinTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func(ctx context.Context) error
		if args[1] != nil {
			arg1 = args[1].(func(ctx context.Context) error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWithTransactionManager_WithinTransaction_Call) Return(err error) *MockWithTransactionManager_WithinTransaction_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWithTransactionManager_WithinTransaction_Call) RunAndReturn(run func(ctx context.Context, fn func(ctx context.Context) error) error) *MockWithTransactionManager_WithinTransaction_Call {
	_c.Call.Return(run)
	return _c
}
