// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocking

import (
	"context"
	"time"

	"github.com/Roisfaozi/go-clean-boilerplate/pkg/ws"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPresenceManager creates a new instance of MockPresenceManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPresenceManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPresenceManager {
	m := &MockPresenceManager{}
	m.Mock.Test(t)

	t.Cleanup(func() { m.AssertExpectations(t) })

	return m
}

// MockPresenceManager is an autogenerated mock type for the PresenceManager type
type MockPresenceManager struct {
	mock.Mock
}

type MockPresenceManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPresenceManager) EXPECT() *MockPresenceManager_Expecter {
	return &MockPresenceManager_Expecter{mock: &_m.Mock}
}

// GetOnlineUsers provides a mock function for the type MockPresenceManager
func (_mock *MockPresenceManager) GetOnlineUsers(ctx context.Context, orgID string) ([]ws.PresenceUser, error) {
	ret := _mock.Called(ctx, orgID)

	if len(ret) == 0 {
		panic("no return value specified for GetOnlineUsers")
	}

	var r0 []ws.PresenceUser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]ws.PresenceUser, error)); ok {
		return returnFunc(ctx, orgID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []ws.PresenceUser); ok {
		r0 = returnFunc(ctx, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ws.PresenceUser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, orgID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPresenceManager_GetOnlineUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOnlineUsers'
type MockPresenceManager_GetOnlineUsers_Call struct {
	*mock.Call
}

// GetOnlineUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID string
func (_e *MockPresenceManager_Expecter) GetOnlineUsers(ctx interface{}, orgID interface{}) *MockPresenceManager_GetOnlineUsers_Call {
	return &MockPresenceManager_GetOnlineUsers_Call{Call: _e.mock.On("GetOnlineUsers", ctx, orgID)}
}

func (_c *MockPresenceManager_GetOnlineUsers_Call) Run(run func(ctx context.Context, orgID string)) *MockPresenceManager_GetOnlineUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPresenceManager_GetOnlineUsers_Call) Return(presenceUsers []ws.PresenceUser, err error) *MockPresenceManager_GetOnlineUsers_Call {
	_c.Call.Return(presenceUsers, err)
	return _c
}

func (_c *MockPresenceManager_GetOnlineUsers_Call) RunAndReturn(run func(ctx context.Context, orgID string) ([]ws.PresenceUser, error)) *MockPresenceManager_GetOnlineUsers_Call {
	_c.Call.Return(run)
	return _c
}

// PruneStaleUsers provides a mock function for the type MockPresenceManager
func (_mock *MockPresenceManager) PruneStaleUsers(ctx context.Context, timeout time.Duration) (map[string][]string, error) {
	ret := _mock.Called(ctx, timeout)

	if len(ret) == 0 {
		panic("no return value specified for PruneStaleUsers")
	}

	var r0 map[string][]string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Duration) (map[string][]string, error)); ok {
		return returnFunc(ctx, timeout)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Duration) map[string][]string); ok {
		r0 = returnFunc(ctx, timeout)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string][]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Duration) error); ok {
		r1 = returnFunc(ctx, timeout)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPresenceManager_PruneStaleUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PruneStaleUsers'
type MockPresenceManager_PruneStaleUsers_Call struct {
	*mock.Call
}

// PruneStaleUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - timeout time.Duration
func (_e *MockPresenceManager_Expecter) PruneStaleUsers(ctx interface{}, timeout interface{}) *MockPresenceManager_PruneStaleUsers_Call {
	return &MockPresenceManager_PruneStaleUsers_Call{Call: _e.mock.On("PruneStaleUsers", ctx, timeout)}
}

func (_c *MockPresenceManager_PruneStaleUsers_Call) Run(run func(ctx context.Context, timeout time.Duration)) *MockPresenceManager_PruneStaleUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Duration
		if args[1] != nil {
			arg1 = args[1].(time.Duration)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPresenceManager_PruneStaleUsers_Call) Return(stringToStrings map[string][]string, err error) *MockPresenceManager_PruneStaleUsers_Call {
	_c.Call.Return(stringToStrings, err)
	return _c
}

func (_c *MockPresenceManager_PruneStaleUsers_Call) RunAndReturn(run func(ctx context.Context, timeout time.Duration) (map[string][]string, error)) *MockPresenceManager_PruneStaleUsers_Call {
	_c.Call.Return(run)
	return _c
}

// RefreshUserHeartbeat provides a mock function for the type MockPresenceManager
func (_mock *MockPresenceManager) RefreshUserHeartbeat(ctx context.Context, orgID string, userID string) error {
	ret := _mock.Called(ctx, orgID, userID)

	if len(ret) == 0 {
		panic("no return value specified for RefreshUserHeartbeat")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, orgID, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPresenceManager_RefreshUserHeartbeat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshUserHeartbeat'
type MockPresenceManager_RefreshUserHeartbeat_Call struct {
	*mock.Call
}

// RefreshUserHeartbeat is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID string
//   - userID string
func (_e *MockPresenceManager_Expecter) RefreshUserHeartbeat(ctx interface{}, orgID interface{}, userID interface{}) *MockPresenceManager_RefreshUserHeartbeat_Call {
	return &MockPresenceManager_RefreshUserHeartbeat_Call{Call: _e.mock.On("RefreshUserHeartbeat", ctx, orgID, userID)}
}

func (_c *MockPresenceManager_RefreshUserHeartbeat_Call) Run(run func(ctx context.Context, orgID string, userID string)) *MockPresenceManager_RefreshUserHeartbeat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPresenceManager_RefreshUserHeartbeat_Call) Return(err error) *MockPresenceManager_RefreshUserHeartbeat_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPresenceManager_RefreshUserHeartbeat_Call) RunAndReturn(run func(ctx context.Context, orgID string, userID string) error) *MockPresenceManager_RefreshUserHeartbeat_Call {
	_c.Call.Return(run)
	return _c
}

// SetUserOffline provides a mock function for the type MockPresenceManager
func (_mock *MockPresenceManager) SetUserOffline(ctx context.Context, orgID string, userID string) error {
	ret := _mock.Called(ctx, orgID, userID)

	if len(ret) == 0 {
		panic("no return value specified for SetUserOffline")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, orgID, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPresenceManager_SetUserOffline_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetUserOffline'
type MockPresenceManager_SetUserOffline_Call struct {
	*mock.Call
}

// SetUserOffline is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID string
//   - userID string
func (_e *MockPresenceManager_Expecter) SetUserOffline(ctx interface{}, orgID interface{}, userID interface{}) *MockPresenceManager_SetUserOffline_Call {
	return &MockPresenceManager_SetUserOffline_Call{Call: _e.mock.On("SetUserOffline", ctx, orgID, userID)}
}

func (_c *MockPresenceManager_SetUserOffline_Call) Run(run func(ctx context.Context, orgID string, userID string)) *MockPresenceManager_SetUserOffline_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPresenceManager_SetUserOffline_Call) Return(err error) *MockPresenceManager_SetUserOffline_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPresenceManager_SetUserOffline_Call) RunAndReturn(run func(ctx context.Context, orgID string, userID string) error) *MockPresenceManager_SetUserOffline_Call {
	_c.Call.Return(run)
	return _c
}

// SetUserOnline provides a mock function for the type MockPresenceManager
func (_mock *MockPresenceManager) SetUserOnline(ctx context.Context, orgID string, userID string, userData *ws.PresenceUser) error {
	ret := _mock.Called(ctx, orgID, userID, userData)

	if len(ret) == 0 {
		panic("no return value specified for SetUserOnline")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *ws.PresenceUser) error); ok {
		r0 = returnFunc(ctx, orgID, userID, userData)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPresenceManager_SetUserOnline_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetUserOnline'
type MockPresenceManager_SetUserOnline_Call struct {
	*mock.Call
}

// SetUserOnline is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID string
//   - userID string
//   - userData *ws.PresenceUser
func (_e *MockPresenceManager_Expecter) SetUserOnline(ctx interface{}, orgID interface{}, userID interface{}, userData interface{}) *MockPresenceManager_SetUserOnline_Call {
	return &MockPresenceManager_SetUserOnline_Call{Call: _e.mock.On("SetUserOnline", ctx, orgID, userID, userData)}
}

func (_c *MockPresenceManager_SetUserOnline_Call) Run(run func(ctx context.Context, orgID string, userID string, userData *ws.PresenceUser)) *MockPresenceManager_SetUserOnline_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *ws.PresenceUser
		if args[3] != nil {
			arg3 = args[3].(*ws.PresenceUser)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockPresenceManager_SetUserOnline_Call) Return(err error) *MockPresenceManager_SetUserOnline_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPresenceManager_SetUserOnline_Call) RunAndReturn(run func(ctx context.Context, orgID string, userID string, userData *ws.PresenceUser) error) *MockPresenceManager_SetUserOnline_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTicketManager creates a new instance of MockTicketManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTicketManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTicketManager {
	m := &MockTicketManager{}
	m.Mock.Test(t)

	t.Cleanup(func() { m.AssertExpectations(t) })

	return m
}

// MockTicketManager is an autogenerated mock type for the TicketManager type
type MockTicketManager struct {
	mock.Mock
}

type MockTicketManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTicketManager) EXPECT() *MockTicketManager_Expecter {
	return &MockTicketManager_Expecter{mock: &_m.Mock}
}

// CreateTicket provides a mock function for the type MockTicketManager
func (_mock *MockTicketManager) CreateTicket(ctx context.Context, userID string, orgID string, sessionID string, role string, username string) (string, error) {
	ret := _mock.Called(ctx, userID, orgID, sessionID, role, username)

	if len(ret) == 0 {
		panic("no return value specified for CreateTicket")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string, string) (string, error)); ok {
		return returnFunc(ctx, userID, orgID, sessionID, role, username)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string, string) string); ok {
		r0 = returnFunc(ctx, userID, orgID, sessionID, role, username)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, string, string) error); ok {
		r1 = returnFunc(ctx, userID, orgID, sessionID, role, username)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTicketManager_CreateTicket_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTicket'
type MockTicketManager_CreateTicket_Call struct {
	*mock.Call
}

// CreateTicket is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - orgID string
//   - sessionID string
//   - role string
//   - username string
func (_e *MockTicketManager_Expecter) CreateTicket(ctx interface{}, userID interface{}, orgID interface{}, sessionID interface{}, role interface{}, username interface{}) *MockTicketManager_CreateTicket_Call {
	return &MockTicketManager_CreateTicket_Call{Call: _e.mock.On("CreateTicket", ctx, userID, orgID, sessionID, role, username)}
}

func (_c *MockTicketManager_CreateTicket_Call) Run(run func(ctx context.Context, userID string, orgID string, sessionID string, role string, username string)) *MockTicketManager_CreateTicket_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockTicketManager_CreateTicket_Call) Return(s string, err error) *MockTicketManager_CreateTicket_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockTicketManager_CreateTicket_Call) RunAndReturn(run func(ctx context.Context, userID string, orgID string, sessionID string, role string, username string) (string, error)) *MockTicketManager_CreateTicket_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateTicket provides a mock function for the type MockTicketManager
func (_mock *MockTicketManager) ValidateTicket(ctx context.Context, ticket string) (*ws.UserContext, error) {
	ret := _mock.Called(ctx, ticket)

	if len(ret) == 0 {
		panic("no return value specified for ValidateTicket")
	}

	var r0 *ws.UserContext
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*ws.UserContext, error)); ok {
		return returnFunc(ctx, ticket)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *ws.UserContext); ok {
		r0 = returnFunc(ctx, ticket)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ws.UserContext)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, ticket)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTicketManager_ValidateTicket_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateTicket'
type MockTicketManager_ValidateTicket_Call struct {
	*mock.Call
}

// ValidateTicket is a helper method to define mock.On call
//   - ctx context.Context
//   - ticket string
func (_e *MockTicketManager_Expecter) ValidateTicket(ctx interface{}, ticket interface{}) *MockTicketManager_ValidateTicket_Call {
	return &MockTicketManager_ValidateTicket_Call{Call: _e.mock.On("ValidateTicket", ctx, ticket)}
}

func (_c *MockTicketManager_ValidateTicket_Call) Run(run func(ctx context.Context, ticket string)) *MockTicketManager_ValidateTicket_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTicketManager_ValidateTicket_Call) Return(userContext *ws.UserContext, err error) *MockTicketManager_ValidateTicket_Call {
	_c.Call.Return(userContext, err)
	return _c
}

func (_c *MockTicketManager_ValidateTicket_Call) RunAndReturn(run func(ctx context.Context, ticket string) (*ws.UserContext, error)) *MockTicketManager_ValidateTicket_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCasbinEnforcer creates a new instance of MockCasbinEnforcer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCasbinEnforcer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCasbinEnforcer {
	m := &MockCasbinEnforcer{}
	m.Mock.Test(t)

	t.Cleanup(func() { m.AssertExpectations(t) })

	return m
}

// MockCasbinEnforcer is an autogenerated mock type for the CasbinEnforcer type
type MockCasbinEnforcer struct {
	mock.Mock
}

type MockCasbinEnforcer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCasbinEnforcer) EXPECT() *MockCasbinEnforcer_Expecter {
	return &MockCasbinEnforcer_Expecter{mock: &_m.Mock}
}

// GetRolesForUser provides a mock function for the type MockCasbinEnforcer
func (_mock *MockCasbinEnforcer) GetRolesForUser(name string, domain ...string) ([]string, error) {
	var tmpRet mock.Arguments
	if len(domain) > 0 {
		tmpRet = _mock.Called(name, domain)
	} else {
		tmpRet = _mock.Called(name)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetRolesForUser")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, ...string) ([]string, error)); ok {
		return returnFunc(name, domain...)
	}
	if returnFunc, ok := ret.Get(0).(func(string, ...string) []string); ok {
		r0 = returnFunc(name, domain...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, ...string) error); ok {
		r1 = returnFunc(name, domain...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCasbinEnforcer_GetRolesForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRolesForUser'
type MockCasbinEnforcer_GetRolesForUser_Call struct {
	*mock.Call
}

// GetRolesForUser is a helper method to define mock.On call
//   - name string
//   - domain ...string
func (_e *MockCasbinEnforcer_Expecter) GetRolesForUser(name interface{}, domain ...interface{}) *MockCasbinEnforcer_GetRolesForUser_Call {
	return &MockCasbinEnforcer_GetRolesForUser_Call{Call: _e.mock.On("GetRolesForUser",
		append([]interface{}{name}, domain...)...)}
}

func (_c *MockCasbinEnforcer_GetRolesForUser_Call) Run(run func(name string, domain ...string)) *MockCasbinEnforcer_GetRolesForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []string
		var variadicArgs []string
		if len(args) > 1 {
			variadicArgs = args[1].([]string)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockCasbinEnforcer_GetRolesForUser_Call) Return(strings []string, err error) *MockCasbinEnforcer_GetRolesForUser_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockCasbinEnforcer_GetRolesForUser_Call) RunAndReturn(run func(name string, domain ...string) ([]string, error)) *MockCasbinEnforcer_GetRolesForUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockManager creates a new instance of MockManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockManager {
	m := &MockManager{}
	m.Mock.Test(t)

	t.Cleanup(func() { m.AssertExpectations(t) })

	return m
}

// MockManager is an autogenerated mock type for the Manager type
type MockManager struct {
	mock.Mock
}

type MockManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockManager) EXPECT() *MockManager_Expecter {
	return &MockManager_Expecter{mock: &_m.Mock}
}

// BroadcastToChannel provides a mock function for the type MockManager
func (_mock *MockManager) BroadcastToChannel(channel string, message []byte) {
	_mock.Called(channel, message)
	return
}

// MockManager_BroadcastToChannel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BroadcastToChannel'
type MockManager_BroadcastToChannel_Call struct {
	*mock.Call
}

// BroadcastToChannel is a helper method to define mock.On call
//   - channel string
//   - message []byte
func (_e *MockManager_Expecter) BroadcastToChannel(channel interface{}, message interface{}) *MockManager_BroadcastToChannel_Call {
	return &MockManager_BroadcastToChannel_Call{Call: _e.mock.On("BroadcastToChannel", channel, message)}
}

func (_c *MockManager_BroadcastToChannel_Call) Run(run func(channel string, message []byte)) *MockManager_BroadcastToChannel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockManager_BroadcastToChannel_Call) Return() *MockManager_BroadcastToChannel_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockManager_BroadcastToChannel_Call) RunAndReturn(run func(channel string, message []byte)) *MockManager_BroadcastToChannel_Call {
	_c.Run(run)
	return _c
}

// GetChannelClients provides a mock function for the type MockManager
func (_mock *MockManager) GetChannelClients(channel string) int {
	ret := _mock.Called(channel)

	if len(ret) == 0 {
		panic("no return value specified for GetChannelClients")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func(string) int); ok {
		r0 = returnFunc(channel)
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockManager_GetChannelClients_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChannelClients'
type MockManager_GetChannelClients_Call struct {
	*mock.Call
}

// GetChannelClients is a helper method to define mock.On call
//   - channel string
func (_e *MockManager_Expecter) GetChannelClients(channel interface{}) *MockManager_GetChannelClients_Call {
	return &MockManager_GetChannelClients_Call{Call: _e.mock.On("GetChannelClients", channel)}
}

func (_c *MockManager_GetChannelClients_Call) Run(run func(channel string)) *MockManager_GetChannelClients_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockManager_GetChannelClients_Call) Return(n int) *MockManager_GetChannelClients_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockManager_GetChannelClients_Call) RunAndReturn(run func(channel string) int) *MockManager_GetChannelClients_Call {
	_c.Call.Return(run)
	return _c
}

// GetPresenceManager provides a mock function for the type MockManager
func (_mock *MockManager) GetPresenceManager() ws.PresenceManager {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPresenceManager")
	}

	var r0 ws.PresenceManager
	if returnFunc, ok := ret.Get(0).(func() ws.PresenceManager); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ws.PresenceManager)
		}
	}
	return r0
}

// MockManager_GetPresenceManager_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPresenceManager'
type MockManager_GetPresenceManager_Call struct {
	*mock.Call
}

// GetPresenceManager is a helper method to define mock.On call
func (_e *MockManager_Expecter) GetPresenceManager() *MockManager_GetPresenceManager_Call {
	return &MockManager_GetPresenceManager_Call{Call: _e.mock.On("GetPresenceManager")}
}

func (_c *MockManager_GetPresenceManager_Call) Run(run func()) *MockManager_GetPresenceManager_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockManager_GetPresenceManager_Call) Return(presenceManager ws.PresenceManager) *MockManager_GetPresenceManager_Call {
	_c.Call.Return(presenceManager)
	return _c
}

func (_c *MockManager_GetPresenceManager_Call) RunAndReturn(run func() ws.PresenceManager) *MockManager_GetPresenceManager_Call {
	_c.Call.Return(run)
	return _c
}

// PresenceUpdate provides a mock function for the type MockManager
func (_mock *MockManager) PresenceUpdate(orgID string, event string, userData *ws.PresenceUser) {
	_mock.Called(orgID, event, userData)
	return
}

// MockManager_PresenceUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PresenceUpdate'
type MockManager_PresenceUpdate_Call struct {
	*mock.Call
}

// PresenceUpdate is a helper method to define mock.On call
//   - orgID string
//   - event string
//   - userData *ws.PresenceUser
func (_e *MockManager_Expecter) PresenceUpdate(orgID interface{}, event interface{}, userData interface{}) *MockManager_PresenceUpdate_Call {
	return &MockManager_PresenceUpdate_Call{Call: _e.mock.On("PresenceUpdate", orgID, event, userData)}
}

func (_c *MockManager_PresenceUpdate_Call) Run(run func(orgID string, event string, userData *ws.PresenceUser)) *MockManager_PresenceUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *ws.PresenceUser
		if args[2] != nil {
			arg2 = args[2].(*ws.PresenceUser)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockManager_PresenceUpdate_Call) Return() *MockManager_PresenceUpdate_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockManager_PresenceUpdate_Call) RunAndReturn(run func(orgID string, event string, userData *ws.PresenceUser)) *MockManager_PresenceUpdate_Call {
	_c.Run(run)
	return _c
}

// RegisterClient provides a mock function for the type MockManager
func (_mock *MockManager) RegisterClient(client *ws.Client) {
	_mock.Called(client)
	return
}

// MockManager_RegisterClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterClient'
type MockManager_RegisterClient_Call struct {
	*mock.Call
}

// RegisterClient is a helper method to define mock.On call
//   - client *ws.Client
func (_e *MockManager_Expecter) RegisterClient(client interface{}) *MockManager_RegisterClient_Call {
	return &MockManager_RegisterClient_Call{Call: _e.mock.On("RegisterClient", client)}
}

func (_c *MockManager_RegisterClient_Call) Run(run func(client *ws.Client)) *MockManager_RegisterClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *ws.Client
		if args[0] != nil {
			arg0 = args[0].(*ws.Client)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockManager_RegisterClient_Call) Return() *MockManager_RegisterClient_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockManager_RegisterClient_Call) RunAndReturn(run func(client *ws.Client)) *MockManager_RegisterClient_Call {
	_c.Run(run)
	return _c
}

// Run provides a mock function for the type MockManager
func (_mock *MockManager) Run() {
	_mock.Called()
	return
}

// MockManager_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockManager_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
func (_e *MockManager_Expecter) Run() *MockManager_Run_Call {
	return &MockManager_Run_Call{Call: _e.mock.On("Run")}
}

func (_c *MockManager_Run_Call) Run(run func()) *MockManager_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockManager_Run_Call) Return() *MockManager_Run_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockManager_Run_Call) RunAndReturn(run func()) *MockManager_Run_Call {
	_c.Run(run)
	return _c
}

// SubscribeToChannel provides a mock function for the type MockManager
func (_mock *MockManager) SubscribeToChannel(client *ws.Client, channel string) {
	_mock.Called(client, channel)
	return
}

// MockManager_SubscribeToChannel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubscribeToChannel'
type MockManager_SubscribeToChannel_Call struct {
	*mock.Call
}

// SubscribeToChannel is a helper method to define mock.On call
//   - client *ws.Client
//   - channel string
func (_e *MockManager_Expecter) SubscribeToChannel(client interface{}, channel interface{}) *MockManager_SubscribeToChannel_Call {
	return &MockManager_SubscribeToChannel_Call{Call: _e.mock.On("SubscribeToChannel", client, channel)}
}

func (_c *MockManager_SubscribeToChannel_Call) Run(run func(client *ws.Client, channel string)) *MockManager_SubscribeToChannel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *ws.Client
		if args[0] != nil {
			arg0 = args[0].(*ws.Client)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockManager_SubscribeToChannel_Call) Return() *MockManager_SubscribeToChannel_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockManager_SubscribeToChannel_Call) RunAndReturn(run func(client *ws.Client, channel string)) *MockManager_SubscribeToChannel_Call {
	_c.Run(run)
	return _c
}

// UnregisterClient provides a mock function for the type MockManager
func (_mock *MockManager) UnregisterClient(client *ws.Client) {
	_mock.Called(client)
	return
}

// MockManager_UnregisterClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnregisterClient'
type MockManager_UnregisterClient_Call struct {
	*mock.Call
}

// UnregisterClient is a helper method to define mock.On call
//   - client *ws.Client
func (_e *MockManager_Expecter) UnregisterClient(client interface{}) *MockManager_UnregisterClient_Call {
	return &MockManager_UnregisterClient_Call{Call: _e.mock.On("UnregisterClient", client)}
}

func (_c *MockManager_UnregisterClient_Call) Run(run func(client *ws.Client)) *MockManager_UnregisterClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *ws.Client
		if args[0] != nil {
			arg0 = args[0].(*ws.Client)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockManager_UnregisterClient_Call) Return() *MockManager_UnregisterClient_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockManager_UnregisterClient_Call) RunAndReturn(run func(client *ws.Client)) *MockManager_UnregisterClient_Call {
	_c.Run(run)
	return _c
}

// UnsubscribeFromChannel provides a mock function for the type MockManager
func (_mock *MockManager) UnsubscribeFromChannel(client *ws.Client, channel string) {
	_mock.Called(client, channel)
	return
}

// MockManager_UnsubscribeFromChannel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnsubscribeFromChannel'
type MockManager_UnsubscribeFromChannel_Call struct {
	*mock.Call
}

// UnsubscribeFromChannel is a helper method to define mock.On call
//   - client *ws.Client
//   - channel string
func (_e *MockManager_Expecter) UnsubscribeFromChannel(client interface{}, channel interface{}) *MockManager_UnsubscribeFromChannel_Call {
	return &MockManager_UnsubscribeFromChannel_Call{Call: _e.mock.On("UnsubscribeFromChannel", client, channel)}
}

func (_c *MockManager_UnsubscribeFromChannel_Call) Run(run func(client *ws.Client, channel string)) *MockManager_UnsubscribeFromChannel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *ws.Client
		if args[0] != nil {
			arg0 = args[0].(*ws.Client)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockManager_UnsubscribeFromChannel_Call) Return() *MockManager_UnsubscribeFromChannel_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockManager_UnsubscribeFromChannel_Call) RunAndReturn(run func(client *ws.Client, channel string)) *MockManager_UnsubscribeFromChannel_Call {
	_c.Run(run)
	return _c
}
