// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"io"

	"github.com/Roisfaozi/go-clean-boilerplate/internal/modules/user/model"
	"github.com/Roisfaozi/go-clean-boilerplate/pkg/querybuilder"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUserUseCase creates a new instance of MockUserUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserUseCase {
	m := &MockUserUseCase{}
	m.Mock.Test(t)

	t.Cleanup(func() { m.AssertExpectations(t) })

	return m
}

// MockUserUseCase is an autogenerated mock type for the UserUseCase type
type MockUserUseCase struct {
	mock.Mock
}

type MockUserUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserUseCase) EXPECT() *MockUserUseCase_Expecter {
	return &MockUserUseCase_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockUserUseCase
func (_mock *MockUserUseCase) Create(ctx context.Context, request *model.RegisterUserRequest) (*model.UserResponse, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.UserResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.RegisterUserRequest) (*model.UserResponse, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.RegisterUserRequest) *model.UserResponse); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.RegisterUserRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserUseCase_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUserUseCase_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - request *model.RegisterUserRequest
func (_e *MockUserUseCase_Expecter) Create(ctx interface{}, request interface{}) *MockUserUseCase_Create_Call {
	return &MockUserUseCase_Create_Call{Call: _e.mock.On("Create", ctx, request)}
}

func (_c *MockUserUseCase_Create_Call) Run(run func(ctx context.Context, request *model.RegisterUserRequest)) *MockUserUseCase_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.RegisterUserRequest
		if args[1] != nil {
			arg1 = args[1].(*model.RegisterUserRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserUseCase_Create_Call) Return(userResponse *model.UserResponse, err error) *MockUserUseCase_Create_Call {
	_c.Call.Return(userResponse, err)
	return _c
}

func (_c *MockUserUseCase_Create_Call) RunAndReturn(run func(ctx context.Context, request *model.RegisterUserRequest) (*model.UserResponse, error)) *MockUserUseCase_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Current provides a mock function for the type MockUserUseCase
func (_mock *MockUserUseCase) Current(ctx context.Context, request *model.GetUserRequest) (*model.UserResponse, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Current")
	}

	var r0 *model.UserResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.GetUserRequest) (*model.UserResponse, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.GetUserRequest) *model.UserResponse); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.GetUserRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserUseCase_Current_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Current'
type MockUserUseCase_Current_Call struct {
	*mock.Call
}

// Current is a helper method to define mock.On call
//   - ctx context.Context
//   - request *model.GetUserRequest
func (_e *MockUserUseCase_Expecter) Current(ctx interface{}, request interface{}) *MockUserUseCase_Current_Call {
	return &MockUserUseCase_Current_Call{Call: _e.mock.On("Current", ctx, request)}
}

func (_c *MockUserUseCase_Current_Call) Run(run func(ctx context.Context, request *model.GetUserRequest)) *MockUserUseCase_Current_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.GetUserRequest
		if args[1] != nil {
			arg1 = args[1].(*model.GetUserRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserUseCase_Current_Call) Return(userResponse *model.UserResponse, err error) *MockUserUseCase_Current_Call {
	_c.Call.Return(userResponse, err)
	return _c
}

func (_c *MockUserUseCase_Current_Call) RunAndReturn(run func(ctx context.Context, request *model.GetUserRequest) (*model.UserResponse, error)) *MockUserUseCase_Current_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUser provides a mock function for the type MockUserUseCase
func (_mock *MockUserUseCase) DeleteUser(ctx context.Context, actorUserID string, request *model.DeleteUserRequest) error {
	ret := _mock.Called(ctx, actorUserID, request)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *model.DeleteUserRequest) error); ok {
		r0 = returnFunc(ctx, actorUserID, request)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserUseCase_DeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUser'
type MockUserUseCase_DeleteUser_Call struct {
	*mock.Call
}

// DeleteUser is a helper method to define mock.On call
//   - ctx context.Context
//   - actorUserID string
//   - request *model.DeleteUserRequest
func (_e *MockUserUseCase_Expecter) DeleteUser(ctx interface{}, actorUserID interface{}, request interface{}) *MockUserUseCase_DeleteUser_Call {
	return &MockUserUseCase_DeleteUser_Call{Call: _e.mock.On("DeleteUser", ctx, actorUserID, request)}
}

func (_c *MockUserUseCase_DeleteUser_Call) Run(run func(ctx context.Context, actorUserID string, request *model.DeleteUserRequest)) *MockUserUseCase_DeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *model.DeleteUserRequest
		if args[2] != nil {
			arg2 = args[2].(*model.DeleteUserRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserUseCase_DeleteUser_Call) Return(err error) *MockUserUseCase_DeleteUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserUseCase_DeleteUser_Call) RunAndReturn(run func(ctx context.Context, actorUserID string, request *model.DeleteUserRequest) error) *MockUserUseCase_DeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllUsers provides a mock function for the type MockUserUseCase
func (_mock *MockUserUseCase) GetAllUsers(ctx context.Context, request *model.GetUserListRequest) ([]*model.UserResponse, int64, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for GetAllUsers")
	}

	var r0 []*model.UserResponse
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.GetUserListRequest) ([]*model.UserResponse, int64, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.GetUserListRequest) []*model.UserResponse); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.UserResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.GetUserListRequest) int64); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, *model.GetUserListRequest) error); ok {
		r2 = returnFunc(ctx, request)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockUserUseCase_GetAllUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllUsers'
type MockUserUseCase_GetAllUsers_Call struct {
	*mock.Call
}

// GetAllUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - request *model.GetUserListRequest
func (_e *MockUserUseCase_Expecter) GetAllUsers(ctx interface{}, request interface{}) *MockUserUseCase_GetAllUsers_Call {
	return &MockUserUseCase_GetAllUsers_Call{Call: _e.mock.On("GetAllUsers", ctx, request)}
}

func (_c *MockUserUseCase_GetAllUsers_Call) Run(run func(ctx context.Context, request *model.GetUserListRequest)) *MockUserUseCase_GetAllUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.GetUserListRequest
		if args[1] != nil {
			arg1 = args[1].(*model.GetUserListRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserUseCase_GetAllUsers_Call) Return(userResponses []*model.UserResponse, n int64, err error) *MockUserUseCase_GetAllUsers_Call {
	_c.Call.Return(userResponses, n, err)
	return _c
}

func (_c *MockUserUseCase_GetAllUsers_Call) RunAndReturn(run func(ctx context.Context, request *model.GetUserListRequest) ([]*model.UserResponse, int64, error)) *MockUserUseCase_GetAllUsers_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllUsersDynamic provides a mock function for the type MockUserUseCase
func (_mock *MockUserUseCase) GetAllUsersDynamic(ctx context.Context, filter *querybuilder.DynamicFilter) ([]*model.UserResponse, int64, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetAllUsersDynamic")
	}

	var r0 []*model.UserResponse
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *querybuilder.DynamicFilter) ([]*model.UserResponse, int64, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *querybuilder.DynamicFilter) []*model.UserResponse); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.UserResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *querybuilder.DynamicFilter) int64); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, *querybuilder.DynamicFilter) error); ok {
		r2 = returnFunc(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockUserUseCase_GetAllUsersDynamic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllUsersDynamic'
type MockUserUseCase_GetAllUsersDynamic_Call struct {
	*mock.Call
}

// GetAllUsersDynamic is a helper method to define mock.On call
//   - ctx context.Context
//   - filter *querybuilder.DynamicFilter
func (_e *MockUserUseCase_Expecter) GetAllUsersDynamic(ctx interface{}, filter interface{}) *MockUserUseCase_GetAllUsersDynamic_Call {
	return &MockUserUseCase_GetAllUsersDynamic_Call{Call: _e.mock.On("GetAllUsersDynamic", ctx, filter)}
}

func (_c *MockUserUseCase_GetAllUsersDynamic_Call) Run(run func(ctx context.Context, filter *querybuilder.DynamicFilter)) *MockUserUseCase_GetAllUsersDynamic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *querybuilder.DynamicFilter
		if args[1] != nil {
			arg1 = args[1].(*querybuilder.DynamicFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserUseCase_GetAllUsersDynamic_Call) Return(userResponses []*model.UserResponse, n int64, err error) *MockUserUseCase_GetAllUsersDynamic_Call {
	_c.Call.Return(userResponses, n, err)
	return _c
}

func (_c *MockUserUseCase_GetAllUsersDynamic_Call) RunAndReturn(run func(ctx context.Context, filter *querybuilder.DynamicFilter) ([]*model.UserResponse, int64, error)) *MockUserUseCase_GetAllUsersDynamic_Call {
	_c.Call.Return(run)
	return _c
}

// GetAvatarUrl provides a mock function for the type MockUserUseCase
func (_mock *MockUserUseCase) GetAvatarUrl(ctx context.Context, userID string) (string, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetAvatarUrl")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserUseCase_GetAvatarUrl_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAvatarUrl'
type MockUserUseCase_GetAvatarUrl_Call struct {
	*mock.Call
}

// GetAvatarUrl is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockUserUseCase_Expecter) GetAvatarUrl(ctx interface{}, userID interface{}) *MockUserUseCase_GetAvatarUrl_Call {
	return &MockUserUseCase_GetAvatarUrl_Call{Call: _e.mock.On("GetAvatarUrl", ctx, userID)}
}

func (_c *MockUserUseCase_GetAvatarUrl_Call) Run(run func(ctx context.Context, userID string)) *MockUserUseCase_GetAvatarUrl_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserUseCase_GetAvatarUrl_Call) Return(s string, err error) *MockUserUseCase_GetAvatarUrl_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockUserUseCase_GetAvatarUrl_Call) RunAndReturn(run func(ctx context.Context, userID string) (string, error)) *MockUserUseCase_GetAvatarUrl_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByID provides a mock function for the type MockUserUseCase
func (_mock *MockUserUseCase) GetUserByID(ctx context.Context, id string) (*model.UserResponse, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 *model.UserResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.UserResponse, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.UserResponse); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserUseCase_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type MockUserUseCase_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockUserUseCase_Expecter) GetUserByID(ctx interface{}, id interface{}) *MockUserUseCase_GetUserByID_Call {
	return &MockUserUseCase_GetUserByID_Call{Call: _e.mock.On("GetUserByID", ctx, id)}
}

func (_c *MockUserUseCase_GetUserByID_Call) Run(run func(ctx context.Context, id string)) *MockUserUseCase_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserUseCase_GetUserByID_Call) Return(userResponse *model.UserResponse, err error) *MockUserUseCase_GetUserByID_Call {
	_c.Call.Return(userResponse, err)
	return _c
}

func (_c *MockUserUseCase_GetUserByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*model.UserResponse, error)) *MockUserUseCase_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// HardDeleteSoftDeletedUsers provides a mock function for the type MockUserUseCase
func (_mock *MockUserUseCase) HardDeleteSoftDeletedUsers(ctx context.Context, retentionDays int) error {
	ret := _mock.Called(ctx, retentionDays)

	if len(ret) == 0 {
		panic("no return value specified for HardDeleteSoftDeletedUsers")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, retentionDays)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserUseCase_HardDeleteSoftDeletedUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HardDeleteSoftDeletedUsers'
type MockUserUseCase_HardDeleteSoftDeletedUsers_Call struct {
	*mock.Call
}

// HardDeleteSoftDeletedUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - retentionDays int
func (_e *MockUserUseCase_Expecter) HardDeleteSoftDeletedUsers(ctx interface{}, retentionDays interface{}) *MockUserUseCase_HardDeleteSoftDeletedUsers_Call {
	return &MockUserUseCase_HardDeleteSoftDeletedUsers_Call{Call: _e.mock.On("HardDeleteSoftDeletedUsers", ctx, retentionDays)}
}

func (_c *MockUserUseCase_HardDeleteSoftDeletedUsers_Call) Run(run func(ctx context.Context, retentionDays int)) *MockUserUseCase_HardDeleteSoftDeletedUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserUseCase_HardDeleteSoftDeletedUsers_Call) Return(err error) *MockUserUseCase_HardDeleteSoftDeletedUsers_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserUseCase_HardDeleteSoftDeletedUsers_Call) RunAndReturn(run func(ctx context.Context, retentionDays int) error) *MockUserUseCase_HardDeleteSoftDeletedUsers_Call {
	_c.Call.Return(run)
	return _c
}

// SetAvatarURL provides a mock function for the type MockUserUseCase
func (_mock *MockUserUseCase) SetAvatarURL(ctx context.Context, userID string, url string) error {
	ret := _mock.Called(ctx, userID, url)

	if len(ret) == 0 {
		panic("no return value specified for SetAvatarURL")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, userID, url)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserUseCase_SetAvatarURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetAvatarURL'
type MockUserUseCase_SetAvatarURL_Call struct {
	*mock.Call
}

// SetAvatarURL is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - url string
func (_e *MockUserUseCase_Expecter) SetAvatarURL(ctx interface{}, userID interface{}, url interface{}) *MockUserUseCase_SetAvatarURL_Call {
	return &MockUserUseCase_SetAvatarURL_Call{Call: _e.mock.On("SetAvatarURL", ctx, userID, url)}
}

func (_c *MockUserUseCase_SetAvatarURL_Call) Run(run func(ctx context.Context, userID string, url string)) *MockUserUseCase_SetAvatarURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserUseCase_SetAvatarURL_Call) Return(err error) *MockUserUseCase_SetAvatarURL_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserUseCase_SetAvatarURL_Call) RunAndReturn(run func(ctx context.Context, userID string, url string) error) *MockUserUseCase_SetAvatarURL_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockUserUseCase
func (_mock *MockUserUseCase) Update(ctx context.Context, request *model.UpdateUserRequest) (*model.UserResponse, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *model.UserResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.UpdateUserRequest) (*model.UserResponse, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.UpdateUserRequest) *model.UserResponse); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.UpdateUserRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserUseCase_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockUserUseCase_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - request *model.UpdateUserRequest
func (_e *MockUserUseCase_Expecter) Update(ctx interface{}, request interface{}) *MockUserUseCase_Update_Call {
	return &MockUserUseCase_Update_Call{Call: _e.mock.On("Update", ctx, request)}
}

func (_c *MockUserUseCase_Update_Call) Run(run func(ctx context.Context, request *model.UpdateUserRequest)) *MockUserUseCase_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.UpdateUserRequest
		if args[1] != nil {
			arg1 = args[1].(*model.UpdateUserRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserUseCase_Update_Call) Return(userResponse *model.UserResponse, err error) *MockUserUseCase_Update_Call {
	_c.Call.Return(userResponse, err)
	return _c
}

func (_c *MockUserUseCase_Update_Call) RunAndReturn(run func(ctx context.Context, request *model.UpdateUserRequest) (*model.UserResponse, error)) *MockUserUseCase_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateAvatar provides a mock function for the type MockUserUseCase
func (_mock *MockUserUseCase) UpdateAvatar(ctx context.Context, userID string, file io.Reader, filename string, contentType string) (*model.UserResponse, error) {
	ret := _mock.Called(ctx, userID, file, filename, contentType)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAvatar")
	}

	var r0 *model.UserResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, io.Reader, string, string) (*model.UserResponse, error)); ok {
		return returnFunc(ctx, userID, file, filename, contentType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, io.Reader, string, string) *model.UserResponse); ok {
		r0 = returnFunc(ctx, userID, file, filename, contentType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, io.Reader, string, string) error); ok {
		r1 = returnFunc(ctx, userID, file, filename, contentType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserUseCase_UpdateAvatar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAvatar'
type MockUserUseCase_UpdateAvatar_Call struct {
	*mock.Call
}

// UpdateAvatar is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - file io.Reader
//   - filename string
//   - contentType string
func (_e *MockUserUseCase_Expecter) UpdateAvatar(ctx interface{}, userID interface{}, file interface{}, filename interface{}, contentType interface{}) *MockUserUseCase_UpdateAvatar_Call {
	return &MockUserUseCase_UpdateAvatar_Call{Call: _e.mock.On("UpdateAvatar", ctx, userID, file, filename, contentType)}
}

func (_c *MockUserUseCase_UpdateAvatar_Call) Run(run func(ctx context.Context, userID string, file io.Reader, filename string, contentType string)) *MockUserUseCase_UpdateAvatar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 io.Reader
		if args[2] != nil {
			arg2 = args[2].(io.Reader)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockUserUseCase_UpdateAvatar_Call) Return(userResponse *model.UserResponse, err error) *MockUserUseCase_UpdateAvatar_Call {
	_c.Call.Return(userResponse, err)
	return _c
}

func (_c *MockUserUseCase_UpdateAvatar_Call) RunAndReturn(run func(ctx context.Context, userID string, file io.Reader, filename string, contentType string) (*model.UserResponse, error)) *MockUserUseCase_UpdateAvatar_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function for the type MockUserUseCase
func (_mock *MockUserUseCase) UpdateStatus(ctx context.Context, userID string, status string) error {
	ret := _mock.Called(ctx, userID, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, userID, status)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserUseCase_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockUserUseCase_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - status string
func (_e *MockUserUseCase_Expecter) UpdateStatus(ctx interface{}, userID interface{}, status interface{}) *MockUserUseCase_UpdateStatus_Call {
	return &MockUserUseCase_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, userID, status)}
}

func (_c *MockUserUseCase_UpdateStatus_Call) Run(run func(ctx context.Context, userID string, status string)) *MockUserUseCase_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserUseCase_UpdateStatus_Call) Return(err error) *MockUserUseCase_UpdateStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserUseCase_UpdateStatus_Call) RunAndReturn(run func(ctx context.Context, userID string, status string) error) *MockUserUseCase_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}
