// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Roisfaozi/queue-base/internal/modules/auth/model"
	"github.com/Roisfaozi/queue-base/internal/modules/user/entity"
	"github.com/Roisfaozi/queue-base/pkg/jwt"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthUseCase creates a new instance of MockAuthUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthUseCase {
	m := &MockAuthUseCase{}
	m.Mock.Test(t)

	t.Cleanup(func() { m.AssertExpectations(t) })

	return m
}

// MockAuthUseCase is an autogenerated mock type for the AuthUseCase type
type MockAuthUseCase struct {
	mock.Mock
}

type MockAuthUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthUseCase) EXPECT() *MockAuthUseCase_Expecter {
	return &MockAuthUseCase_Expecter{mock: &_m.Mock}
}

// ForgotPassword provides a mock function for the type MockAuthUseCase
func (_mock *MockAuthUseCase) ForgotPassword(ctx context.Context, email string) error {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for ForgotPassword")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, email)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthUseCase_ForgotPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ForgotPassword'
type MockAuthUseCase_ForgotPassword_Call struct {
	*mock.Call
}

// ForgotPassword is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockAuthUseCase_Expecter) ForgotPassword(ctx interface{}, email interface{}) *MockAuthUseCase_ForgotPassword_Call {
	return &MockAuthUseCase_ForgotPassword_Call{Call: _e.mock.On("ForgotPassword", ctx, email)}
}

func (_c *MockAuthUseCase_ForgotPassword_Call) Run(run func(ctx context.Context, email string)) *MockAuthUseCase_ForgotPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthUseCase_ForgotPassword_Call) Return(err error) *MockAuthUseCase_ForgotPassword_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthUseCase_ForgotPassword_Call) RunAndReturn(run func(ctx context.Context, email string) error) *MockAuthUseCase_ForgotPassword_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateAccessToken provides a mock function for the type MockAuthUseCase
func (_mock *MockAuthUseCase) GenerateAccessToken(user *entity.User) (string, error) {
	ret := _mock.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for GenerateAccessToken")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*entity.User) (string, error)); ok {
		return returnFunc(user)
	}
	if returnFunc, ok := ret.Get(0).(func(*entity.User) string); ok {
		r0 = returnFunc(user)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(*entity.User) error); ok {
		r1 = returnFunc(user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthUseCase_GenerateAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateAccessToken'
type MockAuthUseCase_GenerateAccessToken_Call struct {
	*mock.Call
}

// GenerateAccessToken is a helper method to define mock.On call
//   - user *entity.User
func (_e *MockAuthUseCase_Expecter) GenerateAccessToken(user interface{}) *MockAuthUseCase_GenerateAccessToken_Call {
	return &MockAuthUseCase_GenerateAccessToken_Call{Call: _e.mock.On("GenerateAccessToken", user)}
}

func (_c *MockAuthUseCase_GenerateAccessToken_Call) Run(run func(user *entity.User)) *MockAuthUseCase_GenerateAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *entity.User
		if args[0] != nil {
			arg0 = args[0].(*entity.User)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuthUseCase_GenerateAccessToken_Call) Return(s string, err error) *MockAuthUseCase_GenerateAccessToken_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockAuthUseCase_GenerateAccessToken_Call) RunAndReturn(run func(user *entity.User) (string, error)) *MockAuthUseCase_GenerateAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateRefreshToken provides a mock function for the type MockAuthUseCase
func (_mock *MockAuthUseCase) GenerateRefreshToken(user *entity.User) (string, error) {
	ret := _mock.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for GenerateRefreshToken")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*entity.User) (string, error)); ok {
		return returnFunc(user)
	}
	if returnFunc, ok := ret.Get(0).(func(*entity.User) string); ok {
		r0 = returnFunc(user)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(*entity.User) error); ok {
		r1 = returnFunc(user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthUseCase_GenerateRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateRefreshToken'
type MockAuthUseCase_GenerateRefreshToken_Call struct {
	*mock.Call
}

// GenerateRefreshToken is a helper method to define mock.On call
//   - user *entity.User
func (_e *MockAuthUseCase_Expecter) GenerateRefreshToken(user interface{}) *MockAuthUseCase_GenerateRefreshToken_Call {
	return &MockAuthUseCase_GenerateRefreshToken_Call{Call: _e.mock.On("GenerateRefreshToken", user)}
}

func (_c *MockAuthUseCase_GenerateRefreshToken_Call) Run(run func(user *entity.User)) *MockAuthUseCase_GenerateRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *entity.User
		if args[0] != nil {
			arg0 = args[0].(*entity.User)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuthUseCase_GenerateRefreshToken_Call) Return(s string, err error) *MockAuthUseCase_GenerateRefreshToken_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockAuthUseCase_GenerateRefreshToken_Call) RunAndReturn(run func(user *entity.User) (string, error)) *MockAuthUseCase_GenerateRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetSSORedirectURL provides a mock function for the type MockAuthUseCase
func (_mock *MockAuthUseCase) GetSSORedirectURL(ctx context.Context, provider string, state string) (string, error) {
	ret := _mock.Called(ctx, provider, state)

	if len(ret) == 0 {
		panic("no return value specified for GetSSORedirectURL")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return returnFunc(ctx, provider, state)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = returnFunc(ctx, provider, state)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, provider, state)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthUseCase_GetSSORedirectURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSSORedirectURL'
type MockAuthUseCase_GetSSORedirectURL_Call struct {
	*mock.Call
}

// GetSSORedirectURL is a helper method to define mock.On call
//   - ctx context.Context
//   - provider string
//   - state string
func (_e *MockAuthUseCase_Expecter) GetSSORedirectURL(ctx interface{}, provider interface{}, state interface{}) *MockAuthUseCase_GetSSORedirectURL_Call {
	return &MockAuthUseCase_GetSSORedirectURL_Call{Call: _e.mock.On("GetSSORedirectURL", ctx, provider, state)}
}

func (_c *MockAuthUseCase_GetSSORedirectURL_Call) Run(run func(ctx context.Context, provider string, state string)) *MockAuthUseCase_GetSSORedirectURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAuthUseCase_GetSSORedirectURL_Call) Return(s string, err error) *MockAuthUseCase_GetSSORedirectURL_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockAuthUseCase_GetSSORedirectURL_Call) RunAndReturn(run func(ctx context.Context, provider string, state string) (string, error)) *MockAuthUseCase_GetSSORedirectURL_Call {
	_c.Call.Return(run)
	return _c
}

// GetTicket provides a mock function for the type MockAuthUseCase
func (_mock *MockAuthUseCase) GetTicket(ctx context.Context, userContext model.UserSessionContext) (string, error) {
	ret := _mock.Called(ctx, userContext)

	if len(ret) == 0 {
		panic("no return value specified for GetTicket")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.UserSessionContext) (string, error)); ok {
		return returnFunc(ctx, userContext)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.UserSessionContext) string); ok {
		r0 = returnFunc(ctx, userContext)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.UserSessionContext) error); ok {
		r1 = returnFunc(ctx, userContext)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthUseCase_GetTicket_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTicket'
type MockAuthUseCase_GetTicket_Call struct {
	*mock.Call
}

// GetTicket is a helper method to define mock.On call
//   - ctx context.Context
//   - userContext model.UserSessionContext
func (_e *MockAuthUseCase_Expecter) GetTicket(ctx interface{}, userContext interface{}) *MockAuthUseCase_GetTicket_Call {
	return &MockAuthUseCase_GetTicket_Call{Call: _e.mock.On("GetTicket", ctx, userContext)}
}

func (_c *MockAuthUseCase_GetTicket_Call) Run(run func(ctx context.Context, userContext model.UserSessionContext)) *MockAuthUseCase_GetTicket_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.UserSessionContext
		if args[1] != nil {
			arg1 = args[1].(model.UserSessionContext)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthUseCase_GetTicket_Call) Return(s string, err error) *MockAuthUseCase_GetTicket_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockAuthUseCase_GetTicket_Call) RunAndReturn(run func(ctx context.Context, userContext model.UserSessionContext) (string, error)) *MockAuthUseCase_GetTicket_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserSessions provides a mock function for the type MockAuthUseCase
func (_mock *MockAuthUseCase) GetUserSessions(ctx context.Context, userID string) ([]*model.Auth, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserSessions")
	}

	var r0 []*model.Auth
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*model.Auth, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*model.Auth); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Auth)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthUseCase_GetUserSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserSessions'
type MockAuthUseCase_GetUserSessions_Call struct {
	*mock.Call
}

// GetUserSessions is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockAuthUseCase_Expecter) GetUserSessions(ctx interface{}, userID interface{}) *MockAuthUseCase_GetUserSessions_Call {
	return &MockAuthUseCase_GetUserSessions_Call{Call: _e.mock.On("GetUserSessions", ctx, userID)}
}

func (_c *MockAuthUseCase_GetUserSessions_Call) Run(run func(ctx context.Context, userID string)) *MockAuthUseCase_GetUserSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthUseCase_GetUserSessions_Call) Return(auths []*model.Auth, err error) *MockAuthUseCase_GetUserSessions_Call {
	_c.Call.Return(auths, err)
	return _c
}

func (_c *MockAuthUseCase_GetUserSessions_Call) RunAndReturn(run func(ctx context.Context, userID string) ([]*model.Auth, error)) *MockAuthUseCase_GetUserSessions_Call {
	_c.Call.Return(run)
	return _c
}

// HandleSSOCallback provides a mock function for the type MockAuthUseCase
func (_mock *MockAuthUseCase) HandleSSOCallback(ctx context.Context, provider string, code string) (*model.LoginResponse, string, error) {
	ret := _mock.Called(ctx, provider, code)

	if len(ret) == 0 {
		panic("no return value specified for HandleSSOCallback")
	}

	var r0 *model.LoginResponse
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*model.LoginResponse, string, error)); ok {
		return returnFunc(ctx, provider, code)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *model.LoginResponse); ok {
		r0 = returnFunc(ctx, provider, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.LoginResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) string); ok {
		r1 = returnFunc(ctx, provider, code)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = returnFunc(ctx, provider, code)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockAuthUseCase_HandleSSOCallback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleSSOCallback'
type MockAuthUseCase_HandleSSOCallback_Call struct {
	*mock.Call
}

// HandleSSOCallback is a helper method to define mock.On call
//   - ctx context.Context
//   - provider string
//   - code string
func (_e *MockAuthUseCase_Expecter) HandleSSOCallback(ctx interface{}, provider interface{}, code interface{}) *MockAuthUseCase_HandleSSOCallback_Call {
	return &MockAuthUseCase_HandleSSOCallback_Call{Call: _e.mock.On("HandleSSOCallback", ctx, provider, code)}
}

func (_c *MockAuthUseCase_HandleSSOCallback_Call) Run(run func(ctx context.Context, provider string, code string)) *MockAuthUseCase_HandleSSOCallback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAuthUseCase_HandleSSOCallback_Call) Return(loginResponse *model.LoginResponse, s string, err error) *MockAuthUseCase_HandleSSOCallback_Call {
	_c.Call.Return(loginResponse, s, err)
	return _c
}

func (_c *MockAuthUseCase_HandleSSOCallback_Call) RunAndReturn(run func(ctx context.Context, provider string, code string) (*model.LoginResponse, string, error)) *MockAuthUseCase_HandleSSOCallback_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function for the type MockAuthUseCase
func (_mock *MockAuthUseCase) Login(ctx context.Context, request model.LoginRequest) (*model.LoginResponse, string, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *model.LoginResponse
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.LoginRequest) (*model.LoginResponse, string, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.LoginRequest) *model.LoginResponse); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.LoginResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.LoginRequest) string); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, model.LoginRequest) error); ok {
		r2 = returnFunc(ctx, request)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockAuthUseCase_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockAuthUseCase_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - request model.LoginRequest
func (_e *MockAuthUseCase_Expecter) Login(ctx interface{}, request interface{}) *MockAuthUseCase_Login_Call {
	return &MockAuthUseCase_Login_Call{Call: _e.mock.On("Login", ctx, request)}
}

func (_c *MockAuthUseCase_Login_Call) Run(run func(ctx context.Context, request model.LoginRequest)) *MockAuthUseCase_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.LoginRequest
		if args[1] != nil {
			arg1 = args[1].(model.LoginRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthUseCase_Login_Call) Return(loginResponse *model.LoginResponse, s string, err error) *MockAuthUseCase_Login_Call {
	_c.Call.Return(loginResponse, s, err)
	return _c
}

func (_c *MockAuthUseCase_Login_Call) RunAndReturn(run func(ctx context.Context, request model.LoginRequest) (*model.LoginResponse, string, error)) *MockAuthUseCase_Login_Call {
	_c.Call.Return(run)
	return _c
}

// RefreshToken provides a mock function for the type MockAuthUseCase
func (_mock *MockAuthUseCase) RefreshToken(ctx context.Context, refreshToken string) (*model.TokenResponse, string, error) {
	ret := _mock.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for RefreshToken")
	}

	var r0 *model.TokenResponse
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.TokenResponse, string, error)); ok {
		return returnFunc(ctx, refreshToken)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.TokenResponse); ok {
		r0 = returnFunc(ctx, refreshToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.TokenResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) string); ok {
		r1 = returnFunc(ctx, refreshToken)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctx, refreshToken)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockAuthUseCase_RefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshToken'
type MockAuthUseCase_RefreshToken_Call struct {
	*mock.Call
}

// RefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken string
func (_e *MockAuthUseCase_Expecter) RefreshToken(ctx interface{}, refreshToken interface{}) *MockAuthUseCase_RefreshToken_Call {
	return &MockAuthUseCase_RefreshToken_Call{Call: _e.mock.On("RefreshToken", ctx, refreshToken)}
}

func (_c *MockAuthUseCase_RefreshToken_Call) Run(run func(ctx context.Context, refreshToken string)) *MockAuthUseCase_RefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthUseCase_RefreshToken_Call) Return(tokenResponse *model.TokenResponse, s string, err error) *MockAuthUseCase_RefreshToken_Call {
	_c.Call.Return(tokenResponse, s, err)
	return _c
}

func (_c *MockAuthUseCase_RefreshToken_Call) RunAndReturn(run func(ctx context.Context, refreshToken string) (*model.TokenResponse, string, error)) *MockAuthUseCase_RefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function for the type MockAuthUseCase
func (_mock *MockAuthUseCase) Register(ctx context.Context, request model.RegisterRequest) (*model.LoginResponse, string, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *model.LoginResponse
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.RegisterRequest) (*model.LoginResponse, string, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.RegisterRequest) *model.LoginResponse); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.LoginResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.RegisterRequest) string); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, model.RegisterRequest) error); ok {
		r2 = returnFunc(ctx, request)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockAuthUseCase_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockAuthUseCase_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - request model.RegisterRequest
func (_e *MockAuthUseCase_Expecter) Register(ctx interface{}, request interface{}) *MockAuthUseCase_Register_Call {
	return &MockAuthUseCase_Register_Call{Call: _e.mock.On("Register", ctx, request)}
}

func (_c *MockAuthUseCase_Register_Call) Run(run func(ctx context.Context, request model.RegisterRequest)) *MockAuthUseCase_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.RegisterRequest
		if args[1] != nil {
			arg1 = args[1].(model.RegisterRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthUseCase_Register_Call) Return(loginResponse *model.LoginResponse, s string, err error) *MockAuthUseCase_Register_Call {
	_c.Call.Return(loginResponse, s, err)
	return _c
}

func (_c *MockAuthUseCase_Register_Call) RunAndReturn(run func(ctx context.Context, request model.RegisterRequest) (*model.LoginResponse, string, error)) *MockAuthUseCase_Register_Call {
	_c.Call.Return(run)
	return _c
}

// RequestVerification provides a mock function for the type MockAuthUseCase
func (_mock *MockAuthUseCase) RequestVerification(ctx context.Context, userID string) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for RequestVerification")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthUseCase_RequestVerification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequestVerification'
type MockAuthUseCase_RequestVerification_Call struct {
	*mock.Call
}

// RequestVerification is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockAuthUseCase_Expecter) RequestVerification(ctx interface{}, userID interface{}) *MockAuthUseCase_RequestVerification_Call {
	return &MockAuthUseCase_RequestVerification_Call{Call: _e.mock.On("RequestVerification", ctx, userID)}
}

func (_c *MockAuthUseCase_RequestVerification_Call) Run(run func(ctx context.Context, userID string)) *MockAuthUseCase_RequestVerification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthUseCase_RequestVerification_Call) Return(err error) *MockAuthUseCase_RequestVerification_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthUseCase_RequestVerification_Call) RunAndReturn(run func(ctx context.Context, userID string) error) *MockAuthUseCase_RequestVerification_Call {
	_c.Call.Return(run)
	return _c
}

// ResetPassword provides a mock function for the type MockAuthUseCase
func (_mock *MockAuthUseCase) ResetPassword(ctx context.Context, token string, newPassword string) error {
	ret := _mock.Called(ctx, token, newPassword)

	if len(ret) == 0 {
		panic("no return value specified for ResetPassword")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, token, newPassword)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthUseCase_ResetPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResetPassword'
type MockAuthUseCase_ResetPassword_Call struct {
	*mock.Call
}

// ResetPassword is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
//   - newPassword string
func (_e *MockAuthUseCase_Expecter) ResetPassword(ctx interface{}, token interface{}, newPassword interface{}) *MockAuthUseCase_ResetPassword_Call {
	return &MockAuthUseCase_ResetPassword_Call{Call: _e.mock.On("ResetPassword", ctx, token, newPassword)}
}

func (_c *MockAuthUseCase_ResetPassword_Call) Run(run func(ctx context.Context, token string, newPassword string)) *MockAuthUseCase_ResetPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAuthUseCase_ResetPassword_Call) Return(err error) *MockAuthUseCase_ResetPassword_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthUseCase_ResetPassword_Call) RunAndReturn(run func(ctx context.Context, token string, newPassword string) error) *MockAuthUseCase_ResetPassword_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeAllSessions provides a mock function for the type MockAuthUseCase
func (_mock *MockAuthUseCase) RevokeAllSessions(ctx context.Context, userID string) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeAllSessions")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthUseCase_RevokeAllSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeAllSessions'
type MockAuthUseCase_RevokeAllSessions_Call struct {
	*mock.Call
}

// RevokeAllSessions is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockAuthUseCase_Expecter) RevokeAllSessions(ctx interface{}, userID interface{}) *MockAuthUseCase_RevokeAllSessions_Call {
	return &MockAuthUseCase_RevokeAllSessions_Call{Call: _e.mock.On("RevokeAllSessions", ctx, userID)}
}

func (_c *MockAuthUseCase_RevokeAllSessions_Call) Run(run func(ctx context.Context, userID string)) *MockAuthUseCase_RevokeAllSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthUseCase_RevokeAllSessions_Call) Return(err error) *MockAuthUseCase_RevokeAllSessions_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthUseCase_RevokeAllSessions_Call) RunAndReturn(run func(ctx context.Context, userID string) error) *MockAuthUseCase_RevokeAllSessions_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeToken provides a mock function for the type MockAuthUseCase
func (_mock *MockAuthUseCase) RevokeToken(ctx context.Context, userID string, sessionID string) error {
	ret := _mock.Called(ctx, userID, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, userID, sessionID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthUseCase_RevokeToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeToken'
type MockAuthUseCase_RevokeToken_Call struct {
	*mock.Call
}

// RevokeToken is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - sessionID string
func (_e *MockAuthUseCase_Expecter) RevokeToken(ctx interface{}, userID interface{}, sessionID interface{}) *MockAuthUseCase_RevokeToken_Call {
	return &MockAuthUseCase_RevokeToken_Call{Call: _e.mock.On("RevokeToken", ctx, userID, sessionID)}
}

func (_c *MockAuthUseCase_RevokeToken_Call) Run(run func(ctx context.Context, userID string, sessionID string)) *MockAuthUseCase_RevokeToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAuthUseCase_RevokeToken_Call) Return(err error) *MockAuthUseCase_RevokeToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthUseCase_RevokeToken_Call) RunAndReturn(run func(ctx context.Context, userID string, sessionID string) error) *MockAuthUseCase_RevokeToken_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateAccessToken provides a mock function for the type MockAuthUseCase
func (_mock *MockAuthUseCase) ValidateAccessToken(token string) (*jwt.Claims, error) {
	ret := _mock.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for ValidateAccessToken")
	}

	var r0 *jwt.Claims
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*jwt.Claims, error)); ok {
		return returnFunc(token)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *jwt.Claims); ok {
		r0 = returnFunc(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*jwt.Claims)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthUseCase_ValidateAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateAccessToken'
type MockAuthUseCase_ValidateAccessToken_Call struct {
	*mock.Call
}

// ValidateAccessToken is a helper method to define mock.On call
//   - token string
func (_e *MockAuthUseCase_Expecter) ValidateAccessToken(token interface{}) *MockAuthUseCase_ValidateAccessToken_Call {
	return &MockAuthUseCase_ValidateAccessToken_Call{Call: _e.mock.On("ValidateAccessToken", token)}
}

func (_c *MockAuthUseCase_ValidateAccessToken_Call) Run(run func(token string)) *MockAuthUseCase_ValidateAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuthUseCase_ValidateAccessToken_Call) Return(claims *jwt.Claims, err error) *MockAuthUseCase_ValidateAccessToken_Call {
	_c.Call.Return(claims, err)
	return _c
}

func (_c *MockAuthUseCase_ValidateAccessToken_Call) RunAndReturn(run func(token string) (*jwt.Claims, error)) *MockAuthUseCase_ValidateAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateRefreshToken provides a mock function for the type MockAuthUseCase
func (_mock *MockAuthUseCase) ValidateRefreshToken(token string) (*jwt.Claims, error) {
	ret := _mock.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for ValidateRefreshToken")
	}

	var r0 *jwt.Claims
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*jwt.Claims, error)); ok {
		return returnFunc(token)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *jwt.Claims); ok {
		r0 = returnFunc(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*jwt.Claims)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthUseCase_ValidateRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateRefreshToken'
type MockAuthUseCase_ValidateRefreshToken_Call struct {
	*mock.Call
}

// ValidateRefreshToken is a helper method to define mock.On call
//   - token string
func (_e *MockAuthUseCase_Expecter) ValidateRefreshToken(token interface{}) *MockAuthUseCase_ValidateRefreshToken_Call {
	return &MockAuthUseCase_ValidateRefreshToken_Call{Call: _e.mock.On("ValidateRefreshToken", token)}
}

func (_c *MockAuthUseCase_ValidateRefreshToken_Call) Run(run func(token string)) *MockAuthUseCase_ValidateRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuthUseCase_ValidateRefreshToken_Call) Return(claims *jwt.Claims, err error) *MockAuthUseCase_ValidateRefreshToken_Call {
	_c.Call.Return(claims, err)
	return _c
}

func (_c *MockAuthUseCase_ValidateRefreshToken_Call) RunAndReturn(run func(token string) (*jwt.Claims, error)) *MockAuthUseCase_ValidateRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// Verify provides a mock function for the type MockAuthUseCase
func (_mock *MockAuthUseCase) Verify(ctx context.Context, userID string, sessionID string) (*model.Auth, error) {
	ret := _mock.Called(ctx, userID, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 *model.Auth
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*model.Auth, error)); ok {
		return returnFunc(ctx, userID, sessionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *model.Auth); ok {
		r0 = returnFunc(ctx, userID, sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Auth)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, userID, sessionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthUseCase_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type MockAuthUseCase_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - sessionID string
func (_e *MockAuthUseCase_Expecter) Verify(ctx interface{}, userID interface{}, sessionID interface{}) *MockAuthUseCase_Verify_Call {
	return &MockAuthUseCase_Verify_Call{Call: _e.mock.On("Verify", ctx, userID, sessionID)}
}

func (_c *MockAuthUseCase_Verify_Call) Run(run func(ctx context.Context, userID string, sessionID string)) *MockAuthUseCase_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAuthUseCase_Verify_Call) Return(auth *model.Auth, err error) *MockAuthUseCase_Verify_Call {
	_c.Call.Return(auth, err)
	return _c
}

func (_c *MockAuthUseCase_Verify_Call) RunAndReturn(run func(ctx context.Context, userID string, sessionID string) (*model.Auth, error)) *MockAuthUseCase_Verify_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyEmail provides a mock function for the type MockAuthUseCase
func (_mock *MockAuthUseCase) VerifyEmail(ctx context.Context, token string) error {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for VerifyEmail")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthUseCase_VerifyEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyEmail'
type MockAuthUseCase_VerifyEmail_Call struct {
	*mock.Call
}

// VerifyEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockAuthUseCase_Expecter) VerifyEmail(ctx interface{}, token interface{}) *MockAuthUseCase_VerifyEmail_Call {
	return &MockAuthUseCase_VerifyEmail_Call{Call: _e.mock.On("VerifyEmail", ctx, token)}
}

func (_c *MockAuthUseCase_VerifyEmail_Call) Run(run func(ctx context.Context, token string)) *MockAuthUseCase_VerifyEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthUseCase_VerifyEmail_Call) Return(err error) *MockAuthUseCase_VerifyEmail_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthUseCase_VerifyEmail_Call) RunAndReturn(run func(ctx context.Context, token string) error) *MockAuthUseCase_VerifyEmail_Call {
	_c.Call.Return(run)
	return _c
}
