// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Roisfaozi/go-clean-boilerplate/internal/modules/api_key/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockApiKeyRepository creates a new instance of MockApiKeyRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockApiKeyRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockApiKeyRepository {
	m := &MockApiKeyRepository{}
	m.Mock.Test(t)

	t.Cleanup(func() { m.AssertExpectations(t) })

	return m
}

// MockApiKeyRepository is an autogenerated mock type for the ApiKeyRepository type
type MockApiKeyRepository struct {
	mock.Mock
}

type MockApiKeyRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockApiKeyRepository) EXPECT() *MockApiKeyRepository_Expecter {
	return &MockApiKeyRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockApiKeyRepository
func (_mock *MockApiKeyRepository) Create(ctx context.Context, apiKey *entity.ApiKey) error {
	ret := _mock.Called(ctx, apiKey)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.ApiKey) error); ok {
		r0 = returnFunc(ctx, apiKey)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockApiKeyRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockApiKeyRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - apiKey *entity.ApiKey
func (_e *MockApiKeyRepository_Expecter) Create(ctx interface{}, apiKey interface{}) *MockApiKeyRepository_Create_Call {
	return &MockApiKeyRepository_Create_Call{Call: _e.mock.On("Create", ctx, apiKey)}
}

func (_c *MockApiKeyRepository_Create_Call) Run(run func(ctx context.Context, apiKey *entity.ApiKey)) *MockApiKeyRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.ApiKey
		if args[1] != nil {
			arg1 = args[1].(*entity.ApiKey)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockApiKeyRepository_Create_Call) Return(err error) *MockApiKeyRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockApiKeyRepository_Create_Call) RunAndReturn(run func(ctx context.Context, apiKey *entity.ApiKey) error) *MockApiKeyRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockApiKeyRepository
func (_mock *MockApiKeyRepository) Delete(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockApiKeyRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockApiKeyRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockApiKeyRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockApiKeyRepository_Delete_Call {
	return &MockApiKeyRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockApiKeyRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *MockApiKeyRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockApiKeyRepository_Delete_Call) Return(err error) *MockApiKeyRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockApiKeyRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockApiKeyRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindByHash provides a mock function for the type MockApiKeyRepository
func (_mock *MockApiKeyRepository) FindByHash(ctx context.Context, keyHash string) (*entity.ApiKey, error) {
	ret := _mock.Called(ctx, keyHash)

	if len(ret) == 0 {
		panic("no return value specified for FindByHash")
	}

	var r0 *entity.ApiKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.ApiKey, error)); ok {
		return returnFunc(ctx, keyHash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.ApiKey); ok {
		r0 = returnFunc(ctx, keyHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.ApiKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, keyHash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockApiKeyRepository_FindByHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByHash'
type MockApiKeyRepository_FindByHash_Call struct {
	*mock.Call
}

// FindByHash is a helper method to define mock.On call
//   - ctx context.Context
//   - keyHash string
func (_e *MockApiKeyRepository_Expecter) FindByHash(ctx interface{}, keyHash interface{}) *MockApiKeyRepository_FindByHash_Call {
	return &MockApiKeyRepository_FindByHash_Call{Call: _e.mock.On("FindByHash", ctx, keyHash)}
}

func (_c *MockApiKeyRepository_FindByHash_Call) Run(run func(ctx context.Context, keyHash string)) *MockApiKeyRepository_FindByHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockApiKeyRepository_FindByHash_Call) Return(apiKey *entity.ApiKey, err error) *MockApiKeyRepository_FindByHash_Call {
	_c.Call.Return(apiKey, err)
	return _c
}

func (_c *MockApiKeyRepository_FindByHash_Call) RunAndReturn(run func(ctx context.Context, keyHash string) (*entity.ApiKey, error)) *MockApiKeyRepository_FindByHash_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockApiKeyRepository
func (_mock *MockApiKeyRepository) FindByID(ctx context.Context, id string) (*entity.ApiKey, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entity.ApiKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.ApiKey, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.ApiKey); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.ApiKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockApiKeyRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockApiKeyRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockApiKeyRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockApiKeyRepository_FindByID_Call {
	return &MockApiKeyRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockApiKeyRepository_FindByID_Call) Run(run func(ctx context.Context, id string)) *MockApiKeyRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockApiKeyRepository_FindByID_Call) Return(apiKey *entity.ApiKey, err error) *MockApiKeyRepository_FindByID_Call {
	_c.Call.Return(apiKey, err)
	return _c
}

func (_c *MockApiKeyRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*entity.ApiKey, error)) *MockApiKeyRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByOrg provides a mock function for the type MockApiKeyRepository
func (_mock *MockApiKeyRepository) ListByOrg(ctx context.Context, orgID string) ([]*entity.ApiKey, error) {
	ret := _mock.Called(ctx, orgID)

	if len(ret) == 0 {
		panic("no return value specified for ListByOrg")
	}

	var r0 []*entity.ApiKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*entity.ApiKey, error)); ok {
		return returnFunc(ctx, orgID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*entity.ApiKey); ok {
		r0 = returnFunc(ctx, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.ApiKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, orgID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockApiKeyRepository_ListByOrg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByOrg'
type MockApiKeyRepository_ListByOrg_Call struct {
	*mock.Call
}

// ListByOrg is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID string
func (_e *MockApiKeyRepository_Expecter) ListByOrg(ctx interface{}, orgID interface{}) *MockApiKeyRepository_ListByOrg_Call {
	return &MockApiKeyRepository_ListByOrg_Call{Call: _e.mock.On("ListByOrg", ctx, orgID)}
}

func (_c *MockApiKeyRepository_ListByOrg_Call) Run(run func(ctx context.Context, orgID string)) *MockApiKeyRepository_ListByOrg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockApiKeyRepository_ListByOrg_Call) Return(apiKeys []*entity.ApiKey, err error) *MockApiKeyRepository_ListByOrg_Call {
	_c.Call.Return(apiKeys, err)
	return _c
}

func (_c *MockApiKeyRepository_ListByOrg_Call) RunAndReturn(run func(ctx context.Context, orgID string) ([]*entity.ApiKey, error)) *MockApiKeyRepository_ListByOrg_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockApiKeyRepository
func (_mock *MockApiKeyRepository) Update(ctx context.Context, apiKey *entity.ApiKey) error {
	ret := _mock.Called(ctx, apiKey)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.ApiKey) error); ok {
		r0 = returnFunc(ctx, apiKey)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockApiKeyRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockApiKeyRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - apiKey *entity.ApiKey
func (_e *MockApiKeyRepository_Expecter) Update(ctx interface{}, apiKey interface{}) *MockApiKeyRepository_Update_Call {
	return &MockApiKeyRepository_Update_Call{Call: _e.mock.On("Update", ctx, apiKey)}
}

func (_c *MockApiKeyRepository_Update_Call) Run(run func(ctx context.Context, apiKey *entity.ApiKey)) *MockApiKeyRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.ApiKey
		if args[1] != nil {
			arg1 = args[1].(*entity.ApiKey)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockApiKeyRepository_Update_Call) Return(err error) *MockApiKeyRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockApiKeyRepository_Update_Call) RunAndReturn(run func(ctx context.Context, apiKey *entity.ApiKey) error) *MockApiKeyRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
