// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Roisfaozi/go-clean-boilerplate/internal/modules/audit/entity"
	"github.com/Roisfaozi/go-clean-boilerplate/internal/modules/audit/model"
	"github.com/Roisfaozi/go-clean-boilerplate/pkg/querybuilder"
	"github.com/hibiken/asynq"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTaskDistributor creates a new instance of MockTaskDistributor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTaskDistributor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTaskDistributor {
	m := &MockTaskDistributor{}
	m.Mock.Test(t)

	t.Cleanup(func() { m.AssertExpectations(t) })

	return m
}

// MockTaskDistributor is an autogenerated mock type for the TaskDistributor type
type MockTaskDistributor struct {
	mock.Mock
}

type MockTaskDistributor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTaskDistributor) EXPECT() *MockTaskDistributor_Expecter {
	return &MockTaskDistributor_Expecter{mock: &_m.Mock}
}

// DistributeTaskAuditLogExport provides a mock function for the type MockTaskDistributor
func (_mock *MockTaskDistributor) DistributeTaskAuditLogExport(ctx context.Context, payload model.AuditLogExportPayload, opts ...asynq.Option) error {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, payload, opts)
	} else {
		tmpRet = _mock.Called(ctx, payload)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for DistributeTaskAuditLogExport")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.AuditLogExportPayload, ...asynq.Option) error); ok {
		r0 = returnFunc(ctx, payload, opts...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTaskDistributor_DistributeTaskAuditLogExport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DistributeTaskAuditLogExport'
type MockTaskDistributor_DistributeTaskAuditLogExport_Call struct {
	*mock.Call
}

// DistributeTaskAuditLogExport is a helper method to define mock.On call
//   - ctx context.Context
//   - payload model.AuditLogExportPayload
//   - opts ...asynq.Option
func (_e *MockTaskDistributor_Expecter) DistributeTaskAuditLogExport(ctx interface{}, payload interface{}, opts ...interface{}) *MockTaskDistributor_DistributeTaskAuditLogExport_Call {
	return &MockTaskDistributor_DistributeTaskAuditLogExport_Call{Call: _e.mock.On("DistributeTaskAuditLogExport",
		append([]interface{}{ctx, payload}, opts...)...)}
}

func (_c *MockTaskDistributor_DistributeTaskAuditLogExport_Call) Run(run func(ctx context.Context, payload model.AuditLogExportPayload, opts ...asynq.Option)) *MockTaskDistributor_DistributeTaskAuditLogExport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.AuditLogExportPayload
		if args[1] != nil {
			arg1 = args[1].(model.AuditLogExportPayload)
		}
		var arg2 []asynq.Option
		var variadicArgs []asynq.Option
		if len(args) > 2 {
			variadicArgs = args[2].([]asynq.Option)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockTaskDistributor_DistributeTaskAuditLogExport_Call) Return(err error) *MockTaskDistributor_DistributeTaskAuditLogExport_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTaskDistributor_DistributeTaskAuditLogExport_Call) RunAndReturn(run func(ctx context.Context, payload model.AuditLogExportPayload, opts ...asynq.Option) error) *MockTaskDistributor_DistributeTaskAuditLogExport_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuditRepository creates a new instance of MockAuditRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuditRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuditRepository {
	m := &MockAuditRepository{}
	m.Mock.Test(t)

	t.Cleanup(func() { m.AssertExpectations(t) })

	return m
}

// MockAuditRepository is an autogenerated mock type for the AuditRepository type
type MockAuditRepository struct {
	mock.Mock
}

type MockAuditRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuditRepository) EXPECT() *MockAuditRepository_Expecter {
	return &MockAuditRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockAuditRepository
func (_mock *MockAuditRepository) Create(ctx context.Context, log *entity.AuditLog) error {
	ret := _mock.Called(ctx, log)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.AuditLog) error); ok {
		r0 = returnFunc(ctx, log)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuditRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockAuditRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - log *entity.AuditLog
func (_e *MockAuditRepository_Expecter) Create(ctx interface{}, log interface{}) *MockAuditRepository_Create_Call {
	return &MockAuditRepository_Create_Call{Call: _e.mock.On("Create", ctx, log)}
}

func (_c *MockAuditRepository_Create_Call) Run(run func(ctx context.Context, log *entity.AuditLog)) *MockAuditRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.AuditLog
		if args[1] != nil {
			arg1 = args[1].(*entity.AuditLog)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuditRepository_Create_Call) Return(err error) *MockAuditRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuditRepository_Create_Call) RunAndReturn(run func(ctx context.Context, log *entity.AuditLog) error) *MockAuditRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOutbox provides a mock function for the type MockAuditRepository
func (_mock *MockAuditRepository) CreateOutbox(ctx context.Context, outbox *entity.AuditOutbox) error {
	ret := _mock.Called(ctx, outbox)

	if len(ret) == 0 {
		panic("no return value specified for CreateOutbox")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.AuditOutbox) error); ok {
		r0 = returnFunc(ctx, outbox)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuditRepository_CreateOutbox_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOutbox'
type MockAuditRepository_CreateOutbox_Call struct {
	*mock.Call
}

// CreateOutbox is a helper method to define mock.On call
//   - ctx context.Context
//   - outbox *entity.AuditOutbox
func (_e *MockAuditRepository_Expecter) CreateOutbox(ctx interface{}, outbox interface{}) *MockAuditRepository_CreateOutbox_Call {
	return &MockAuditRepository_CreateOutbox_Call{Call: _e.mock.On("CreateOutbox", ctx, outbox)}
}

func (_c *MockAuditRepository_CreateOutbox_Call) Run(run func(ctx context.Context, outbox *entity.AuditOutbox)) *MockAuditRepository_CreateOutbox_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.AuditOutbox
		if args[1] != nil {
			arg1 = args[1].(*entity.AuditOutbox)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuditRepository_CreateOutbox_Call) Return(err error) *MockAuditRepository_CreateOutbox_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuditRepository_CreateOutbox_Call) RunAndReturn(run func(ctx context.Context, outbox *entity.AuditOutbox) error) *MockAuditRepository_CreateOutbox_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteLogsOlderThan provides a mock function for the type MockAuditRepository
func (_mock *MockAuditRepository) DeleteLogsOlderThan(ctx context.Context, cutoffTime int64) error {
	ret := _mock.Called(ctx, cutoffTime)

	if len(ret) == 0 {
		panic("no return value specified for DeleteLogsOlderThan")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, cutoffTime)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuditRepository_DeleteLogsOlderThan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteLogsOlderThan'
type MockAuditRepository_DeleteLogsOlderThan_Call struct {
	*mock.Call
}

// DeleteLogsOlderThan is a helper method to define mock.On call
//   - ctx context.Context
//   - cutoffTime int64
func (_e *MockAuditRepository_Expecter) DeleteLogsOlderThan(ctx interface{}, cutoffTime interface{}) *MockAuditRepository_DeleteLogsOlderThan_Call {
	return &MockAuditRepository_DeleteLogsOlderThan_Call{Call: _e.mock.On("DeleteLogsOlderThan", ctx, cutoffTime)}
}

func (_c *MockAuditRepository_DeleteLogsOlderThan_Call) Run(run func(ctx context.Context, cutoffTime int64)) *MockAuditRepository_DeleteLogsOlderThan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuditRepository_DeleteLogsOlderThan_Call) Return(err error) *MockAuditRepository_DeleteLogsOlderThan_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuditRepository_DeleteLogsOlderThan_Call) RunAndReturn(run func(ctx context.Context, cutoffTime int64) error) *MockAuditRepository_DeleteLogsOlderThan_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteOutbox provides a mock function for the type MockAuditRepository
func (_mock *MockAuditRepository) DeleteOutbox(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOutbox")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuditRepository_DeleteOutbox_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteOutbox'
type MockAuditRepository_DeleteOutbox_Call struct {
	*mock.Call
}

// DeleteOutbox is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockAuditRepository_Expecter) DeleteOutbox(ctx interface{}, id interface{}) *MockAuditRepository_DeleteOutbox_Call {
	return &MockAuditRepository_DeleteOutbox_Call{Call: _e.mock.On("DeleteOutbox", ctx, id)}
}

func (_c *MockAuditRepository_DeleteOutbox_Call) Run(run func(ctx context.Context, id string)) *MockAuditRepository_DeleteOutbox_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuditRepository_DeleteOutbox_Call) Return(err error) *MockAuditRepository_DeleteOutbox_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuditRepository_DeleteOutbox_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockAuditRepository_DeleteOutbox_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllDynamic provides a mock function for the type MockAuditRepository
func (_mock *MockAuditRepository) FindAllDynamic(ctx context.Context, filter *querybuilder.DynamicFilter) ([]*entity.AuditLog, int64, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for FindAllDynamic")
	}

	var r0 []*entity.AuditLog
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *querybuilder.DynamicFilter) ([]*entity.AuditLog, int64, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *querybuilder.DynamicFilter) []*entity.AuditLog); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.AuditLog)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *querybuilder.DynamicFilter) int64); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, *querybuilder.DynamicFilter) error); ok {
		r2 = returnFunc(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockAuditRepository_FindAllDynamic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllDynamic'
type MockAuditRepository_FindAllDynamic_Call struct {
	*mock.Call
}

// FindAllDynamic is a helper method to define mock.On call
//   - ctx context.Context
//   - filter *querybuilder.DynamicFilter
func (_e *MockAuditRepository_Expecter) FindAllDynamic(ctx interface{}, filter interface{}) *MockAuditRepository_FindAllDynamic_Call {
	return &MockAuditRepository_FindAllDynamic_Call{Call: _e.mock.On("FindAllDynamic", ctx, filter)}
}

func (_c *MockAuditRepository_FindAllDynamic_Call) Run(run func(ctx context.Context, filter *querybuilder.DynamicFilter)) *MockAuditRepository_FindAllDynamic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *querybuilder.DynamicFilter
		if args[1] != nil {
			arg1 = args[1].(*querybuilder.DynamicFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuditRepository_FindAllDynamic_Call) Return(auditLogs []*entity.AuditLog, n int64, err error) *MockAuditRepository_FindAllDynamic_Call {
	_c.Call.Return(auditLogs, n, err)
	return _c
}

func (_c *MockAuditRepository_FindAllDynamic_Call) RunAndReturn(run func(ctx context.Context, filter *querybuilder.DynamicFilter) ([]*entity.AuditLog, int64, error)) *MockAuditRepository_FindAllDynamic_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllInBatches provides a mock function for the type MockAuditRepository
func (_mock *MockAuditRepository) FindAllInBatches(ctx context.Context, startTime int64, endTime int64, batchSize int, process func([]*entity.AuditLog) error) error {
	ret := _mock.Called(ctx, startTime, endTime, batchSize, process)

	if len(ret) == 0 {
		panic("no return value specified for FindAllInBatches")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64, int, func([]*entity.AuditLog) error) error); ok {
		r0 = returnFunc(ctx, startTime, endTime, batchSize, process)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuditRepository_FindAllInBatches_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllInBatches'
type MockAuditRepository_FindAllInBatches_Call struct {
	*mock.Call
}

// FindAllInBatches is a helper method to define mock.On call
//   - ctx context.Context
//   - startTime int64
//   - endTime int64
//   - batchSize int
//   - process func([]*entity.AuditLog) error
func (_e *MockAuditRepository_Expecter) FindAllInBatches(ctx interface{}, startTime interface{}, endTime interface{}, batchSize interface{}, process interface{}) *MockAuditRepository_FindAllInBatches_Call {
	return &MockAuditRepository_FindAllInBatches_Call{Call: _e.mock.On("FindAllInBatches", ctx, startTime, endTime, batchSize, process)}
}

func (_c *MockAuditRepository_FindAllInBatches_Call) Run(run func(ctx context.Context, startTime int64, endTime int64, batchSize int, process func([]*entity.AuditLog) error)) *MockAuditRepository_FindAllInBatches_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 func([]*entity.AuditLog) error
		if args[4] != nil {
			arg4 = args[4].(func([]*entity.AuditLog) error)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockAuditRepository_FindAllInBatches_Call) Return(err error) *MockAuditRepository_FindAllInBatches_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuditRepository_FindAllInBatches_Call) RunAndReturn(run func(ctx context.Context, startTime int64, endTime int64, batchSize int, process func([]*entity.AuditLog) error) error) *MockAuditRepository_FindAllInBatches_Call {
	_c.Call.Return(run)
	return _c
}

// FindPendingOutbox provides a mock function for the type MockAuditRepository
func (_mock *MockAuditRepository) FindPendingOutbox(ctx context.Context, limit int) ([]*entity.AuditOutbox, error) {
	ret := _mock.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindPendingOutbox")
	}

	var r0 []*entity.AuditOutbox
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]*entity.AuditOutbox, error)); ok {
		return returnFunc(ctx, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []*entity.AuditOutbox); ok {
		r0 = returnFunc(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.AuditOutbox)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuditRepository_FindPendingOutbox_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindPendingOutbox'
type MockAuditRepository_FindPendingOutbox_Call struct {
	*mock.Call
}

// FindPendingOutbox is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
func (_e *MockAuditRepository_Expecter) FindPendingOutbox(ctx interface{}, limit interface{}) *MockAuditRepository_FindPendingOutbox_Call {
	return &MockAuditRepository_FindPendingOutbox_Call{Call: _e.mock.On("FindPendingOutbox", ctx, limit)}
}

func (_c *MockAuditRepository_FindPendingOutbox_Call) Run(run func(ctx context.Context, limit int)) *MockAuditRepository_FindPendingOutbox_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuditRepository_FindPendingOutbox_Call) Return(auditOutboxs []*entity.AuditOutbox, err error) *MockAuditRepository_FindPendingOutbox_Call {
	_c.Call.Return(auditOutboxs, err)
	return _c
}

func (_c *MockAuditRepository_FindPendingOutbox_Call) RunAndReturn(run func(ctx context.Context, limit int) ([]*entity.AuditOutbox, error)) *MockAuditRepository_FindPendingOutbox_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOutboxStatus provides a mock function for the type MockAuditRepository
func (_mock *MockAuditRepository) UpdateOutboxStatus(ctx context.Context, id string, status string, lastError string) error {
	ret := _mock.Called(ctx, id, status, lastError)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOutboxStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, id, status, lastError)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuditRepository_UpdateOutboxStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOutboxStatus'
type MockAuditRepository_UpdateOutboxStatus_Call struct {
	*mock.Call
}

// UpdateOutboxStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - status string
//   - lastError string
func (_e *MockAuditRepository_Expecter) UpdateOutboxStatus(ctx interface{}, id interface{}, status interface{}, lastError interface{}) *MockAuditRepository_UpdateOutboxStatus_Call {
	return &MockAuditRepository_UpdateOutboxStatus_Call{Call: _e.mock.On("UpdateOutboxStatus", ctx, id, status, lastError)}
}

func (_c *MockAuditRepository_UpdateOutboxStatus_Call) Run(run func(ctx context.Context, id string, status string, lastError string)) *MockAuditRepository_UpdateOutboxStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockAuditRepository_UpdateOutboxStatus_Call) Return(err error) *MockAuditRepository_UpdateOutboxStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuditRepository_UpdateOutboxStatus_Call) RunAndReturn(run func(ctx context.Context, id string, status string, lastError string) error) *MockAuditRepository_UpdateOutboxStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuditUseCase creates a new instance of MockAuditUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuditUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuditUseCase {
	m := &MockAuditUseCase{}
	m.Mock.Test(t)

	t.Cleanup(func() { m.AssertExpectations(t) })

	return m
}

// MockAuditUseCase is an autogenerated mock type for the AuditUseCase type
type MockAuditUseCase struct {
	mock.Mock
}

type MockAuditUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuditUseCase) EXPECT() *MockAuditUseCase_Expecter {
	return &MockAuditUseCase_Expecter{mock: &_m.Mock}
}

// ExportLogs provides a mock function for the type MockAuditUseCase
func (_mock *MockAuditUseCase) ExportLogs(ctx context.Context, fromDate string, toDate string, process func([]model.AuditLogResponse) error) error {
	ret := _mock.Called(ctx, fromDate, toDate, process)

	if len(ret) == 0 {
		panic("no return value specified for ExportLogs")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, func([]model.AuditLogResponse) error) error); ok {
		r0 = returnFunc(ctx, fromDate, toDate, process)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuditUseCase_ExportLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExportLogs'
type MockAuditUseCase_ExportLogs_Call struct {
	*mock.Call
}

// ExportLogs is a helper method to define mock.On call
//   - ctx context.Context
//   - fromDate string
//   - toDate string
//   - process func([]model.AuditLogResponse) error
func (_e *MockAuditUseCase_Expecter) ExportLogs(ctx interface{}, fromDate interface{}, toDate interface{}, process interface{}) *MockAuditUseCase_ExportLogs_Call {
	return &MockAuditUseCase_ExportLogs_Call{Call: _e.mock.On("ExportLogs", ctx, fromDate, toDate, process)}
}

func (_c *MockAuditUseCase_ExportLogs_Call) Run(run func(ctx context.Context, fromDate string, toDate string, process func([]model.AuditLogResponse) error)) *MockAuditUseCase_ExportLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 func([]model.AuditLogResponse) error
		if args[3] != nil {
			arg3 = args[3].(func([]model.AuditLogResponse) error)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockAuditUseCase_ExportLogs_Call) Return(err error) *MockAuditUseCase_ExportLogs_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuditUseCase_ExportLogs_Call) RunAndReturn(run func(ctx context.Context, fromDate string, toDate string, process func([]model.AuditLogResponse) error) error) *MockAuditUseCase_ExportLogs_Call {
	_c.Call.Return(run)
	return _c
}

// ExportLogsAsync provides a mock function for the type MockAuditUseCase
func (_mock *MockAuditUseCase) ExportLogsAsync(ctx context.Context, userID string, orgID string, fromDate string, toDate string, format string) error {
	ret := _mock.Called(ctx, userID, orgID, fromDate, toDate, format)

	if len(ret) == 0 {
		panic("no return value specified for ExportLogsAsync")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string, string) error); ok {
		r0 = returnFunc(ctx, userID, orgID, fromDate, toDate, format)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuditUseCase_ExportLogsAsync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExportLogsAsync'
type MockAuditUseCase_ExportLogsAsync_Call struct {
	*mock.Call
}

// ExportLogsAsync is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - orgID string
//   - fromDate string
//   - toDate string
//   - format string
func (_e *MockAuditUseCase_Expecter) ExportLogsAsync(ctx interface{}, userID interface{}, orgID interface{}, fromDate interface{}, toDate interface{}, format interface{}) *MockAuditUseCase_ExportLogsAsync_Call {
	return &MockAuditUseCase_ExportLogsAsync_Call{Call: _e.mock.On("ExportLogsAsync", ctx, userID, orgID, fromDate, toDate, format)}
}

func (_c *MockAuditUseCase_ExportLogsAsync_Call) Run(run func(ctx context.Context, userID string, orgID string, fromDate string, toDate string, format string)) *MockAuditUseCase_ExportLogsAsync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockAuditUseCase_ExportLogsAsync_Call) Return(err error) *MockAuditUseCase_ExportLogsAsync_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuditUseCase_ExportLogsAsync_Call) RunAndReturn(run func(ctx context.Context, userID string, orgID string, fromDate string, toDate string, format string) error) *MockAuditUseCase_ExportLogsAsync_Call {
	_c.Call.Return(run)
	return _c
}

// GetLogsDynamic provides a mock function for the type MockAuditUseCase
func (_mock *MockAuditUseCase) GetLogsDynamic(ctx context.Context, filter *querybuilder.DynamicFilter) ([]model.AuditLogResponse, int64, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetLogsDynamic")
	}

	var r0 []model.AuditLogResponse
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *querybuilder.DynamicFilter) ([]model.AuditLogResponse, int64, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *querybuilder.DynamicFilter) []model.AuditLogResponse); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.AuditLogResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *querybuilder.DynamicFilter) int64); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, *querybuilder.DynamicFilter) error); ok {
		r2 = returnFunc(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockAuditUseCase_GetLogsDynamic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLogsDynamic'
type MockAuditUseCase_GetLogsDynamic_Call struct {
	*mock.Call
}

// GetLogsDynamic is a helper method to define mock.On call
//   - ctx context.Context
//   - filter *querybuilder.DynamicFilter
func (_e *MockAuditUseCase_Expecter) GetLogsDynamic(ctx interface{}, filter interface{}) *MockAuditUseCase_GetLogsDynamic_Call {
	return &MockAuditUseCase_GetLogsDynamic_Call{Call: _e.mock.On("GetLogsDynamic", ctx, filter)}
}

func (_c *MockAuditUseCase_GetLogsDynamic_Call) Run(run func(ctx context.Context, filter *querybuilder.DynamicFilter)) *MockAuditUseCase_GetLogsDynamic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *querybuilder.DynamicFilter
		if args[1] != nil {
			arg1 = args[1].(*querybuilder.DynamicFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuditUseCase_GetLogsDynamic_Call) Return(auditLogResponses []model.AuditLogResponse, n int64, err error) *MockAuditUseCase_GetLogsDynamic_Call {
	_c.Call.Return(auditLogResponses, n, err)
	return _c
}

func (_c *MockAuditUseCase_GetLogsDynamic_Call) RunAndReturn(run func(ctx context.Context, filter *querybuilder.DynamicFilter) ([]model.AuditLogResponse, int64, error)) *MockAuditUseCase_GetLogsDynamic_Call {
	_c.Call.Return(run)
	return _c
}

// LogActivity provides a mock function for the type MockAuditUseCase
func (_mock *MockAuditUseCase) LogActivity(ctx context.Context, req model.CreateAuditLogRequest) error {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for LogActivity")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.CreateAuditLogRequest) error); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuditUseCase_LogActivity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LogActivity'
type MockAuditUseCase_LogActivity_Call struct {
	*mock.Call
}

// LogActivity is a helper method to define mock.On call
//   - ctx context.Context
//   - req model.CreateAuditLogRequest
func (_e *MockAuditUseCase_Expecter) LogActivity(ctx interface{}, req interface{}) *MockAuditUseCase_LogActivity_Call {
	return &MockAuditUseCase_LogActivity_Call{Call: _e.mock.On("LogActivity", ctx, req)}
}

func (_c *MockAuditUseCase_LogActivity_Call) Run(run func(ctx context.Context, req model.CreateAuditLogRequest)) *MockAuditUseCase_LogActivity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.CreateAuditLogRequest
		if args[1] != nil {
			arg1 = args[1].(model.CreateAuditLogRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuditUseCase_LogActivity_Call) Return(err error) *MockAuditUseCase_LogActivity_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuditUseCase_LogActivity_Call) RunAndReturn(run func(ctx context.Context, req model.CreateAuditLogRequest) error) *MockAuditUseCase_LogActivity_Call {
	_c.Call.Return(run)
	return _c
}
