from pathlib import Path

root = Path(__file__).resolve().parents[2]
skills_dir = root / '.agents' / 'skills'

skills = {
'api-endpoint': ('Use when adding or changing a backend API endpoint, route protection, or frontend-consumed contract.', ['AGENTS.md', 'llm/cache/api-contracts.md', 'llm/cache/backend-map.md', 'llm/workflows/api-endpoint.md'], ['Confirm route owner in `internal/router/router.go` and module routes.', 'Define request, response, auth, tenant, and API-key scope needs.', 'Implement controller -> usecase -> repository changes.', 'Update Swagger and frontend consumers when contract is public.', 'Run targeted verification and report exact command results.']),
'brainstorm': ('Use when exploring approaches for a feature, refactor, or architecture decision in this repo.', ['relevant `llm/cache/*.md`', 'relevant `llm/conventions/*.md`', 'closest live code precedent'], ['Clarify goal and constraints from repo context.', 'Compare 2-3 approaches against current module boundaries.', 'Prefer approach preserving auth, tenant, Casbin, and contract safety.', 'Save durable investigation to `llm/research/` if useful.']),
'cross-stack-change': ('Use when a change spans Go backend plus `apps/web`, `apps/client`, or shared workspace packages.', ['AGENTS.md', 'llm/cache/api-contracts.md', 'llm/cache/frontend-map.md', 'llm/cache/backend-map.md', 'llm/workflows/cross-stack-change.md'], ['Establish backend contract and route behavior first.', 'Update shared types, proxies, and app consumers.', 'Check both active apps if either can consume changed path.', 'Verify auth, cookie, header, and tenant forwarding behavior.']),
'database-transactions': ('Use when writing multi-step persistence changes that must commit atomically in GORM-backed backend code.', ['llm/conventions/database.md', 'llm/cache/domain-rules.md', 'target module usecase and repository files'], ['Confirm all-or-nothing write boundary.', 'Keep dependent writes inside single transaction pattern used by repo.', 'Preserve tenant, auth, and Casbin semantics inside transaction when relevant.', 'Add failure-path verification where practical.']),
'debugging-difficult-bugs': ('Use early when debugging medium or hard bugs involving runtime state, ordering, persistence, concurrency, auth, tenant, or external services.', ['relevant cache and exact runtime path'], ['Reproduce with tests or narrow code trace before editing.', 'Capture evidence from logs, payloads, DB state, or middleware layering.', 'Prove root cause before patching.', 'Remove temporary instrumentation unless intentionally kept.']),
'design': ('Use when designing a new feature or system change before implementation.', ['relevant cache, domain rules, and live wiring'], ['Define user flow, module owner, data model, and contract boundaries.', 'Record tradeoffs and risks against current repo architecture.', 'Save durable design notes to `llm/plans/` or `llm/research/`.']),
'e2e-test': ('Use when testing a feature flow end-to-end through browser or full request lifecycle.', ['changed diff and target workflow'], ['Use `login` if auth is required.', 'Drive exact user flow.', 'Capture failure evidence.', 'Save reusable flow to `llm/test-playbooks/` if valuable.']),
'execute': ('Use when executing an approved implementation plan in this Go plus TypeScript monorepo.', ['llm/tasks/todo.md'], ['Load more specific skill matching current task.', 'Implement one coherent slice at a time.', 'Mark progress in `llm/tasks/todo.md` for multi-step work.', 'Run targeted verification before final review.']),
'feature': ('Use when implementing a new feature in backend, frontend, or both.', ['AGENTS.md', 'llm/cache/project-overview.md', 'llm/cache/architecture.md', 'llm/cache/domain-rules.md', 'llm/workflows/feature.md'], ['Define smallest coherent slice.', 'Confirm owning module and contract boundaries.', 'Implement backend-first if persisted behavior or API changes.', 'Update frontend consumers only after contract is clear.', 'Run `self-review` before handoff.']),
'forms': ('Use when building or changing forms and validation across frontend apps and backend API.', ['llm/cache/frontend-map.md', 'llm/cache/api-contracts.md', 'validation precedents'], ['Keep frontend validation aligned with backend validation tags and responses.', 'Verify loading, error, and success states.', 'Check submitted payload against actual backend contract.']),
'go-service': ('Use when implementing or changing backend business logic in Go modules, usecases, repositories, or worker-owned flows.', ['AGENTS.md', 'llm/cache/backend-map.md', 'llm/cache/module-map.md', 'llm/conventions/golang.md', 'llm/workflows/go-service.md'], ['Find owning module and constructor wiring.', 'Keep business rules in usecase layer and persistence in repository layer.', 'Preserve context, tenant, session, and Casbin boundaries.', 'Run narrow package tests first.']),
'improve': ('Use when making reviewer-facing improvements, cleanup, hardening, or maintainability upgrades without changing product intent.', ['relevant cache and live precedent'], ['State current pain clearly.', 'Find owning layer.', 'Make smallest high-value improvement.', 'Save larger follow-up ideas to `llm/recommendations/` or `llm/plans/improve/`.']),
'login': ('Use when browser, E2E, or smoke verification needs authenticated setup.', ['apps/web or apps/client auth flow'], ['Identify which app owns flow.', 'Prefer existing test or manual login pattern.', 'Keep auth flow aligned with backend session and cookie behavior.', 'Record reusable steps in `llm/test-playbooks/` if stable.']),
'plan': ('Use when work needs a staged implementation plan, phased rollout, or scoped checklist before editing.', ['relevant cache and workflow files'], ['Break work into coherent verifiable slices.', 'Store active task state in `llm/tasks/todo.md`.', 'Store durable multi-stage plans in `llm/plans/`.']),
'pr-explainer': ('Use when explaining a change set to reviewer with problem, solution, verification, and risk framing.', ['current diff'], ['Group changes by feature area.', 'Explain problem, solution, verification, and residual risk.', 'Keep reviewer-facing and factual.']),
'pr-splitter': ('Use when current branch should be split into smaller focused change groups.', ['current diff and commit history'], ['Group by independent concern.', 'Propose split order and file ownership.', 'Do not do destructive git operations without approval.']),
'receiving-code-review': ('Use when addressing reviewer comments on an existing patch or branch.', ['review comments exactly'], ['Classify architectural vs bug vs style concerns.', 'Make smallest targeted fix.', 'Re-verify affected behavior.']),
'research': ('Use when researching technical or product approaches before design or implementation decisions.', ['internal precedents and relevant references'], ['Define research questions.', 'Separate facts from recommendations.', 'Save durable findings to `llm/research/`.']),
'self-review': ('Use when changes are complete and need correctness, maintainability, and boundary review before handoff.', ['current diff'], ['Check correct layer ownership.', 'Check auth, tenant, API-key, and Casbin boundaries.', 'Check contract changes updated consumers.', 'Check verification is proportional and reported honestly.', 'Avoid unrelated edits.']),
'smoke-test': ('Use when running a quick end-to-end check that core app pages or routes still work after changes.', ['target app or backend run command'], ['Use `login` if auth is required.', 'Visit core pages or routes relevant to change.', 'Check visible errors, server failures, and broken navigation.', 'Report exact paths checked.']),
'systematic-debugging': ('Use when encountering any bug, failing test, or unexpected behavior before proposing fixes.', ['relevant cache and workflow'], ['Identify failing layer precisely.', 'Reproduce or trace exact path.', 'Gather evidence before editing.', 'State root cause.', 'Fix minimally.', 'Verify narrow path first.']),
'test-driven-development': ('Use when implementing a feature or bugfix starting from the best available failing test layer.', ['target test conventions'], ['Pick best test layer.', 'Write or adjust failing test.', 'Confirm failure reason.', 'Implement minimal code.', 'Re-run narrow test.', 'Refactor after green.']),
'ui': ('Use when building, reviewing, or polishing frontend UI in `apps/web`, `apps/client`, or shared packages.', ['llm/cache/frontend-map.md', 'llm/conventions/typescript.md'], ['Confirm which app owns screen or route.', 'Reuse existing components and shared packages.', 'Check loading, empty, error, and success states.', 'Verify visually or through browser flow when practical.']),
'using-git-worktrees': ('Use when feature work needs isolation from current workspace state.', ['current workspace state'], ['Prefer existing harness/worktree tooling if available.', 'Do not discard uncommitted work.', 'Explain isolation choice.']),
'verification-before-completion': ('Use when about to claim work is complete, fixed, or passing.', ['changed layers'], ['Run targeted verification for each changed layer.', 'If contract changed, verify producer and consumer.', 'Report exact commands and results.', 'State skipped verification honestly.']),
'writing-skills': ('Use when creating, editing, or validating agent skills for this repo.', ['AGENTS.md', 'llm/workflows/', 'llm/conventions/'], ['Keep trigger clear in `description`.', 'Keep `SKILL.md` concise.', 'Put repo facts in `llm/cache`, not long skill bodies.', 'Remove stale stack assumptions.']),
}

for name, (description, read_first, workflow) in skills.items():
    path = skills_dir / name / 'SKILL.md'
    path.parent.mkdir(parents=True, exist_ok=True)
    read_lines = ''.join(f'- {item}\n' for item in read_first)
    workflow_lines = ''.join(f'{idx}. {item}\n' for idx, item in enumerate(workflow, start=1))
    title = ' '.join(part.capitalize() for part in name.replace('-', ' ').split())
    path.write_text(f'''---\nname: {name}\ndescription: {description}\n---\n\n# {title}\n\n## Read First\n{read_lines}\n## Workflow\n{workflow_lines}''')

print(f'wrote {len(skills)} skills into {skills_dir}')
